### PR TITLE
Fix translations

### PR DESCRIPTION
**Pull request by mikhailnov**
Some menu entries were not translated in Russian, some were not transalted in all languages. Fixed them.
Screenshot bellow shows untranslated strings, now they are translated.
DeepinScreenshot_выберите-область_20200531044140

### CODE REVIEW

**Comment by JamesCrook** [comment]
Thanks.  

But 
(a) Please only change po files for the languages you offer to translate (even if via script).
(b) Please do updated po files for your own language (Russian) via the translator's email list, where conflicts between different translators/translations can be resolved, and general issues with translatability that affect all translations can be discussed with all translators.

I generally prefer to receive updated .po files via that list, rather than as pull requests.  

Pull request rejected.

**Comment by mikhailnov** [comment]
a) as you see, I changed a string in the source code, so it was necessary to update all pot and po files, how do you suggest to handle this?
b) ok, I will write there, but I would suggest that an updated po file is pull requested after it is accepted in the list

**Comment by JamesCrook** [comment]
a) Just request the change in the source (pull request is fine).  If it is only a string change, maybe mention it is a 'Wording change'.  The script will be run at the start of translation freeze, and translators will then be asked for updated translations.
b) That's not how we do it.  After end of translation freeze stage, and before making rcs, I diff the new .po against the old, and can sometimes pick up mistakes even though I don't speak the languages.  The order of strings is unchanged which makes the diffing actually useful.

**Comment by mikhailnov** [comment]
Thanks for explaining. So, I should first request a change of the string without changing anything in locale/. Send a PR with that change. Then wait for long and only then have a chance to suggest my translation of the new wording?

**Comment by JamesCrook** [comment]
> Thanks for explaining. So, I should first request a change of the string without changing anything in locale/. Send a PR with that change. 

Correct.

You don't need to suggest the new wording.  The existing translator will do it.

If you want to get involved in translating, then you really need to be subscribed to the translators list and work with existing translators there.

**Pull request closed without merging**
