### PR TITLE
Bug2107: Mac Enter should press def. button when text entry focused

### PR DESCRIPTION
**Pull request by Paul-Licameli**
# Pull Requests

If you are submitting a pull request, read https://wiki.audacityteam.org/wiki/GitHub_Pull_Requests 

## The key points: 

* Come over talk with us at the audacity devel email list. If you just rely on the GitHub pull request messages, you may find we ignore or close the pull request for what does not seem to you to be a good reason. Please come and talk. 

* Translators should subscribe to audacity translators email list instead.  The translators list is also the right place for most translation discussion. 

There is a bit more on our wiki about how we use the pull requests and the labels that can be attached to pull requests.

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Amended as suggested by David to test that the event is char hook, not key up.

**Comment by JamesCrook** [comment]
This is a very recently reported P4 and is going to wait for review/assessment until 2.3.3.

**Comment by DavidBailes** [comment]
On Wed, 1 May 2019 at 23:36, James Crook <notifications@github.com> wrote:

> This is a very recently reported P4 and is going to wait for
> review/assessment until 2.3.3.
>
Additional info:
When I recently added a number of mac accessibility bugs, I just left them
on the default p4 level. I was going to let Q&A change this if required.
If this fix works, then I presume it would fix bug 1329, which is a P2.

David.

**Comment by JamesCrook** [comment]
Thanks David.  We have 36 accessibility bugs recorded in Bugzilla.  This possible fix for (now) two issues, one of which has not even yet been assessed as to its priority, can and will wait until 2.3.3.

**Comment by JamesCrook** [comment]
Tracked in Bugzilla, bug 2107.  Paul's fix applied and works.  Thanks Paul.
https://bugzilla.audacityteam.org/show_bug.cgi?id=2107

**Pull request closed without merging**
