### PR TITLE
Pipeclient usage help enhancement

### PR DESCRIPTION
**Pull request by CHRYSICS**
Resolves: *pipeClient.py usability (general)*

*The following changes attempt to improve usability of the interactive command-line by providing internal help functions for basic terminal use. This includes:*
* 'H': to view usage help
* 'C': to view list of all commands, and option to view param requirements for requested command
* 'M': to view list of all menus, and option to view param requirements for requested command

*In the usage help message, it explains how the general command syntax required for commands and the link to the scripting reference manual. The goal is to make it more clear how the terminal can be used and reveal the breadth of commands available for scripting and automation.*

h_command

*The view commands/Menus options are intended to quickly view all the possible command inputs, and reduce incorrect input errors.*

c_command

*(here user can input case-insensitive command id seen on screen and return usage details. Note no match or just pressing enters to terminal prompt)*

c_command2

*Similar to commands, menus returns a list and option to view usage details*

m_command

*(I did not check "no unnecessary changes" since this may seem to an unneeded feature, given the information available within the Audacity manual.  Instead this is aimed for Audacity users who explore the application and its functionality with a hands-on approach by enhancing internal documentation)*  

- [X] I signed [CLA](https://www.audacityteam.org/cla/)
- [X] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [X] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

**Comment by SteveDaulton** [comment]
Please use pylint or similar to avoid whitespace / PEP8 /other easily avoided issues.

It seems strange that you have to read the "H" help to be  aware of the available "C" and "M" options. Why not start the command line interface with a menu that provides all of the options?

Unfortunately I'm not able  to test much of the new functionality due to https://github.com/audacity/audacity/issues/1294

Perhaps, rather than assigning a long string to a variable in "usage_helper", you could include the help strings as standard Docstrings in  the appropriate functions, and then print them with something like:
`print(function_name.__doc__)`
This would have the added benefit that the new help would be included if the documentation was rendered with sphinx or similar.

The repeated use of "if <something> in command else" in "command_info" is rather ugly and makes the lines rather long. I expect that you can figure out a more easily readable way to  write that.

While not a hard and fast rule, I generally prefer "main()" to be at the end of a single page app, but regardless of that one case, it is better for the function definitions to be  in some kind of logical order. I shouldn't need to  search up and down the page to follow the code.

Terminal windows frequently default to 80 character width. Testing on Xubuntu, this line has an unwanted line wrap near the end (more than 80 characters):
```
    To include custom parameters, the scripting id must be followed by a colon ':',
```

**Comment by CHRYSICS** [comment]
Thank you Steve for the suggested Improvements!
## Major Update:
* To offload excessive code in main, a PipeTerminal Class was created that launches a pipeclient object and holds many of the built-in functionality.

## Updates:
* Ran file through with linter
* Built-in Commands are shown at launch of terminal
LaunchTerminal
* used docstrings to print help info (truthfully these still probably need to rearrange a bit more to match functions better). Currently pulling from the docstrings of PipeTerminal.__doc__, PipeTerminal.start.__doc__, and PipeTerminal.help.__doc__.
help_docstrings
help_docstrings2
* use of excessive "if else" in command info has been reduced using string formatting but can likely still be reduced further
* Main function placed at bottom

**Comment by CHRYSICS** [comment]
# Updates: 
* fetched upstream changes from master branch and verified pipeclient.py worked with new updates.
* Reworded CLI prompt message to include all built-in command options.
* fixed additional linting issues.

**Comment by LWinterberg** [comment]
Hello! We just [switched master to 4.0.0](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which makes this PR incompatible and/or obsolete as we're switching UI framework and reorganizing large parts of the codebase. 

Also, sorry for this comically large delay.

**Pull request closed without merging**
