### PR TITLE
AppData file update to v0.7+Ukrainian translation of AppData

### PR DESCRIPTION
**Pull request by yurchor**
This patch updates Audacity AppData file to the new version of standard [1] and adds Ukrainian translation.
 
Thanks for reviewing and committing the changes.

[1] http://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

### CODE REVIEW

**Comment by lllucius** [comment]
Looks like a good thing to me, but I agree James, it would be something that we'd want to have all of the translators do if we wanted to start maintaining the translations in here as well.

**Comment by JamesCrook** [comment]
As RM I've decided not to do this for 2.1.1.  
Yuri If you can persuade French and German translators on the translators list to do this for 2.1.2 too, then there is a good chance we will do translated versions for 2.1.2.

**Comment by trebmuh** [comment]
Yuri, can you tell me what would need to be done ? (french translator here)

**Comment by yurchor** [comment]
Hi,

Look at the diff:

https://github.com/yurchor/audacity/commit/5184faa1c2b94ed5401720b66e0f1cc732ac4b8d

It is enough to add your translation after each tag in the following format:

<some_tag>
Blah-blah-blah
</some_tag>
<some_tag xml:lang="fr">
Translation
</some_tag>

Thorough explanation:

http://www.freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html

Thanks in advance for your help.

**Comment by JamesCrook** [comment]
https://github.com/bdrung is a coder rather than a translator, but is active in Audacity, and as it is a small amount to translate and specifically for Linux, he may be willing to do so.  Worth asking.

**Comment by JamesCrook** [comment]
I should also have said he is German.

**Comment by trebmuh** [comment]
Hi James, if you'd be happy to merge Yuri's patch, I'd be able to commit the FR one afterward.
I'm pretty new with GIT's stuff. That said, my guestimate is that if I'm modifying the original file without Yuri's patch in, Yuri or me would have to redo a patch. Am I right here ?
I did read your comment about deciding not to do this before 2.1.2 so please, tell me what to do from here.
Cheers.

**Comment by JamesCrook** [comment]
Hi Trebmuh,

You can easily create a new branch in your repo that is a copy of yurchor/master and then make changes in your new branch.  When I later pick that up for 2.1.2 I will get his changes and your changes.  You are using the command line, not doing everything through GitHub web interface?  If so, then on your machine navigate to your audacity repo and do:

    git remote add yuri https://github.com/yurchor/audacity
    git fetch --all

to add yuri's repo and get up to date with it.  Now do 

    git checkout yuri/master
    git checkout -b appdata_branch

and your appdata_branch will be up to date with yuri's branch.  You can then add your changes.  Later you will push it to your github repo.

If you'd rather not try that, then just make your changes and later on I will merge the two branches.  I don't know if git tools will merge this file nicely, but if they don't I can hand edit to get the right end result.

**Comment by trebmuh** [comment]
OK done. I hope I did the right way with GIT. I'm only using the web interface for this i18n work James. Thanks for your comments, really appreciated.

**Comment by JamesCrook** [comment]
I've cherry picked your changes into my new appdata branch. The idea is that when we do add them for 2.1.2 they will all be in one place in the commit logs. 

Thanks.  LGTM.

--James

**Comment by trebmuh** [comment]
Awesome James. Thanks for this. Would you reckon that we should send an email to the audacity translations list in order to get some more other language commits and then, when merging this branch it'll be pretty consistent across languages support ?

**Comment by JamesCrook** [comment]
We're very much a 'doer decides' community.  

For it to get into 2.1.2 it must have the German translation too.  Also I will be taking feedback from the linux people on the developer list about AppData.  I want to check and get them to sign off on it going in with more translations.  Totally expecting them to be +1. The usual problem with translations, e.g. of website, is half completed translations and translations that haven't kept up with the changes.  This file is (a) small and (b) not changing often/fast, so there is low risk of that.

It doesn't need to have more than English, French, German, but if you would like to organise more on the translators list, you are welcome to.  

We will soon be making a change to the URLs in the file, but most unlikely to change the other text any time soon.

**Comment by trebmuh** [comment]
Great. I'll be waiting you to have a discussion with the linux people about AppData first since I do not want to rush people if that's finally a no-go.
Then, I'll take your point and get that proposition of translation on the translation list. The ball is yours :)

**Comment by DanWin** [comment]
You can now cherry-pick the German translation from https://github.com/DanWin/audacity/commit/b538f367df994a803d1a87067a1536d2b11e49b9

**Comment by trebmuh** [comment]
Awesome Dan !

**Comment by trebmuh** [comment]
+1 thanks for the '<' correction

**Pull request closed without merging**
