### PR TITLE
Lib channel

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: *(direct link to the issue)*

Depends on
- #4825
- #4844
- #4797

Split lib-channel from lib-track.

Define interfaces to iterate over a Track (or ChannelGroup, its new base) by
significant time intervals, alternatively to the iteration over Channels.

Define abstract ChannelInterval as the intersection of the information of a Channel
and a ChannelGroupInterval;  and Channel and ChannelGroupInterval each define
an iterator over those.

Thus these are somewhat like rows, columns, and cells of a matrix, and convenient
striding by either.

QA:
- [x] Known behavior changes to ignore:  In case of misalignments, right channel clip boundaries are ignored for snapping.
- [x] Briefly test display & interaction with the four kinds of tracks; and mono and stereo
- [x] Painting of track (not clip) names (a preference turns them on)
- [x] Resizing of track height and channel height
- [x] Time Shift Left and TimeShiftRight (under Extra > Edit), applied to selections within each of the four kinds of tracks (bind them to keystrokes to make repeated trail easy; these are important for accessibility)
- [x] Punch and roll recording
- [x] Dragging clips (left, right, and between tracks)
- [x] Undo and redo of channel height and minimization changes

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Rebased onto recent master after merging two dependencies.

**Comment by Paul-Licameli** [comment]
Rebased again.  All the dependencies are now merged

**Comment by Paul-Licameli** [comment]
Rebased onto #4887 which fixes a recent regression and changes Track.*

**Comment by Paul-Licameli** [comment]
More self-review of the time-shifting stuff to my own satisfaction now.

Rebased onto recent master.

Not dependent on bug fix #4885, which still has other blocking problems still to be figured out.

**Review by crsib — APPROVED** [review]

**Comment by Paul-Licameli** [comment]
Rebased onto more recent master, resolving unimportant conflict in comments

**Comment by dozzzzer** [comment]
Tested

**Pull request merged**
