### PR TITLE
Compressor v2 effect

### PR DESCRIPTION
**Pull request by mmmaisel**
The Compressor v2 effect is a downward compressor that, in
constrast to the existing compressor (see below), behaves
as someone would expect. It is implemented in a new effect to not break
existing legacy chains.

The new effect has two envelope detectors, a new one which is based on
an analog PT1 compressor and the legacy envelope detector from the old
compressor effect. Additionally, you can chose between RMS and peak
detection.

Sliders in the GUI with a very high dynamic range (e.g. attack and
release time) use a logarithmic scale to improve usability.

As mentioned earlier on the audacity-devel list, I extracted the plot and
slider-with-textbox widgets into separate classes. They are both
integrated into ShuttleGUI so they can be used elsewhere as well.

Envelope detectors and sample preprocessors (RMS and sliding-max)
are separate classes to keep the code modular and extensible.
Internally, the effect uses a four stage pipeline to buffer audio data.
This might be over-complicated for offline processing but allows unified
offline and realtime code-paths.

When using the new PT1 envelope detector, all parameters expect the
lookahead time are realtime capable. In case of the legacy envelope
detector, attack time is not realtime capable as an additional
limitation because it is implemented with lookahead.

### CODE REVIEW

**Comment by mmmaisel** [comment]
I'll nmever sign a CLA on Google docs.

**Comment by Tantacrul** [comment]
> I'll never sign a CLA on Google docs.

To be clear, you won't sign a CLA regardless of how it is presented to you, correct?

It's not merely an issue with a Google form, I assume?

If so, I'm very sorry you've decided to retract the PR but of course, I respect it.

**Comment by mmmaisel** [comment]
> > I'll never sign a CLA on Google docs.
> 
> To be clear, you won't sign a CLA regardless of how it is presented to you, correct?
> 
> It's not merely an issue with a Google form, I assume?
> 
> If so, I'm very sorry you've decided to retract the PR but of course, I respect the decision

Why should I sign a contract the gives nothing back to me?
Instead it demands lots of additional personal information beyond those in a git commit and sends them to google(forms).

**Comment by Tantacrul** [comment]
I understand. The CLA itself is a fundamental problem for you. Apologies that it doesn't work for you. Unfortunately, this is not something I have the ability to change.

**Pull request closed without merging**
