### PR TITLE
Fixed wrong button icons for track panel in high contrast and dark themes

### PR DESCRIPTION
**Pull request by nalin243**
Resolves:  #6815 

*Rotated the TCPChevron icon 180 degrees for dark and high contrast themes*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by LWinterberg** [comment]
Please rebase this onto release-3.6.0

**Comment by nalin243** [comment]
@LWinterberg I am not sure I did it correctly. If not I could just close this and open another pull request?

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @nalin243 's latest branch build for this:  audacity-win-3.7.0-alpha-20240708+0b1a329-x64
_(and note the Mac builds for this failed to work).

This now appears to work properly in this branch build with the correct icons now showing for collapse and expand in the TCP's of tracks for both Dark and High Contrast themes.

I tested>
1. stereo track
2. mono track
3. label track
4. time track

I tested these individually and with the **View > Track Size** commands for **Collapse** and **Expand**

**Comment by nalin243** [comment]
@petersampsonaudacity Let me just close this and make a new pull request. I had created my branched based off of master which is on 3.7.0 alpha.

**Pull request closed without merging**
