### PR TITLE
Add myself as a contributor

### PR DESCRIPTION
**Pull request by JoeS209**
Resolves: *(direct link to the issue)*

Add myself as a contributor.  I have fixed issues 5639, 5858, 5860, and both bugs in 7131.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by LWinterberg — APPROVED** [review]

**Comment by shoogle** [comment]
@JoeS209, can you remove the merge commits and rebase instead?

**Comment by JoeS209** [comment]
> @JoeS209, can you remove the merge commits and rebase instead?

Sorry.  Will try to get to that soon.  Machine is currently in the middle of a backup.

**Comment by JoeS209** [comment]
OK, that was nerve-wracking.  Hopefully I didn't screw anything up.

**Comment by LWinterberg** [comment]
this looks exactly right! And just like that you've learned how to rewrite git history - you're practically an expert now :)

**Comment by JoeS209** [comment]
> this looks exactly right! And just like that you've learned how to rewrite git history - you're practically an expert now :)

Too much power in the wrong hands...  :-)

**Pull request merged**
