### PR TITLE
Windows compile

### PR DESCRIPTION
**Pull request by tip2tail**

### CODE REVIEW

**Comment by windinthew** [comment]
Thanks, Mark. Actually we usually bump the version number to the current release after the release has been made, so 2.1.3 as now. When we gave the current version being developed, people compiling the current release complained.    

Perhaps we should say now "This document is for Audacity release 2.1.3 and for 2.2.0-alpha". Mostly, compile.txt would be correct for previous release and the following alpha at any given time.

**Comment by tip2tail** [comment]
Hi Gale,

Sorry - I misunderstood and thought we'd missed it on 2.1.3 release.  Do
you want me to change it to what you mentioned above?  Or do you want to
make the change?

Thanks,

Mark

**Comment by windinthew** [comment]
We had missed it for 2.1.3 release and it is certainly wrong now.  Bumping the version 
number in win/compile.txt should be done when setting IS_ALPHA back to 1 and 
updating the version numbers in src/Audacity.h. OTOH we don't mention Audacity
version at all in mac/Build.txt. Perhaps we should.

I'd say don't trouble to recommit. Whoever commits this to MASTER can decide.
I do think you should move your extra line in .gitignore under # Windows specific
but I assume whoever commits this will do that. Do you know if VS2015 adds the
same hidden folder to /win?

**Comment by windinthew** [comment]
To get this out the way I committed a slightly modified version at https://github.com/audacity/audacity/commit/930e834 , with the ignore moved into Windows-specific files and compile.txt saying it is for 2.1.3 but also works (currently)  with 2.2.0-alpha. Thanks.

**Pull request closed without merging**
