### PR TITLE
Updates Russian po file

### PR DESCRIPTION
**Pull request by dikonov**
Contains many fixes for errors, typos and mis-translations

# Pull Requests

If you are submitting a pull request, please read https://wiki.audacityteam.org/wiki/GitHub_Pull_Requests 

This same file was posted to the translation mailing list on April 17. as ru24.po-rev2

### CODE REVIEW

**Comment by JamesCrook** [comment]
Thanks.  However we're using the recent Russian translation from Alexander Kovalenko.  If you want to get your translations/changes in, please coordinate with him.  Telling him that his translation is terrible is not the way.  

You need to work with him to produce a translation you are both happy with.

**Comment by dikonov** [comment]
Alexander Kovalenko proved himself to be an incompetent translator (I assume that he has a different professional background) and he refuses to enter any linguistic discussion. 

His variant is 1) full of grave mistakes, some of which are just stupid. I have cited some of the errors in the forum and they can be found in the diff.  There are phrases distorted to the point of meaning the opposite in translation. 2) He uses jargon words (false friends and unnecessary borrowings from English) that are not comprehensible to normal Russian speakers outside of a small group. The translation supplied with Audacity 2.3.3 is so bad that I cannot use it even though I am able to "reverse engineer" the abracadabra because I am a linguist with professional background in translation and software localization.  Another former translator of Audacity Alexander Prokoudine (https://github.com/prokoudine) could be a mediator and confirm that  Alexander Kovalenko's style deviates from normal Russian and software localization standards. 

I started a project to translate Audacity user manual, but it has to be cancelled because it cannot be based on a such inadequate UI. Audacity looks amateurish in Russian.

**Comment by JamesCrook** [comment]
Vyacheslav - Audacity is a collaborative enterprise, so we need people who can work together well.  Yuri showed the 'right' way to deal with poor translation, which is to start with the incontrovertible errors, the misspellings.  Alexander responded to those, and with good grace.  

We have competing Slovak translations, competing Basque translations and competing Gaelic translations.  The translators are often passionate about why their translation is 'right'.  Whilst I am linguistically challenged, that is I don't speak Russian, Basque or Gaelic, I know enough to know that some issues are sloppiness (sloppy translator vs conscientious one), regional (North vs South) and tradition/style (franglais vs Française).  

How do we resolve these?  By making the problem more complex and more human.  We in Audacity need people who can work together, and we need people who are not fly by nights but who are here for the longer term.  I believe your translation is better, based on the errors/typos that Yuri presented.  Nevertheless I chose to use Alexander's rather than 'dethrone' him.  He has been with us for many translation cycles, and that is evidence that he is not a fly-by-night.  For all that I know, so far, your personality could be to snipe at people and then move on - and that's not something I want for Audacity.

I'd suggest that for 3.0.0, the next version of Audacity, you complete your translation of the one page Tour Guide.  If there are issues caused by poor translation needed in screenshots for that one page document that need correction, raise them in translation email list so they can be discussed and dealt with.

That gives me some evidence that you are not a fly-by contributor, and that it is worth working with you and Alexander to get a joint translation that is better than either would do on their own.

**Comment by dikonov** [comment]
I understand your position, and I must give justice to Alexander Kovalenko, who implemented some of the proposed fixes. The unresolved problem here is the overall style. It is technicaly possible to have two alternatives: Ruglish "jargon" version for selected geeks vs a "neutral" one for everyone else.

I got just two replies form Alexander. In the first letter he recommends me to use "Racetrack" (approximate reverse translation) instead of audio "Track" and "||PECET" (this nonsense should mimic the level of abracadabra for an English speaker) instead of "Preset". These wer the very words that shocked me in 2.3.3. A regular Russian, who does not know the corresponding English words may not understand it. I objected telling that the words are not technical terms and there are better native Russian equivalents.  The only response to my objections was "Everyone has a right to an opinion". I see it as a refusal to discuss and cooperate on Alexander's (and in a way Audacity Team's) side. 

Alexander is still welcome to use any proposed changes, but I would not like to be mentioned as an author of a translation that I deem defective and cannot control or fix.

**Comment by dikonov** [comment]
By the way, the Russian version of the Tour Guide is complete and available online at  https://wiki.audacityteam.org/wiki/Audacity_Tour_Guide/ru. All UI reference terms are the same as in Audacity 2.3.3 (Alexander's) version except for the "Track". This sole change is the-right-thing-to-do linguistically and is completely transparent.

**Comment by JamesCrook** [comment]
1) About the tour guide.  Great!  I have had a look and am glad it's complete. Using 'Track' instead of 'Racetrack' is 'the right thing' :-) .  You could if you like mention the Tour Guide is complete on the translation email list and thereby (perhaps) encourage others to translate into their languages - which in turn encourages us to do the work of getting a pdf version made and distributed, as it becomes more worthwhile with more languages.

2) Alexander Prokoudine could submit your translation as a pull request.  We'd almost certainly accept his translation over Alexander Kovalenko's, unless he was rude and ill mannered about it.  He has a longer history with the project than AK.  Once that is been done for three consecutive versions, with AP saying it's your translation, I'd say you are the clear incumbent, and you can submit directly.  Note - I actually prefer posting of translation .po files to translation list to pull requests so would prefer AP to do that to a pull request.  That is just one simple way it could all go.  I think between you you can find a good way, possibly better than that, that gets a good translation and that is seen to be 'fair'.

Thanks for showing some patience and understanding.  I am looking forward to us having better translation.

**Pull request closed without merging**
