### PR TITLE
Always default export to "Entire Project"

### PR DESCRIPTION
**Pull request by crsib**
Resolves: #5402 

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by DavidBailes** [comment]
@crib. This fix doesn't always default the export range to the entire project. The default export range is now the last used setting.

**Comment by crsib** [comment]
This is a kind of behavior that a lot of places in Audacity has. This can be changed easily, I'm not sure that it should.

In the very same dialog every other setting remembers the value used during the last export.

@LWinterberg please advise

**Review by vsverchinsky — APPROVED** [review]

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @crsib 's branch build:  audacity-win-3.4.0-alpha-20231030+c5fb3b0-x64

This works on first use if you have
a) multiple tracks
b) a non-empty label track
c) a selection
Then regardless if the above the "Entire Project" is properly offered 

BUT on next use it still remembers the previously used export range 0 an sometime inappropriately so - try these steps

1. purge the Audacity settings folder
2. get some audio - single track
3. add some labels
4. File > Export Audio
5. Observe: "Entire Project" is the default range offered
6. set the rang to "Multiple Files"
7. Export button to export the labeled ranges
8. Delete the Label Track
9. File > Export Audio
10. Observe: "Multiple Files" is still the default range offered (even though there a no labels and only a single track)

It's a bit smarter with Export - but not totally smart
1. purge the Audacity settings folder
2. get some audio - single track
3. select a portion of the track
4. File > Export Audio
5. Observe: "Entire Project" is the default range offered
6. set the range to be "Current selection"
7. Export button to export the selection
8. make a different selection
9. File > Export Audio
10. Observe: "Current selection" is the default range offered (remembered from last use)
11. Export button to export the selection
12. make a point "selection" - i.e. set a cursor position
13.  File Export >Audio
14. Observe: "Entire Project" is offered as the default range

**Comment by LWinterberg** [comment]
I think an important bit for usability is whether the user is aware of this option. If you've never used export multiple before and suddenly find your files getting chopped up after placing labels, it's super confusing. However, with this PR, you need to have used the export multiple option before, and it's likely that you have used it within the same session. Getting your files chopped up in this case may be a bit annoying, but chances are you know exactly what happened and also know exactly how to fix it.

**Review by vsverchinsky — APPROVED** [review]

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @crsib 's latest updated branch build for this:  audacity-win-3.4.0-alpha-20231030+6cc55d0-x64

This now looks **_much_** better to me.

Yes it now remembers that previously used range setting but now only applies that if and when it is appropriate - if it is not appropriate then "Entire Project" is offered.

@LWinterberg @crsib @vsverchinsky This looks good to go to me

**Pull request merged**
