### PR TITLE
Bug 2582 - Enh: Repeat last Process, Part 2

### PR DESCRIPTION
**Pull request by JohnColket**
Bug 2582 - Enh: Repeat last Process, Part 2

This commit implementsl features suggested by Peter And Steve and fixes Repeat NyQuist Command Tool.

It should close:
Bug 2582 - Enh: Repeat last Generator, Analyzer or Tool
Bug 2640 - Plot Spectrum and Contrast analyzers are not "Repeatable"
Bug 1019 - Plot Spectrum and Contrast analyzers are not "Repeatable"

(although it does not address the original issue reported in
Bug 1019 - Enh: Contrast and Plot Spectrum cannot be disabled in Plug-In Manager.)

This commit adds Plot Spectrum and Contrast Anaylyzer to the list of repeatable Analyzers;
This commit adds Macros, Palette, Screenshot, Run Benchmark, and Nyquist Prompt to the list of repeatable tools.

### CODE REVIEW

**Comment by JohnColket** [comment]
Cool, thank you, James.  - John

**Comment by JamesCrook** [comment]
You'll see in https://github.com/audacity/audacity/commit/67dff35a123297152b67bcc6bcb46787a80b05d4 I removed them from the menus, so they are just in the keyboard bindings - which is right.  They are for power users.  Let's not confuse new users.  See comment in that commit.

**Comment by JohnColket** [comment]
James,

  Good plan. Personally, I thought these menus were looking a little top
heavy myself, what with both Add/Remove... and Repeat...  It was a good
idea to set them aside.

  I had another idea that could be considered at some future time.  Add the
Repeat Last Process, which would be the umbrella.  That should prove to be
fairly straightforward to implement.  Later....

  And thanks for the time you spent on this as well.

- John

**Comment by SteveDaulton** [comment]
On Wed, 3 Feb 2021 at 17:01, JohnColket <notifications@github.com> wrote:

> James,
>
> Good plan. Personally, I thought these menus were looking a little top
> heavy myself, what with both Add/Remove... and Repeat... It was a good
> idea to set them aside.
>
> I had another idea that could be considered at some future time. Add the
> Repeat Last Process, which would be the umbrella. That should prove to be
> fairly straightforward to implement. Later....
>

Nice idea.

Perhaps the umbrella version could replace the individual "Repeat" commands
with a Preference to select which menus it works with? Perhaps that's too
much? Perhaps we could try out alternatives early in the 3.1.0 release
cycle and see what works best.

Steve

**Comment by Paul-Licameli** [comment]
I regret this merge.

Much done here that creates problems for rebasing of my many-more-modules branch onto latest master.

Changing CommandManager and Menus and EffectManager as done here just to support these things is a sign that something is wrong with the design.

I must look closer and consider how it ought to be rewritten.

**Comment by Paul-Licameli** [comment]
The growing switch statement in EffectUI::DoEffect is a sign that something is wrong with the design.  The testing for the special string "Nyquist Prompt" assumed to be identical to another string elsewhere in the program is a fragility.  Adding state variables to MenuManager just to support this isn't good either.

But my branch did rebase and build.  Still I'm bothered by some things in here and would look for another implementation in future consistent with a more decoupled plug-in architecture.

**Comment by JohnColket** [comment]
Thank you, Paul. - John

**Comment by Paul-Licameli** [comment]
I'm not saying redo it.  These points aren't obvious.

It's more for me to think about as I try to bring better structure to the whole.

**Comment by Paul-Licameli** [comment]
This may be a real problem.  Why was it necessary to delete these lines from CommandManager.cpp?  Did you make an error in rebasing?


-#if defined(BE_CAREFUL)
-      // Don't be tempted to do this unless you're willing to change how
-      // HandleMenuID() decides if a menu action should be performed.
-      // (see comments 6-9 in bug #2642 for symptoms)
-      else if (name == wxT("Copy"))
-         entry->id = wxID_COPY;
-      else if (name == wxT("Cut"))
-         entry->id = wxID_CUT;
-      else if (name == wxT("Delete"))
-         entry->id = wxID_CLEAR;
-      else if (name == wxT("Paste"))
-         entry->id = wxID_PASTE;
-      else if (name == wxT("SelectAll"))
-         entry->id = wxID_SELECTALL;
-#endif

**Comment by JamesCrook** [comment]
Paul, are you OK with it going through to 3.0.0 release in the current form
[and then perhaps a tidy up in 3.1.0]?

The reason I ask is because if you are not, then I feel we do not have time
to refactor it AND test that refactoring for 3.0.0.  So in that case it
should be reverted and held over to 3.1.0.

**Comment by JamesCrook** [comment]
BE_CAREFUL is not defined.  This is unused code.

The value of that code is the comment, the link to bug #2642 for
background, and I put that link back in.

**Comment by Paul-Licameli** [comment]
I do not mean my objections to be blocking for 3.0.0.

**Comment by JamesCrook** [comment]
OK.  Then let's tidy it up in 3.1.0.

**Comment by JohnColket** [comment]
Paul, yes, I think you are exactly correct.  - John

**Pull request merged**
