### PR TITLE
Observer fixes

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #2421 
Resolves: #2424
Resolves: #2426

Fix two mistakes in the recent Observers branch.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
@vsverchinsky your suspicion of object lifetime problems in uses of `CallAfter` was quite right, but we missed one of them.

**Comment by petersampsonaudacity** [comment]
@vsverchinsky Hi Vitaly - I tested this on W10 with @Paul-Licameli 's fix in his branch:
audacity-win-3.2.0-alpha-20220113+7129052-64bit

This seems to address the issues in this bug post - any chance you can do the review and pull this so that we can get a more workable 3.2.0 alpha to test against _(just to see if any other gremlins are now lurking)_.

**Review by vsverchinsky — APPROVED** [review]

**Comment by vsverchinsky** [comment]
> @vsverchinsky Hi Vitaly - I tested this on W10 with @Paul-Licameli 's fix in his branch: audacity-win-3.2.0-alpha-20220113+7129052-64bit
> 
> This seems to address the issues in this bug post - any chance you can do the review and pull this so that we can get a more workable 3.2.0 alpha to test against _(just to see if any other gremlins are now lurking)_.

Approved, sorry for the delay

**Comment by Paul-Licameli** [comment]
> > @vsverchinsky Hi Vitaly - I tested this on W10 with @Paul-Licameli 's fix in his branch: audacity-win-3.2.0-alpha-20220113+7129052-64bit
> > This seems to address the issues in this bug post - any chance you can do the review and pull this so that we can get a more workable 3.2.0 alpha to test against _(just to see if any other gremlins are now lurking)_.
> 
> Approved, sorry for the delay

Thank you.

Lesson learned:  Beware CallAfter, and use more weak pointers.

**Pull request merged**
