### PR TITLE
Rewrite expand cut line

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #5554

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by saintmatthieu** [comment]
I reckon you intend this to be merged in `wave-clip-refactoring` rather than `master` ?

**Comment by saintmatthieu** [comment]
... which would mean that only a42f52cbdff5caea65101b4ab49cdfb0bd8ac262 is to be reviewed, and which looks fine to me. I approve assuming that it's the case, please notify me if it wasn't.

**Review by saintmatthieu — APPROVED** [review]

**Comment by Paul-Licameli** [comment]
> I reckon you intend this to be merged in `wave-clip-refactoring` rather than `master` ?

Of course I did.  It's corrected.

**Comment by Paul-Licameli** [comment]
> ... which would mean that only [a42f52c](https://github.com/audacity/audacity/commit/a42f52cbdff5caea65101b4ab49cdfb0bd8ac262) is to be reviewed, and which looks fine to me. I approve assuming that it's the case, please notify me if it wasn't.

Yes, this PR is dependent on another and is meant to add only one commit.

**Comment by Paul-Licameli** [comment]
Rebased onto the updated dependency

**Review by saintmatthieu — APPROVED** [review]

**Pull request merged**
