### PR TITLE
Fix truncated decode of mp3 files on import

### PR DESCRIPTION
**Pull request by cannam**
The MAD decoder will not decode the final frame in an mp3 stream unless
it has a small amount of padding afterwards (MAD_BUFFER_GUARD bytes,
actually 8). Without this, it loses sync before returning any decoded
data from the final frame. The result is that the imported audio is
truncated by up to 1152 samples.

This commit addresses that by using a final round of input callback
calls to provide the last MAD_BUFFER_GUARD bytes after the underlying
file has reached eof. The logic is based on madplay.

### CODE REVIEW

**Comment by cannam** [comment]
You can find a test file at http://all-day-breakfast.com/m/ticks.mp3. It contains two short bursts of noise, one right at the start of the file and the other right at the end, separated by a couple of seconds of silence. If you open this in the Audacity master branch you will find that the second burst is missing; this commit fixes that.

The logic here is surprisingly fiddly, and would benefit from careful review.

(I chanced on this after finding the same problem in my own use of the MAD library in Sonic Visualiser. I suspect that hardly anyone is using this library completely correctly, since everyone copies the minimad example code and that has this problem as well. The official madplay application handles this case and that's what the fix is based on.)

**Comment by SteveDaulton** [comment]
Thanks for this Chris.

I can confirm that Audacity does have the problem that you  describe, and that your patch does allow Audacity to import the final frame, but it does not seem to be quite right yet. With your patched version I observe that the imported file is prepended with 1152 additional silent samples.

Audacity  has just gone into freeze in preparation for releasing 2.1.3, so this can't be merged right now. If you can sort out the residual problem (the extra samples at the start) then I'd be keen to see this reviewed and committed when the freeze is ended.

**Comment by cannam** [comment]
Thanks for taking a look.

The effect you describe was already the case, this patch didn't
introduce that problem. I'm just concentrating on one bug at a time.

I discuss both problems here:
https://thebreakfastpost.com/2016/11/26/mp3-decoding-with-the-mad-library-weve-all-been-doing-it-wrong/

This PR is only for the more serious of the two bugs. I may prepare a
patch for the other as well at some point, but I'm focusing on this one
first and I'm not going to incorporate both into a single PR.

**Comment by SteveDaulton** [comment]
Thanks for the additional detail. Yes I see what you're saying about the leading samples. I'll forward your link to the developer's mailing list and log both of these issues on our bug-tracker.
I'd be happy to assign these bugs to you if you'd care to join us on the developer's mailing list (https://lists.sourceforge.net/lists/listinfo/audacity-devel).
As I wrote previously, we're in freeze so we can't merge this right now, but please do come and say hello on-list (the GitHub comments are not heavily monitored - the primary communication channel for the Audacity developers is the mailing list).
Thanks again for your contribution (and by the way, I'm a big fan of Sonic Visualiser :-)

**Pull request merged**
