### PR TITLE
Several build failure fixes

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Please explain which "build failures" you are fixing with each of these commits.

Please explain more about how the wxFileNameWrapper kludge causes a crash.  I would like to keep that kludge for the compilers that let us get away with it.

**Comment by MaxKellermann** [comment]
Ok, I'll add error messages to the commit messages.

**Comment by MaxKellermann** [comment]
In any case, the wxFileNameWrapper kludge causes severe double free bugs. Valgrind is screaming loudly, and sometimes, even glibc notices heap corruption. I'll post details.

**Comment by Paul-Licameli** [comment]
According to the travis output linked herein, commit 7acc599cd7999020bec9d92f9a99cbc55429b863 is causing build failures.

**Comment by MaxKellermann** [comment]
Apparently, Travis builds with a very old FFmpeg version which doesn't have the `const` yet. Without that commit, build fails here (FFmpeg 3.0 and 2.8.6).

**Comment by Paul-Licameli** [comment]
I cherry-picked the fix for Track.cpp

**Comment by MaxKellermann** [comment]
So I'm using my system FFmpeg, because I hate projects which ship (outdated) copies of other libraries. The FFmpeg version in `lib-src/ffmpeg/` is 2.2.2 according to 14b47b46ab51f31f43f73017aac55e2789aaa96e. Would you agree to update those headers again? (I'd remove them completely, but that's just my opinion.)

**Comment by MaxKellermann** [comment]
I've added a valgrind log to the wxFileNameWrapper commit. Do you need to know anything else?

**Comment by Paul-Licameli** [comment]
I am not qualified to make the decision about FFmpeg.  I suggest you ask the question also at audacity-devel@lists.sourceforge.net

Can you figure out conditional compilation that could make the build work with either version?

**Comment by MaxKellermann** [comment]
Ok, wrapped in preprocessor version checks.

**Comment by Paul-Licameli** [comment]
Please see my commit https://github.com/audacity/audacity/commit/e09f62031156dbe792d98a161eaf7267095e94a5
which implements a different cheat for wxFileNameWrapper which might not crash you.

**Comment by MaxKellermann** [comment]
This will fall apart as well any day. I wouldn't do that. I understand your desire for move operations, but in this case I'd wait for WX to support it. Everything else is a kludge that's just waiting to crash (or corrupt data randomly).

**Comment by Paul-Licameli** [comment]
It's ugly either way, but humor me and see if it compiles and runs and lets you load and save a project without apparent trouble.

**Comment by MaxKellermann** [comment]
Compiles and doesn't crash, no valgrind warning.

**Comment by Paul-Licameli** [comment]
Good, I enabled the less evil swap function.  It should be safe so long as we do not change version of wxWidgets.

This discussion page is still telling me you did not satisfy the Travis build for FFmpeg functions.

**Comment by MaxKellermann** [comment]
That's because your FFmpeg version numbers are inconsistent!

In upstream FFmpeg, the `const` was added in commit https://github.com/FFmpeg/FFmpeg/commit/ec4f04da1 and `version.h` said:

    #define LIBAVFORMAT_VERSION_MAJOR 55
    #define LIBAVFORMAT_VERSION_MINOR 20
    #define LIBAVFORMAT_VERSION_MICRO  0

Now your `version.h` without the `const` says:

    #define LIBAVFORMAT_VERSION_MAJOR 55
    #define LIBAVFORMAT_VERSION_MINOR 33
    #define LIBAVFORMAT_VERSION_MICRO 100

.. which is the more recent version number set by commit https://github.com/FFmpeg/FFmpeg/commit/db3c9701f46d20fd7e94c3222cf4fd4524a16414 . The real problem is that FFmpeg applied those two changes in different branches, and your copy is a newer branch but without the `const` change.

So now I've changed the minimum version expected for `const` to 55.33.101, one more than Audacity's FFmpeg copy. I hope this covers all relevant versions.

**Comment by walisser** [comment]
What needs to be done to get the FFmpeg patch through?

**Comment by windinthew** [comment]
For a start, the commit has conflicts. 

And when that is solved, we have to be sure that the currently recommended FFmpeg 2.2.3 
maximum is still supported (so e.g. the recommended Windows/Mac FFmpeg downloads at http://manual.audacityteam.org/man/faq_installation_and_plug_ins.html#ffdown still work).

Or upgrade Audacity to support later FFmpeg/libav (what range of versions?)

Or migrate to gstreamer and use their FFmpeg support rather than hardcoding our own.  

The last two are major undertakings but I am not an expert in this. 

I doubt we will want to make any changes now before 2.1.3 release but I 
suggest taking Paul's recommendation to ask on the -devel list.

**Comment by walisser** [comment]
I was hoping to give Max a chance to do this, if he doesn't I will submit a new pull request and this one can be closed.

I cherry picked the FFmpeg commit only, and it doesn't break the current master branch. I don't know about Travis yet. I don't expect any change in behavior (or supported versions) as a result.

FWICT this patch is about fixing a build failure since the function prototypes changed in the new headers. But since they're only adding a const where there wasn't one, that won't break anything (const isn't part of the C calling conventions AFAIK). So functionally, nothing has changed, the same symbols are still loaded from the libraries. This can all be verified of course without much effort.

**Comment by MaxKellermann** [comment]
As of yet, I have no feedback whether my changes will be merged. I don't want to waste time on something that will go to the trash can. When I submitted this PR, there was no conflict - the Audacity project ignored my PR for so long, and **after** that merged changed which conflicted with this PR. Yes, I will do you the favor and resolve the conflicts - if you want me to.

About the `const`: the function pointers are not compatible if the constness of pointer targets is not the same. This has nothing to do with calling conventions - calling conventions describe how calls are made on the machine language level. Thus, calling conventions have little to do with the C language, they're a lower level, and semantic API declarations like constness do not matter on that level.

**Comment by Paul-Licameli** [comment]
As I said to Max before, I do not consider myself competent to decide which
version of the library should be used in our released binaries for Mac and
Windows.

However I reexamined commit 41de5b385b2ca721a71871fcdb00ec3fa4441b5b

and I saw that all changes are conditionally compiled, so that it leaves
our source code compatible with use of either version of the library.

Therefore I have cherry-picked and commited that.  Alone, it was
unconflicting.

The other commits are not relevant to upgrading the library version.
Updates of Makefile.in are periodically done by other people, and simply
commit the results of an automated tool, which doesn't demand real
programming effort.

And from discussions earlier with Max, I found other changes to
wxFileNameWrapper that do not give up the performance improvements I
intended, while also fixing the complaints from valgrind.

Therefore I do not intend to take those commits.

The changes to .gitignore give developers some convenience while not
affecting the build at all.  No development really depends on them.

Therefore I intend to close the commit request, having selected the one
most important part.

PRL

**Comment by Paul-Licameli** [comment]
... And the Travis build has succeeded.
PRL

**Pull request closed without merging**
