### PR TITLE
Issue 3899

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #3899
Resolves: #3855

Fix play after switching to a user preset in VST effects

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by pietro68** [comment]
I tried this with BlueCat Chorus and the two originally reported problems still persist. Maybe what happened is that you tested it using DeeGain, but I was wrong when I wrote that DeeGain is affected by this (I just corrected the original issue).

**Comment by Paul-Licameli** [comment]
> I tried this with BlueCat Chorus and the two originally reported problems still persist. Maybe what happened is that you tested it using DeeGain, but I was wrong when I wrote that DeeGain is affected by this (I just corrected the original issue).
> 
> I tried some debug printing in VSTEffectInstance::ProcessInitialize, printing the settings that come in (that is what gets called when pressing play). With both this branch and the release branch (on which this branch is based) what gets printed are the settings for what was in effect before the loading of the preset; and this both in the chunk and in the params map.
> 
> In other words, it looks as if the loading of a user preset is not remembered by the framework.

You did not specify which branch you tested when you reported the problem.

I think the problem with DeeGain is real at the previous commit 7616b89f9ea38f31a64631b36de3b727dd7d4248 and is fixed by this commit.

**Comment by pietro68** [comment]
> You did not specify which branch you tested when you reported the problem.

I was testing branch i-3877

> I think the problem with DeeGain is real at the previous commit [7616b89](https://github.com/audacity/audacity/commit/7616b89f9ea38f31a64631b36de3b727dd7d4248) and is fixed by this commit.

I confirm that the commit `Fix start of play of VST after loading preset...` fixed the problem reported in #3899, but for DeeGain only. The problem persists with BlueCat Chorus.

**Review by pietro68 — COMMENTED** [review]
Changes understood and fine with me. Please disregard my above comment about BlueCat Chorus, let's keep it out of the scope of this PR.

**Review by pietro68 — APPROVED** [review]

**Pull request merged**
