### PR TITLE
Update French translators credits + timestamp

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Do these individuals deserve a user-visible credit in the msgstr for translator_credits ?

**Comment by trebmuh** [comment]
@Paul-Licameli : I don't know. I know that Christian Brochec have been "the one" for a long time but I don't know about those 2 persons. I simply took their names from [your commit](https://github.com/audacity/audacity/commit/c55ad8552707b607b49a0af1e5b0090332fb753f) in order for them to be still credited somewhere.

**Comment by trebmuh** [comment]
and ... I realize that I forgot one...

 Added with the last commit which:
- modifies header's timestamp
- adds Lionel to the translators in the header
- remove a few legacy translation strings
- corrects a few typos/punctuations/better_translations/... in the legacy translation strings

**Comment by trebmuh** [comment]
and ... I realize that I forgot one...

The 2 last commits:
- adds Lionel to the translators in the header
- removes a few legacy translation strings
- corrects a few typos/punctuations/better_translations/... in the legacy translation strings
- updates header's timestamp

**Comment by trebmuh** [comment]
👍

**Pull request merged**
