### PR TITLE
Update French translation for 3.0.3

### PR DESCRIPTION
**Pull request by trebmuh**
- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Thanks, Olivier.

This makes fr.po 97% complete.  There are still 117 missing entries.

There is still some time in the window for submitting translations.  Can you make this more complete, before I merge it?

Thank you

PRL

**Comment by trebmuh** [comment]
@Paul-Licameli 

> This makes fr.po 97% complete. There are still 117 missing entries.

They aren't "missing" entries, they are entries which doesn't need to be translated.
Hence, it doesn't make sense for those to be copy/pasted, since if the English version would be to change, it would add myself some unneeded handwork. Leaving those as they are now is saving myself some unneeded work (hence time).

With this current PR, the French translation is 100% translated.

**Comment by Paul-Licameli** [comment]
Olivier, I figured out a few commands on the Unix command line that complete your translation, copying the English wherever you left a blank:

```
msgen audacity.pot > en.po
msgcat --use-first fr.po en.po > fr2.po
msgmerge fr2.po audacity.pot > fr.po
```
I pushed the results as another commit.  Please quickly review this.

I can see that mostly there are proper names and short strings.  But I think you had a doubt about "Pluck"?

**Comment by Paul-Licameli** [comment]
It helps us to do this extra work, so that we can automatically check the degree of completion of translation files, and not have false reports of incomplete translations.

**Comment by trebmuh** [comment]
Hi @Paul-Licameli .
It is wrong to do this from my perspective since it will add some more work on me on the future.
Let's take an example so you get my point:

    #: src/widgets/NumericTextCtrl.cpp
    msgid "centihertz"
    msgstr ""

There is no value added if I'm _translating_ (copying/pasting) `centihertz` for the same word in French. Hence I left it empty. Because of the way the translation system works, the French GUI will fall back to using the original original English string (ie: centihertz). All good, French user got the right word for the right meaning.

Now, if you choose to automate a copy/paste thing like you did:

    #: src/widgets/NumericTextCtrl.cpp
    msgid "centihertz"
    msgstr "centihertz"

it will work the same. No added value. Thinking ahead now. One day, the coding people want to change the string to "centi-hertz". The pot file changes. The French .po file is updated. And now, I've got to modify the translation while.

With the previous solution (leaving `msgstr "" ` empty), it would have automatically catch up with the new translation. With your solution, it requires me to do an extra work.

Please, revert your commit, it doesn't add any value for the translation, and it seems to be only needed for a helping tool to check the translation status. Leave that to the translator (me in this case here). I don't want my work to get more complicated only to cope with a helping tool. I can tell you that the translation is update to 100% or not. no need for a tool here.

Thanks for reading, hope you get my point.

**Comment by Paul-Licameli** [comment]
Have it your way, I will merge it into master without the other commit, if you object so strongly.

But I really don't understand your objections.  I don't understand why the work is so large, after I have explained how you can automate this work with a few commands.  I was just trying to help and make it easy.

These strings are very unlikely to change.  Fix them once, and you won't even have to look at the untranslated strings again in your favorite .po file editor.  It won't list them as incomplete for you to review, for the next Audacity version.  That could reduce your work too.

Proper names of mathematicians like "Bartlett" are not going to change in future versions.

(Why were strings like "Bartlett" added, anyway?  Because maybe it's proper to transliterate such a name into Katakana or Devanagari or Cyrillic.  It was wrong to assume that all languages would best leave the names in Latin.)

**Comment by Paul-Licameli** [comment]
It's done, at commit bd89510a35fcdea01d3a4c239ff49c2251858021, but it was not done with this GitHub interface.

Therefore I close this pull request.  Thank you for the translation.

**Pull request closed without merging**
