### PR TITLE
Fix writing to atomics in ShareAudioDialog.cpp

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by crsib — APPROVED** [review]

**Comment by Paul-Licameli** [comment]
Straight to merge?

What symptoms could have been fixed?

Maybe incorrect progress bar update during upload.

**Comment by crsib** [comment]
Straight to merge. I think nothing has changed, `memory_order_release` is not zero

**Comment by Paul-Licameli** [comment]
> Straight to merge. I think nothing has changed, `memory_order_release` is not zero

We don't know whether `memory_order_release` might be zero in some other standard library implementation, and besides one of these is `std::atomic<double>` in which some unchanging converted integer was always stored.

**Comment by Paul-Licameli** [comment]
The error would not have compiled if `std::memory_order` had been an enum class... oh well.

Use strong typing when you can to help the compiler help you!

**Comment by crsib** [comment]
I think it is in c++20

**Comment by Paul-Licameli** [comment]
> I think it is in c++20

Indeed

**Pull request merged**
