### PR TITLE
Break dependency cycle

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: 

The strongly connected component of six files:
   CommandFlag
   CommandManager
   Menus
   ToolBar
   ToolDock
   ToolManager

-- is broken up.  Two cycles of two still remain:
   ToolBar
   ToolDock

and
   CommandManager
   Menus

image

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by ksoze95 — APPROVED** [review]
Refactor looks good.

**Comment by Paul-Licameli** [comment]
Force push onto recent master required some conflict resolution but only in the #include lines.

**Comment by Paul-Licameli** [comment]
@dozzzzer @Ryan-Miller-Audacity just some sanity checking of behavior of menus and toolbars.

**Comment by Ryan-Miller-Audacity** [comment]
Verified sanity checking of menus/toolbars on Windows and MacOS via build: https://github.com/audacity/audacity/actions/runs/3885277388

**Pull request merged**
