### PR TITLE
Updates the RealtimeSupport for certain effects

### PR DESCRIPTION
**Pull request by crsib**
Resolves: #3416 

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
I approve these simple changes, but are they sufficient?  What happens if you
- Remove pluginregistry.cfg
- Start Audacity 3.1.3
- Exit
- Open Audacity 3.2. alpha

Does it still correctly exclude non-processing plug-ins from the sidebar?  If not, then users upgrading to 3.2 won't have the intended behavior.

**Comment by crsib** [comment]
Hmm, probably you are right and it should be `Since_3_2`. This will cause problems when downgrading, but we already have them.

**Review by vsverchinsky — APPROVED** [review]

**Comment by Paul-Licameli** [comment]
Can you give exmples of plug-ins that are not processors?

**Comment by Paul-Licameli** [comment]
Here's one: https://www.maat.digital/gon/ in VST and AU versions, but VST is off the table for 3.2, and our AU code actually doesn't correctly report whether effects are processors!  (More about that another time)

**Comment by crsib** [comment]
Plenty of generators, at least. 

https://soundsmag.com/top-generator-vst-plugins/

I have several LADSPA generators as well from the SWH

**Pull request merged**
