### PR TITLE
Generate an AppImage for each build

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will generate and upload an [AppImage](http://appimage.org/) of each commit. It does so by bundling Audacity and its core dependencies which cannot be expected to be part of each target system (Linux distribution) inside the AppImage.

The URL of the AppImage can be found in the Travis CI build log, it is beginning with `http://bintray...`. Of course you can change this to use the GitHub Releases mechanism for hosting the binaries instead.

### CODE REVIEW

**Comment by probonopd** [comment]
The resulting AppImage from df3c21d can be downloaded from
https://transfer.sh/Audacity-travis17-glibc2.15-x86_64.AppImage
as indicated in the Travis CI build log.

**Comment by probonopd** [comment]
Would appreciate review, feedback, discussion. Even if you end up deciding not to use it in the end :-)

**Comment by JamesCrook** [comment]
No one in team has volunteered to maintain this going forward, and it would be another deliverable we would need to create/test on each release.  Plus it pulls in binary code that we do not have full visibility of. 
 For now we are staying with our current methods for distributing on linux.

**Comment by probonopd** [comment]
@JamesCrook it pulls in binary code but only for the sake of speeding up the packaging process, and all is coming from traceable GitHub repository that contain the full source code.

Which "current methods for distributing on linux" are as easy for everyone as download one file, make it executable, and run?

**Comment by JamesCrook** [comment]
No one in team has volunteered to maintain this going forward, and it would be another deliverable we would need to create/test on each release. Plus it pulls in binary code that we do not have full visibility of.
For now we are staying with our current methods for distributing on linux.

**Comment by probonopd** [comment]
Isn't it a shame that if I was running a proprietary OS rather than Ubuntu LTS, I could be downloading and running Audacity 2.2.0 right now, whereas with Linux I am lost?

downloads

**Comment by probonopd** [comment]
Follow-up work has been done here: https://github.com/probonopd/audacity/blob/patch-1/.travis.yml

New build can be downloaded here: https://github.com/probonopd/audacity/releases

**Comment by TheAssassin** [comment]
I'd love to see binaries for Audacity for Linux as well. Big fan of this software, use it a few times the week. AppImage seems like the easiest way for you guys to provide those binaries. I mean, seriously, how many lines of code is the AppImage build compared to the NSIS(?) installer?

And whenever you would have trouble with the AppImage builds, you're free to join #AppImage on Freenode, there's a lot of people who can help you out.

**Comment by JamesCrook** [comment]
Simon, thanks for taking this to the devel list.  That is moving it along faster.  At least now the AppImage build is being reviewed by the people in Audacity who make sure things work well on Linux.  Thanks also for your flexibility in being willing to maintain and host this yourself.  We will never be testing on as many Linux variants as you do!

**Comment by Lvaskz** [comment]
Hi, will audacity release in appimage in the future? that will be awesome!!!!!

**Comment by JamesCrook** [comment]
+Lvaakz, probonopd is providing AppImages at https://github.com/probonopd/audacity/releases .  Audacity team already have our hands full providing and supporting Windows installer, Mac dmg and Linux-src for those three platforms, and as yet it does not make sense for us to officially provide AppImage, Snaps and Flatpak for linux ourselves.

**Comment by probonopd** [comment]
Still haven’t given up the hopes of an official AppImage... definitely happy to help :-)

**Comment by Lvaskz** [comment]
There are hundreds of them! Which of all to choose?

**Comment by Lvaskz** [comment]
I would like to see one official :-)

**Comment by probonopd** [comment]
> There are hundreds of them! Which of all to choose?

The most recent one that offers the combination of features you need. If people think there are build combinations that make no sense, let me know. Ideally the Audacity team would just decide on one.

**Comment by Lvaskz** [comment]
@JamesCrook you could include in the download page the links of audacity flatpak https://flathub.org/apps/details/org.audacityteam.Audacity of snap https://snapcraft.io/audacity and audacity appimage https: // github .com / probonopd / audacity / releases, indicating that they are not maintained by the audacity team, as does krita with the flatpak package?
Is there some problem with that? It would be easier for some users to see from the audacity page that there are such packages.

**Comment by Lvaskz** [comment]
Any way, you are not bundling such packages, only indicating a link,  if any body want them. :)

**Comment by JamesCrook** [comment]
Thanks @Lvaskz .  I've passed your comment on to the people who make decisions about Linux.

**Comment by Lvaskz** [comment]
Hi, any progress about it?

**Comment by probonopd** [comment]
Let me know if you want me to change anything.

**Comment by hcsubser** [comment]
any news on official audacity appimage, would really want to have one

**Comment by Lvaskz** [comment]
> 
> 
> any news on official audacity appimage, would really want to have one

I am hopeful that this will happen one day, personally speaking, the appimages are manageable and less irritating when executing them, the terminal is not needed, etc. Although for a linux user of several years, the terminal becomes indispensable. Anyway, appimages is a good option to download binaries and test them on linux.

**Comment by joe733** [comment]
Hi, it would be wonderful to see an official `Audacity.AppImage`. I use three opensource applications for video creation namely Audacity, Kdenlive and OBS Studio.

- Kdenlive already provides AppImages: https://kdenlive.org/en/download/
- OBS is in the process of adopting one: https://github.com/obsproject/obs-studio/pull/2868

I would love to see Audacity move in this direction. It would help a lot of content creators to get started with Audacity hassle free!

**Comment by JamesCrook** [comment]
Thanks @joe733 . I've passed your comment on to the people who make decisions about Linux.

**Comment by Lvaskz** [comment]
I think with this  (https://github.com/appimagecrafters/appimage-builder )appimage builder , create an appimage will be more easier.
To consider too

**Pull request closed without merging**
