### PR TITLE
tweak to default width of meter bar and project window

### PR DESCRIPTION
**Pull request by LWinterberg**
Resolves: #3627
part 1 of it anyway.

looks like this to me: 
image

### CODE REVIEW

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

I think you have made the slightly too large Leo - they now pop down in a third row in the top tooldock in your branch build.

image

**Comment by petersampsonaudacity** [comment]
Ahh, I note that you have also made the Audacity default window narrower (which I like).

a) on my PC with your branch build the window is 21.7 cm wide

b) on my PC with 3-2-0 Beta it is 3cm wider at 24.7 cm wide

So rather than reducing the new size of your meters maybe you just need to widen the default window by a small amount.

**Comment by LWinterberg** [comment]
oh, interesting: the default window widths are 1120 and 1060 (depending on whether the share audio button is present), but the actual width is 1106 for the audio sharing button version. I wonder where we lose the 14px

**Comment by petersampsonaudacity** [comment]
@LWinterberg  testing your latest branch - that's much better Leo - nice  :-))

image

**Comment by petersampsonaudacity** [comment]
I assume this is gonna make it into 3.2.0 ?

**Comment by petersampsonaudacity** [comment]
@LWinterberg @crsib @Tantacrul 

Will this get pulled into the 3.2.0 release - looks much better like this with Leo's changes?

**Review by crsib — APPROVED** [review]

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 2.3.0 build (today's)

Looking good now in the release build
image

**Pull request merged**
