### PR TITLE
Update Catalan translation

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by windinthew** [comment]
Thanks, but please read https://github.com/audacity/audacity/wiki:

> Translation changes must be submitted by subscribing to the [audacity-translation] (https://lists.sourceforge.net/lists/listinfo/audacity-translation) list, even if only changing one or two words.

**Comment by rbuj** [comment]
How often is updated https://sourceforge.net/p/audacity/mailman/audacity-translation/? I've sent an email one hour ago which is not shown.

**Comment by windinthew** [comment]
@rbuj  Thank you for subscribing to the -translation list. I don't know why the SourceForge archive of the list is oudated, but we have received your message to the list:
http://audacity.238276.n2.nabble.com/Update-Catalan-translation-for-Audacity-td7578860.html  so it will be dealt with in due course.

**Comment by rbuj** [comment]
Thanks for the clarification @windinthew and I apologize for the inconvenience.

**Pull request closed without merging**
