### PR TITLE
Fix Russian translation typos

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
In the latest version the About dialog does not look correct.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by Gootector** [comment]
You should change branch to 'release-3.4.2'.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@Gootector done

**Comment by Gootector** [comment]
@crsib See here.

**Review by crsib — APPROVED** [review]

**Comment by crsib** [comment]
Thank you, mate!

**Pull request merged**
