### PR TITLE
Issue-#4310 resolved by adding error message earlier so it fits in the dialog box

### PR DESCRIPTION
**Pull request by Ritikkhulbe**
… dialog box

Resolves: https://github.com/audacity/audacity/issues/4310)

*The Issue was that after entering some positive value in the text box to Normalize error (Maximum 0dB) was displayed after
the text Field but was not fit to the dialog box
Changes-
1. the Message (Maximum 0db) now appears as default message and fits to the dialog box
2. after entering a positive number in the text Box only the apply button doesn't allow and no new text appears on the dialog box*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Ritikkhulbe 's branch build: audacity-win-3.3.0-alpha-20230218+0ee4c00-x64

This looks better as the dialog is full-size from the get-go
image


But it is a little cramped on the right, would look better with a little space on the right of the closing bracket:
image

**Comment by Ritikkhulbe** [comment]
hey @petersampsonaudacity , i'll get it done right now

**Comment by Ritikkhulbe** [comment]
@petersampsonaudacity done, let me know if there's some more changes i could do

**Comment by petersampsonaudacity** [comment]
The build is waiting for a Muse "maintainer" to review and approve.  Until the build goes through I can't test.

And BTW I am not a decision-maker, I'm not a Muse bod, so the final yeah/nay will need to come from Muse anyway.

**Comment by petersampsonaudacity** [comment]
testing with @Ritikkhulbe 's latest branch build:  audacity-win-3.3.0-alpha-20230218+50ee0f0-x64

This now looks better to me (thanks for that) :
image


BTW I am not a decision-maker, I'm not a Muse bod, _I used to do QA on the old Audacity Team before Audacity bought the project a couple of years ago_, so the final yeah/nay will need to come from Muse anyway.

**Comment by LWinterberg** [comment]
FWIW: I'm not massively happy with this implementation (but then - I also am not massively happy with the implementation until now; error messages should be recognizable as such, not be a little bit of text in brackets)

**Comment by LWinterberg** [comment]
Hello! We just [switched master to 4.0.0](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which makes this PR incompatible and/or obsolete as we're switching UI framework and reorganizing large parts of the codebase.

**Pull request closed without merging**
