### PR TITLE
Add new colors for WaveColor

### PR DESCRIPTION
**Pull request by jonata**
This commit adds 20 colors to Wave Color selection.

### CODE REVIEW

**Comment by JamesCrook** [comment]
Thanks, but we're not going to go with this change.
When we add more colours, we won't be extending the menu.  We'll provide some different interface that is easier to use (and easier to customise).  We can discuss that on audacity-devel email list or on Discord.

**Comment by Nozalys** [comment]
Sorry to dig into an old ticket but what about this feature ? I was looking for exactly this feature (searched options, played with the .aup XML file to try, even looked if some plugins exists). Having only 4 colors makes the audio edition not very visual in a project with dozens tracks.
Does this feature still planned ?

**Comment by JamesCrook** [comment]
I'm not keen on the interface for this @Nozalys .  Four colours covers basic to mid level users.  For advanced users with large numbers of tracks we need to use colour more systematically, or the extra colour will start to get confusing rather than be helpful.  Also we would want to get coloured labels in at the same time, possibly coordinating label colours and clip colours in some way, to show a relation when there is one.  

Going to more colours - we need to think systematically about how colours are used.  

If you'd like to talk more about colour customisation, can I encourage you to start a conversation on audacity-devel email list where more people can join in?

**Comment by Nozalys** [comment]
Ok I see. I'll take a try with audacity-devel email list. Let's see.

**Pull request closed without merging**
