### PR TITLE
Issue#4504-CogwheelFix

### PR DESCRIPTION
**Pull request by aniruddhJo**
Above fix can be considered as workaround, Original fix needed is fix in audacity\libraries\lib-theme-resources\high-contrast\Components\UpButtonSmall.png

Resolves: #4504

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

classic
dark
highContrast
light

### CODE REVIEW

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @aniruddhJo 's branch build

@crsib this seems to fix the cosmetic issue with the cogwheel

image

**Comment by crsib** [comment]
@aniruddhJo please rebase you branch onto `release-3.3.0` and force push

**Comment by petersampsonaudacity** [comment]
@crsib Dmitry, this looks to be fixed in the latest master I have - so this can probably be closed.

image

**Comment by luzpaz** [comment]
Can this be rebased so testers can test ?

**Pull request closed without merging**
