### PR TITLE
Warning fixes

### PR DESCRIPTION
**Pull request by andheh**
Fixed a couple of easy-to-fix compiler warnings (GCC on Linux).

### CODE REVIEW

**Comment by JamesCrook** [comment]
Thanks.
We're keen to remove warnings.
Please don't include changes to lib-src in the revised pull request.  We try not to patch third party libs if we can help it.

**Comment by andheh** [comment]
Hi James!
Ok, sure.
What about files in lib-src/header-substitutes/, are these third-party files as well?

**Comment by JamesCrook** [comment]
Changes in header-substitutes are fine.

There will likely be a delay before we apply the patch as we are in code freeze prior to releasing 2.2.2.  Hopefully within 2 weeks.  Also I work on Windows, only occasionally Linux, so someone more familiar with linux, probably Steve, will be checking/approving this.

**Comment by andheh** [comment]
Sounds good. All changes in lib-src have been reverted.

I guess you should also check https://github.com/audacity/audacity/pull/255/commits/e044ef3f8088e6364ba6df7a36fc8c73cffcc185 on Windows.
I'm not sure if MSVC will complain about unused variables there...

**Comment by JamesCrook** [comment]
Windows does complain about the unused function parameters.  
Please use WXUNUSED() around the parameter instead.  

The 'compiler food' idiom arose from some case once upon a time, when a parameter was used in Mac, but not windows, so using WXUNUSED was 'too coarse'.

**Comment by andheh** [comment]
Could I also use a cast to void in the function body instead, or is WXUNUSED preferred in the audacity code?

Adding WXUNUSED to the unused parameters makes the function parameter list look very cluttered in my opinion.

**Comment by JamesCrook** [comment]
cast to void is fine.

The competing forces are that (a) we mostly use wxWidgets WXUNUSED() so for consistency one might and (b) we are moving over to avoiding wxisms like wxARRAY and similar more and more in our code.

So your preference to use cast to void is probably better, and it was just old habits that made me suggest WXUNUSED.

**Comment by andheh** [comment]
I created a revised version of this pull request. See pull request https://github.com/audacity/audacity/pull/260.

**Pull request closed without merging**
