### PR TITLE
This changes allow you to choose between different color scales.

### PR DESCRIPTION
**Pull request by LBoggino**

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Hello Luciano,

Unfortunately you have shared this code with us too late for inclusion in version 2.1.1, but I hope this can be considered for version 2.1.2.

However you did not resolve conflicts correctly between your work and mine.  You removed some changes necessary to my recent zero-padding project in files SpectrumPrefs.cpp and SpectrumPrefs.h.  This is evident in the diff view.

Please fix this and then share the updated project.

**Comment by LBoggino** [comment]
HI Paul,

Ok I'll get the last changes you made and send the pull request again.

Best Regards.

**Comment by Paul-Licameli** [comment]
I tried it and I like the interface so far.  I am also reviewing the code.  GitHub allows me to attach my remarks to your code, and I will leave some.

**Comment by JamesCrook** [comment]
This pull request has conflicts and does not have Paul's suggestions/improvements.
Closing the pull request, waiting for the new one.

**Pull request closed without merging**
