### PR TITLE
Spectrogram note pitch ruler

### PR DESCRIPTION
**Pull request by andheh**
A new ruler for the spectrogram display of an audio track showing note names instead of Hz.

Changes:
* Added the new ruler.
* Extended the spectrogram settings to switch between Hz and note display and to set the tuning of "a4" (default: 440Hz).
* Added a Clamp function.
* Removed an old, unused "CustomMode" of the Ruler class and added a function to add custom ticks
* Added generalized versions of FreqToMIDInote() and MIDInoteToFreq() which include the tuning frequency of "a4".

### CODE REVIEW

**Comment by andheh** [comment]
I noticed Travis fails to build the Clamp function I added.
The Clamp function is correct C++ code as far as I can tell (correct me if I'm wrong :) ).
I'll look into the problem, please have a look into the other changes nevertheless.

**Comment by vaughanjohnson** [comment]
Cool idea. I thought we had it already , but andheh, please proceed. --
Vaughan

**Comment by Paul-Licameli** [comment]
Please don't use constexpr.  We are not yet migrated to a version of the
MSVC compiler that supports it.

PRL

**Comment by andheh** [comment]
Thanks for the first feedback!
I fixed Clamp.h to not use constexpr.

When looking through the code I didn't see anything like this ruler.
There is #ifdef EXPERIMENTAL_FIND_NOTES in TrackArtist.cpp which tries to guess notes by quantizing frequencies as far as I can tell and is significantly more complex.
By the way, do you happen to know if anyone is still working on this?

Somehow the Travis build failed during the initial setup of the build environment, could someone restart the build, please?

**Comment by Pokechu22** [comment]
> There is #ifdef EXPERIMENTAL_FIND_NOTES in TrackArtist.cpp which tries to guess notes by quantizing frequencies as far as I can tell and is significantly more complex.
> By the way, do you happen to know if anyone is still working on this?

The [experimental features](http://wiki.audacityteam.org/wiki/Experimental_Features) page on the wiki says "Disabled. Status unclear."  I've played around with it in the past and from my memory, it works, but the setting pages are a bit awkward (probably didn't get updated with some of the other changes).  I don't think anyone's working on it anymore, and `git blame` says it was added in the first commit e74978ba7 to this repo; the [old SVN history](https://github.com/JamesCrook/audacity-from-svn-5GB) says (after some digging) it was added in 2007 in JamesCrook/audacity-from-svn-5GB@fb3dcff703.  I don't think much has happened with it since.

> Somehow the Travis build failed during the initial setup of the build environment, could someone restart the build, please?

I'm not able to do this myself (not sure if anyone else here can), but you can manually do it by amending and then force-pushing a commit (or, say, rebasing off of origin/master and then force-pushing; any push should trigger a rebuild)

**Comment by andheh** [comment]
Thanks! Amending and pushing with force did the trick -- ugly procedure though...

**Comment by matti-kariluoma** [comment]
I've fixed the conflicts in my fork at https://github.com/matti-kariluoma/audacity/tree/spectrogram_note_pitch_ruler

**Comment by LWinterberg** [comment]
Hello! We just [switched master to 4.0.0](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which makes this PR incompatible and/or obsolete as we're switching UI framework and reorganizing large parts of the codebase. 

Also, sorry for this comically large delay.

**Pull request closed without merging**
