### PR TITLE
Dont delete sample blocks prematurely

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Re-fixes an old problem more simply.

Also restores AutoCommitTransaction as I think it should be, consistent with these principles: https://doxy.audacityteam.org/exception-safety.html#Strong-guarantee-compound

MAY have relation to the disk exhaustion troubles -- I'm not certain of that yet.

But I believe this is also a right thing to do on its own merits.

### CODE REVIEW

**Comment by lllucius** [comment]
If you're really certain that the in memory objects will no longer reference the blocks created during the effect, then doing a rollback should be fine.

But, why not just leave the AutoCommitTransaction as-is and simply call trans.Rollback() in the cleanup finally block?  Seems a lot clearer to me.

Actually, maybe I should rename AutoCommitTransaction to something more like what it was intended to do.  Maybe, PerformanceWrapper or IOReducer or some such.

And we should probably get rid of using SAVEPOINTs.  Just makes things more complicated due to the nesting.  It's a remnant of some of the initial tinkering I was doing.

**Comment by Paul-Licameli** [comment]
> If you're really certain that the in memory objects will no longer reference the blocks created during the effect, then doing a rollback should be fine.
> 
> But, why not just leave the AutoCommitTransaction as-is and simply call trans.Rollback() in the cleanup finally block? Seems a lot clearer to me.

But the rollback was never done.   The code before my reversion commits by default and requires rollback to be explicit but didn't use it.   Commit of the savepoint was always done.  That's questionable.  Maybe that could leave orphan blocks committed in the SeqBlock table if there is an exception thrown in the scope of AutoCommitTransaction for any reason.

No, see the guideline document I cited about why I think this really is better this way.

The point of a destructor and RAII is to guarantee a cleanup no matter what might go wrong and cause early abnormal exit.  Better to setup for recovery from failure as the default, and require an explicit call to indicate success and cancel cleanup, which is only done at the point when success is certain.

If you do the reverse, requiring rollback to be explicit overriding the commit -- how can you be so sure you correctly cover all the paths of failure?  It's easier to cover just the path of success in stead, which, while most probable, is only one path, not many.

> 
> Actually, maybe I should rename AutoCommitTransaction to something more like what it was intended to do. Maybe, PerformanceWrapper or IOReducer or some such.
> 
> And we should probably get rid of using SAVEPOINTs. Just makes things more complicated due to the nesting. It's a remnant of some of the initial tinkering I was doing.

Do you mean you would reimplement the class to use BEGIN, COMMIT, and ROLLBACK commands instead?

**Comment by lllucius** [comment]
> 
> 
> > If you're really certain that the in memory objects will no longer reference the blocks created during the effect, then doing a rollback should be fine.
> > But, why not just leave the AutoCommitTransaction as-is and simply call trans.Rollback() in the cleanup finally block? Seems a lot clearer to me.
> 
> But the rollback was never done.

That's because rollbacks were NEVER intended to be done.  This was strictly supposed to be used for performance not database management.  (I could kick myself for putting that method in there in the first place.)

If you want to change it to be more than that, then rename it because it won't be Auto"Commit"Transaction anymore.

> > And we should probably get rid of using SAVEPOINTs. Just makes things more complicated due to the nesting. It's a remnant of some of the initial tinkering I was doing.
> 
> Do you mean you would reimplement the class to use BEGIN, COMMIT, and ROLLBACK commands instead?

Yes.

**Comment by Paul-Licameli** [comment]
> > > If you're really certain that the in memory objects will no longer reference the blocks created during the effect, then doing a rollback should be fine.
> > > But, why not just leave the AutoCommitTransaction as-is and simply call trans.Rollback() in the cleanup finally block? Seems a lot clearer to me.
> > 
> > 
> > But the rollback was never done.
> 
> That's because rollbacks were NEVER intended to be done. This was strictly supposed to be used for performance not database management. (I could kick myself for putting that method in there in the first place.)

But should not rollbacks be done as error recovery, if there is any exception propagating out, for whatever other reason (maybe other than exceptions related to the database), to make sure things are left in a clean state? 

We need to consider the exceptional flows of control too, which might quit anywhere in the middle of the scope of AutoCommitTransaction, and not just the usual success path.

I was led to this while debugging the problems Steve reported with exhaustion of the thumb drive.

It got to the point that these AutoCommitTransaction blocks were being entered, and applying effects was failing, and yet commits of savepoints were also being attempted in these destructors.  And these database operations were failing, but there was no other way to propagate the error out.  And I don't understand what compounded corruption to the database might be happening.

Another reason I think it's far better to set up for rollback in the destructor by default, in case anything else wants to blow up for whatever reason.

> 
> If you want to change it to be more than that, then rename it because it won't be Auto"Commit"Transaction anymore.

Indeed, the name might be reconsidered, if it's really the rollback that is "auto" unless you tell it otherwise.  Say, "TransactionScope".

> 
> > > And we should probably get rid of using SAVEPOINTs. Just makes things more complicated due to the nesting. It's a remnant of some of the initial tinkering I was doing.
> > 
> > 
> > Do you mean you would reimplement the class to use BEGIN, COMMIT, and ROLLBACK commands instead?
> 
> Yes.

**Comment by Paul-Licameli** [comment]
> > > > If you're really certain that the in memory objects will no longer reference the blocks created during the effect, then doing a rollback should be fine.
> > > > But, why not just leave the AutoCommitTransaction as-is and simply call trans.Rollback() in the cleanup finally block? Seems a lot clearer to me.
> > > 
> > > 
> > > But the rollback was never done.
> > 
> > 
> > That's because rollbacks were NEVER intended to be done. This was strictly supposed to be used for performance not database management. (I could kick myself for putting that method in there in the first place.)

Are you suggesting it may be best simply to remove that class and its uses, because it has not demonstrated its value with performance improvements?

If you decide that then I will close this request.

> 
> But should not rollbacks be done as error recovery, if there is any exception propagating out, for whatever other reason (maybe other than exceptions related to the database), to make sure things are left in a clean state?
> 
> We need to consider the exceptional flows of control too, which might quit anywhere in the middle of the scope of AutoCommitTransaction, and not just the usual success path.
> 
> I was led to this while debugging the problems Steve reported with exhaustion of the thumb drive.
> 
> It got to the point that these AutoCommitTransaction blocks were being entered, and applying effects was failing, and yet commits of savepoints were also being attempted in these destructors. And these database operations were failing, but there was no other way to propagate the error out. And I don't understand what compounded corruption to the database might be happening.
> 
> Another reason I think it's far better to set up for rollback in the destructor by default, in case anything else wants to blow up for whatever reason.
> 
> > If you want to change it to be more than that, then rename it because it won't be Auto"Commit"Transaction anymore.
> 
> Indeed, the name might be reconsidered, if it's really the rollback that is "auto" unless you tell it otherwise. Say, "TransactionScope".
> 
> > > > And we should probably get rid of using SAVEPOINTs. Just makes things more complicated due to the nesting. It's a remnant of some of the initial tinkering I was doing.
> > > 
> > > 
> > > Do you mean you would reimplement the class to use BEGIN, COMMIT, and ROLLBACK commands instead?
> > 
> > 
> > Yes.

**Comment by Paul-Licameli** [comment]
Let me restate the problem very briefly:

Committing automatically in the destructor may seem convenient, but then it will happen not only with normal flow control, but also when doing exceptional stack unwinding.

It is doubtful that this is right.

I saw it happening while debugging drive exhaustion.

So I propose this slightly less convenient class which may be more correct in the unusual cases too.

**Comment by lllucius** [comment]
> > > That's because rollbacks were NEVER intended to be done. This was strictly supposed to be used for performance not database management. (I could kick myself for putting that method in there in the first place.)
> 
> Are you suggesting it may be best simply to remove that class and its uses, because it has not demonstrated its value with performance improvements?
> 

Oh, no, it is absolutely required for performance purposes.

**Comment by Paul-Licameli** [comment]
I have renamed the class to TransactionScope.

I'm not sure you sound convinced yet.  It is true haven't yet demonstrated a bug that is fixed with this rewrite.  I would still prefer this style on principle.

**Comment by Paul-Licameli** [comment]
Thanks for merging!

**Pull request merged**
