### PR TITLE
[NYQUIST] fix nyq_reformat_aud_do_response() not found. 

### PR DESCRIPTION
**Pull request by carlo-bramini**
Resolves: [*(direct link to the issue)*](https://github.com/audacity/audacity/issues/3137)

If NYQUIST is disabled when configuring Audacity, the build process hangs with an error because `nyq_reformat_aud_do_response()` is not found when linking, see issue #3137. Since `ExecForLisp()` is called only by `src\effects\nyquist\Nyquist.cpp` but this source is not compiled if Nyquist is disabled:

https://github.com/audacity/audacity/blob/ea8163f94e58899844a173c679f5a267b4252d1c/src/CMakeLists.txt#L637

it is worth to apply here the same test on `USE_NYQUIST` macro, as it has been already done elsewhere.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by crsib — APPROVED** [review]

**Review by Paul-Licameli — CHANGES_REQUESTED** [review]
Please cherry pick the last commit onto recent master and force push this branch with only that commit.  There are 14 extraneous merge commits before it.

**Comment by crsib** [comment]
We can just squash it on merge

**Comment by carlo-bramini** [comment]
> We can just squash it on merge

I would really appreciate that... for doing this quick fix, I used GitHub web editor and those extraneous commits are made by the "Sync fork" button on the web interface.

**Comment by crsib** [comment]
I'll do that, no worries

**Comment by crsib** [comment]
Given that this change is not visible to out QA team, I'll go ahead and merge it

**Pull request merged**
