### PR TITLE
Adds access key to the presets & settings button

### PR DESCRIPTION
**Pull request by LWinterberg**
(previously "manage"). Moves existing access keys on s to new places. Also resolves a conflict on p in the process.

Resolves: #3489

### CODE REVIEW

**Review by crsib — COMMENTED** [review]
I can see lot's of changes to the old strings. Is there a reason to use `s` for `Presets & Settings`?

Please keep in mind that any change to XO/XXO string means that it needs to be retranslated, potentially it will cause translations to be missing for not-so-actively updated languages

**Comment by LWinterberg** [comment]
the previous access key was m, which no longer appears in the new strings (unless we do it like the japanese localization and do `"Presets && settings (&M)`), so a new letter needed to be chosen. P is taken by preview, and all other letters have collisions with access keys inside the effects. Technically, `I` has the fewest collisions, but access keys are to be remembered after all, so I chose the start of the second word - "alt+s for settings".

It is possible to allow the collision anyway, ie to put the access key on s while keeping the other strings on s, too. If this is chosen, it would work as thus: 

1. open "change pitch"
2. press alt+s
3. the focus jumps to the semitone controls
4. press alt+s again
5. presets and settings open
6. close menu
7. press alt+s again
8. presets and settings open

Generally, in case of collision, if there is a matching access key inside the form (ie the effect settings) after the current focus, the access key jumps to it. If the focus is on or after the last instance of a matching access key, it presses the button instead, but the  buttons generally give back the focus to where it was previously. Note that you don't really get trapped here, as tab navigation (or using other access keys) gets you to where you want to be anyway.

(Aside: Import/export remove the focus altogether, making keyboard navigation impossible afaict. I'll make a separate bug on that later)

----

Any of these options are easy enough to implement/change the implementation to it. 

* Keep the existing access key and rename the Presets and settings button to "Presets & Settings (M)"
* Use S as the access key and resolve collisions (this PR)
* Use I as the access key and resolve collisions (this would require 4 additional string changes, compared to 15 here)
* Use [S,I, or any of the other letters found in presets & settings] as the access key but allow the collisions (this would be just a single string change, inside the button itself)

After this investigation I think I prefer the latter option, S as the access key while allowing collisions. What do you think? @crsib @DavidBailes @Tantacrul

**Comment by DavidBailes** [comment]
On Tue, 6 Sept 2022 at 10:05, Dmitry Vedenko ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> I can see lot's of changes to the old strings. Is there a reason to use s
> for Presets & Settings?
>
> Please keep in mind that any change to XO/XXO string means that it needs
> to be retranslated, potentially it will cause translations to be missing
> for not-so-actively updated languages
>
Why can't two strings which differ only in the position of an & be treated
as being the same for the purposes of whether a new translation is needed?

**Comment by DavidBailes** [comment]
On Tue, 6 Sept 2022 at 11:26, LWinterberg ***@***.***> wrote:

> the previous access key was m, which no longer appears in the new strings
> (unless we do it like the japanese localization and do "Presets &&
> settings (&M)), so a new letter needed to be chosen. P is taken by
> preview, and all other letters have collisions with access keys inside the
> effects. Technically, I has the fewest collisions, but access keys are to
> be remembered after all, so I chose the start of the second word - "alt+s
> for settings".
>
> It is possible to allow the collision anyway, ie to put the access key on
> s while keeping the other strings on s, too. If this is chosen, it would
> work as thus:
>
>    1. open "change pitch"
>    2. press alt+s
>    3. the focus jumps to the semitone controls
>    4. press alt+s again
>    5. presets and settings open
>    6. close menu
>    7. press alt+s again
>    8. presets and settings open
>
> Generally, in case of collision, if there is a matching access key inside
> the form (ie the effect settings) after the current focus, the access key
> jumps to it. If the focus is on or after the last instance of a matching
> access key, it presses the button instead, but the buttons generally give
> back the focus to where it was previously. Note that you don't really get
> trapped here, as tab navigation (or using other access keys) gets you to
> where you want to be anyway.
>
> (Aside: Import/export remove the focus altogether, making keyboard
> navigation impossible afaict. I'll make a separate bug on that later)
> ------------------------------
>
> Any of these options are easy enough to implement/change the
> implementation to it.
>
>    - Keep the existing access key and rename the Presets and settings
>    button to "Presets & Settings (M)"
>    - Use S as the access key and resolve collisions (this PR)
>    - Use I as the access key and resolve collisions (this would require 4
>    additional string changes, compared to 15 here)
>    - Use [S,I, or any of the other letters found in presets & settings]
>    as the access key but allow the collisions (this would be just a single
>    string change, inside the button itself)
>
> After this investigation I think I prefer the latter option, S as the
> access key while allowing collisions. What do you think? @crsib
> <https://github.com/crsib> @DavidBailes <https://github.com/DavidBailes>
> @Tantacrul <https://github.com/Tantacrul>
>
Allowing collisions is my least favourite option - it significantly
degrades the usability of access keys when you have to press the relevant
keystroke a different number of times depending on the position of the
focus.

As for the other options, I'd prefer to be certain of whether new
translations are required when the access key is changed before choosing.

**Comment by crsib** [comment]
> I'd prefer to be certain of whether new translations are required when the access key is changed before choosing.

I am quite certain that new translations will be required. @Paul-Licameli can you confirm it please?

**Comment by DavidBailes** [comment]
On Tue, 6 Sept 2022 at 13:53, Dmitry Vedenko ***@***.***>
wrote:

> I'd prefer to be certain of whether new translations are required when the
> access key is changed before choosing.
>
> I am quite certain that new translations will be required. @Paul-Licameli
> <https://github.com/Paul-Licameli> can you confirm it please?
>

But I don't understand why!

**Comment by crsib** [comment]
And even if it does - the translations likely need to change the accelerator key as well. 

On top of that, I think that gettext ignoring & in keys will break complex interfaces, so I don't think that they've considered such functionality.

**Comment by DavidBailes** [comment]
On Tue, 6 Sept 2022 at 15:08, Dmitry Vedenko ***@***.***>
wrote:

> But I don't understand why!
>
> & is a part of msgid, which is essentially a key into the translation.
> Changing the location of & changes the key.
>
> A real world example of our translation file:
>
> #: src/prefs/KeyConfigPrefs.cpp
> msgid "&Tree"
> msgstr "&Arborescence"
>
> I do not see enough evidence yet that gettext can handle that only & has
> changed
>
thanks for the explanation, I hadn't realized that this was handled by
third party code, I thought that it might be something that could be
tweaked by us.

**Comment by DavidBailes** [comment]
On Tue, 6 Sept 2022 at 15:12, Dmitry Vedenko ***@***.***>
wrote:

> And even if it does - the translations likely need to change the
> accelerator key as well.
>
but not necessarily for the label for that particular control. If the
"Manage" button is changed to a "Presets & settings" button, then in a
translation, depending on the translations of "Manage" and "Presets &
settings", the access key for that button may or may not have to be
changed. If it's a new access key, then whether it creates a duplicate
depends on the access keys assigned to the translated strings of the other
controls in the dialog. So the correction of duplicates in the translation
doesn't, in general,  involve having to change the access keys in the names
of the same controls that have to be changed in the original english.

For the "not-so-actively updated languages", then if "Manage" is changed to
"Presets & settings", then, as I understand it, the name of this important
control which appears in all effect dialogs may go untranslated, so there's
a problem regardless of the translation problem which you have raised. So
the translation is going to have to be updated anyway, if it's going to
remain usable.

On top of that, I think that gettext ignoring & in keys will break complex

**Comment by Tantacrul** [comment]
Hmm. This is a bit of a pickle with not much time at our disposal (and not much time for translations) - but loads of time after we get the release out. 

Since the Presets and Settings button can already be accessed, we should hold off setting an access key now, which will simplify things to allow us to focus on our remaining audio issues.

I think we bump this to 3.2.x

**Comment by DavidBailes** [comment]
On Wed, 7 Sept 2022 at 10:51, Tantacrul ***@***.***> wrote:

> Hmm. This is a bit of a pickle with not much time at our disposal (and not
> much time for translations) - but loads of time after we get the release
> out.
>
> Since the Presets and Settings button can already be accessed, we should
> hold off setting an access key now, which will simplify things to allow us
> to focus on our remaining audio issues.
>
> I think we bump this to 3.2.x
>
An alternative would be to keep the name of the button as "Manage" until
3.2.x.  Then, no translations of "Presets and Settings" are needed until
3.2.x

**Comment by Tantacrul** [comment]
Yeah. That makes sense. I'm reticent since the general UX benefit of calling it 'Presets and Settings' is high, since it is much more descriptive and quite important for real-time FX.

I feel it slightly outweighs the access key issue. Only because there is already a way to access the button.

**Comment by Paul-Licameli** [comment]
> > But I don't understand why!
> 
> `&` is a part of `msgid`, which is essentially a key into the translation. Changing the location of `&` changes the key.
> 
> A real world example of our translation file:
> 
> ```
> #: src/prefs/KeyConfigPrefs.cpp
> msgid "&Tree"
> msgstr "&Arborescence"
> ```
> 
> I do not see enough evidence yet that gettext can handle that only `&` location has changed

What @crsib says about get text is correct

But the translation update can help the translator at least by detecting near-matching msgIds, keeping the old translations in comments, and suggesting them for the new strings.

**Pull request closed without merging**
