### PR TITLE
OpenMP TrackArtist::DrawSpectrum

### PR DESCRIPTION
**Pull request by walisser**
Much faster drawing function, measured about 300% improvement. Not much to this, there is some minor refactoring to allow loop parallelization.

Additional refactoring to calculate number scale one time, could give a boost to the non-omp version esp when scale involves log(), etc.

Also changed pointless references like "const double& x = y" to "const double x = y", I don't see the point of having a reference to a primitive type, or basic struct like wxRect. This may allow better code generation inside loops.

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
I will review this.

I am not sure that the references were harming the compiled code.  To the contrary a reference is a way of saying "don't copy."  The real question is whether a declaration is causing a register allocation or stack growth unnecessarily.  That may depend on how smart the optimizer is.

**Comment by Paul-Licameli** [comment]
My incomplete review so far:

I will not merge this as it is now.

Please don't remove the references unnecessarily without any proof that they help performance.  Keep the commit simple.

I am surprised that line 2187 compiles, but it does for my on Mac.  But standard C++ should not allow the array dimension to be a non-constant expression.  This may not be portable.  This might break the Windows build, but I am not in a place where I can check that now.

Use alloca instead.  Though not standard either, there is precedent for that elsewhere in our code.

**Comment by Paul-Licameli** [comment]
Sorry, but the changes you made involving variables w0 and w1 can't go in.

You assumed reasonably enough that every pixel column covers an equal interval of time.  What you don't know is that I intentially wrote more general code that does not assume this, because I was developing a project tentatively called "fisheye" which can make the mapping non-uniform.  This project may be completed in version 2.1.4.

**Comment by Paul-Licameli** [comment]
That completes my review.
PRL

**Comment by Paul-Licameli** [comment]
On reflection, I find a bit more to say.

The changes to w0 and w1 might be objectionable anyway because of numerical roundoff when computing timeStep.  This might make more difference when in zoomed very closely and making a (time) selection.

I understand that you need to break a loop carried dependency.  I think there is no avoiding two calls to PositionToTime in each pass of the loop, in the parallel version, for the future fisheye to work.  The serial version can avoid the second call.

**Comment by JamesCrook** [comment]
I'm closing this rather than have incremental additional changes since Paul is not OK with it.  Paul needs to add comments into the existing code to explain not lifting calculation outside the loop for w0 and w1.  I tend to side with Darrell over the '&' being unnecessary and unclear and favour removing them.  It's a well known idiom to pass small values by value and large values by pointer/reference, and I think it is correct to continue it here, as Darrell does, when essentially using const variables just for renaming.

**Comment by Paul-Licameli** [comment]
Surely though we will welcome another commit that answers my objections.

**Comment by JamesCrook** [comment]
Yes indeed.  But as a new pull request.

**Pull request closed without merging**
