### PR TITLE
Restore stateful effects

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #2781
Resolves: #3520

If a dialog for a stateful effect is cancelled, then when next opened, restore the settings' initial not final state as in last dialog.
Remove some redundant code for persistency of Equalization curves
Fix error specific to Amplification from commit 4dcc5ee

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by crsib — APPROVED** [review]

**Review by pietro68 — APPROVED** [review]
code changes understood and tested

**Comment by crsib** [comment]
Is the branch right though @Paul-Licameli ?

**Comment by Paul-Licameli** [comment]
> Is the branch right though @Paul-Licameli ?

Oops, I based on master, and merged this plus all other recent alpha stuff to master.  No harm from that, and I also merged these changes to alpha.

**Comment by Paul-Licameli** [comment]
@dozzzzer @Ryan-Miller-Audacity Pay special attention to the checkbox in Amplify and the curves in equalization.

**Pull request merged**
