### PR TITLE
Snap manager

### PR DESCRIPTION
**Pull request by Paul-Licameli**
A preliminary for improvements in Time Shift (which will eliminate track type switches in it) is first to eliminate type switches in Snap.cpp.

### CODE REVIEW

**Review by JamesCrook — COMMENTED** [review]
I like the dependence in Snap being on Track rather than multiple other classes.

The use of const to distinguish  Intervals with IntervalData and without looks 'tricksy' to me.  
> I get (or think I do) that IntervalData (aka TrackIntervalData) is arbitrary attached data, but am not getting why you're not using different named functions for with-data and without-data, which seems to be the real distinction.  

The const/non-const distinction is also confusing, because I'd expect to be able to modify actual start and end with the non-const version, and have that modify the underlying objects, and that's not the case.  Would separate names for the two versions that indicates one has data and one doesn't be clearer?  

If we're expecting to 'do operation' on the attached IntervalData, such as actually modify start and end, or to query the data to find out whether there is quantization on start and end and whether there is a constraint, such as 'length must be preserved', is the intention that one would add virtual functions to IntervalData to achieve that?

I understand, now, why SnapManager needed changing too, since it (of courses) cares about clips and indeed other things one might snap to.  
> I am interested in whether the eventual method for filtering Tracks and Intervals to snap to will be adequate or fragile.  I can see cases where we do not want to snap to all possible labels, but only to labels in tracks in the same track (sync lock) group, or where we don't want to snap to notes in other NoteTracks, because there are so many, but do want to snap to notes in the current track.  It is not 'to solve now', but I do wonder if the more agnostic method is storing up problems.  When the code later adapts to not have a switch on type, I'd like a brief comment in the code about (one proposed way for) extending filtering at Track and Interval level.

**Comment by Paul-Licameli** [comment]
> I like the dependence in Snap being on Track rather than multiple other classes.
> 
> The use of const to distinguish Intervals with IntervalData and without looks 'tricksy' to me.
> 

Think of STL containers with overloaded const and non-const begin() and end(), returning different types of iterators, that don't or do allow mutation of the container.  An analogy is intended.

> > I get (or think I do) that IntervalData (aka TrackIntervalData) is arbitrary attached data, but am not getting why you're not using different named functions for with-data and without-data, which seems to be the real distinction.

The important distinction is not with or without data, but rather allowing or not allowing mutation.  Overloading by constness of this is idiomatic.

> 
> The const/non-const distinction is also confusing, because I'd expect to be able to modify actual start and end with the non-const version, and have that modify the underlying objects, and that's not the case. Would separate names for the two versions that indicates one has data and one doesn't be clearer?


> 
> If we're expecting to 'do operation' on the attached IntervalData, such as actually modify start and end, or to query the data to find out whether there is quantization on start and end and whether there is a constraint, such as 'length must be preserved', is the intention that one would add virtual functions to IntervalData to achieve that?

No, the IntervalData is a cookie to be passed back to the appropriate Track or TrackShifter class (next pull request) to interpret.  It only offers a readout of start and end, not modification.  Which is enough for SnapManager. 

> 
> I understand, now, why SnapManager needed changing too, since it (of courses) cares about clips and indeed other things one might snap to.
> 
> > I am interested in whether the eventual method for filtering Tracks and Intervals to snap to will be adequate or fragile.

There is a constructor of SnapManager that collects all intervals from the TrackList in a default way.  But it can also be given a predefined list of points built in a nondefault way.  Which is what TimeShift needs to do, to exclude the moving parts of the tracks from the list of snap candidates.  I did not like the special purpose constructor that existed and rewrote it.

**Comment by Paul-Licameli** [comment]
Allow me a redraft.

**Comment by JamesCrook** [comment]
Of course you're 'allowed a redraft'.  I'm taking it to mean; 'I'm redrafting to address some points'.

**Comment by Paul-Licameli** [comment]
I have reworked this.

As I said, I follow the convention of stl container methods like "begin" which have const and non-const overloads, returning results of different kinds, allowing non-mutative or mutative access to the special extra data in the interval.

You must static_cast or dynamic_cast the extra to the expected type, but those casts can't throw away const.

So long as you don't use const_cast (which is always a questionable thing) or C-style pointer casts (bad C++ style), you won't subvert the system.

**Comment by JamesCrook** [comment]
These look like improvements on the previous version; including NoteTrack in the changes and making the exclusions a passed in parameter.

**Comment by Paul-Licameli** [comment]
What do you mean about NoteTrack?  I thought I had changes for it too in the previous version.  It is necessary to preserve behavior.

**Comment by JamesCrook** [comment]
Then perhaps I had not picked up on it last time.  I noticed it this time, and thought it was one of the new changes.

**Comment by Paul-Licameli** [comment]
Rebased onto more recent master, no changes

**Pull request closed without merging**
