### PR TITLE
Add a delete button to the Cut/Copy/Paste toolbar

### PR DESCRIPTION
**Pull request by abhi-kr-2100**
Signed-off-by: Abhishek Kumar <abhi.kr.2100@gmail.com>

Resolves: #4131 

Add a delete button to the Cut/Copy/Paste toolbar

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by abhi-kr-2100** [comment]
While .png icons for cut, copy and paste exist inside [libraries/lib-theme-resources/classic/Components](https://github.com/audacity/audacity/tree/master/libraries/lib-theme-resources/classic/Components), `Delete.png` and `DeleteDisabled.png` need to be added.

**Comment by LWinterberg** [comment]
The source for these icons can be found at https://github.com/musescore/MuseScore/blob/master/fonts/mscore/MusescoreIcon.ttf,  is the glyph in question (it's inside a private use area and won't render outside the musescore icon font)

you'll need to color them manually in an image editor though. Be aware that the four themes (classic, light, dark, high contrast) each need their own versions.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @abhi-kr-2100 's   branch build:  audacity-win-3.3.0-alpha-20230101+c23548e-x64-msvc2022

This looks good to me in this branch build:
a) The Delete button does indeed delete the selection - and properly does _**not**_ replace the clipboard contents
b) the Cut button deletes the selection - and properly **_does_** replace the clipboard contents
c) the Delete button icon is as @DilsonsPickles specified in the Figma spec

**Comment by Tantacrul** [comment]
I have one suggestion. When there is no audio selected, the delete button should be disabled.
image

There is no reason why we should need to show this message:
image

I'm aware that when you use a shortcut to delete, you see the above message. At some other point, we'll remove the message in this instance too.

**Comment by Tantacrul** [comment]
One other little comment, although I'm not sure if it is relevant to this PR or not.

When I first opened this, the **cut, copy, paste** toolbar was moved to a second row under the main toolbar. Resetting my configuration fixed this. I only mention it to make sure we don't accidentally revert our changes that make the **cut, copy, paste** toolbar hidden by default, and when one does enable it, that it appears in the right place.

Thanks @abhi-kr-2100 !

**Comment by petersampsonaudacity** [comment]
> I have one suggestion. When there is no audio selected, the delete button should be disabled.

@Tantacrul   Same then should also be true for Cut and Copy when there is nothing selected - and for Copy when there is nothing on the clipboard.

1. clear Audacity settings folder
2. launch the branch build
3. enable the Cut/Copy/Paste toolbar
4. Observe: the Paste button is bold/enabled - but there is nothing on the clipboard
5. import some audio
6. Observe: now the Cut, Copy and Delete buttons are bold/enabled too - though nothing is selected

BTW this erroneous button behavior is a regression introduced somewhere between 2.0.0 and 2.4.2 _(I don't have time to bisect right now, sorry - will do so later)._

**Comment by crsib** [comment]
Enabled "Paste" is an older bug of Audacity. It was not fixed.

**Comment by petersampsonaudacity** [comment]
> When I first opened this, the **cut, copy, paste** toolbar was moved to a second row under the main toolbar.

I don't see that

1) when I pseudo-upgrade from 3.2.2 to this branch and then enable Cut/Copy/Paste I see:
image


2) If I pseudo virgin install this branch and then enable Cut/Copy/Paste I see:
image

**Comment by petersampsonaudacity** [comment]
> Enabled "Paste" is an older bug of Audacity. It was not fixed.

@crsib Is it a logged bug Dmitry?

**Comment by crsib** [comment]
I have no idea. But the toolbar buttons reflect the state of the "Edit" menu.

**Comment by Tantacrul** [comment]
> Enabled "Paste" is an older bug of Audacity. It was not fixed.

@petersampsonaudacity - is it a bug? I saw you mention it a week or so ago and I forgot to respond. The problem you identified, IIRC, was that if you copied text on your clipboard somewhere else, then the Paste button is active.

I'm wondering if that is wrong, bearing in mind you could paste that into a label?

**Comment by petersampsonaudacity** [comment]
> > Enabled "Paste" is an older bug of Audacity. It was not fixed.
> 
> @petersampsonaudacity - is it a bug? I saw you mention it a week or so ago and I forgot to respond. The problem you identified, IIRC, was that if you copied text on your clipboard somewhere else, then the Paste button is active.

I no longer think this is entirely true

1) If I reboot my PC (so there is no data on my Windows clipboard) and then launch Audacity i observe that the Paste button is active/enabled even though there is no data to post.

2) The other thing to bear in mind is that there are two clipboards
a) the Windows clipboard that normally contains alphanumeric text
b) the Audacity clipboard that contains chunks of audio track or chunks of label track

The Paste command and button is a little odd in that it can:
i) Paste chunks of audio track  from the Audacity clipboard into audio tracks
ii) Paste chunks of label track  from the Audacity clipboard into label tracks
iii) but _(surprisingly, to me anyway)_ paste alphanumeric text from the Windows clipboard into a label

In contrast to iii) what the Paste command cannot do is to paste alphanumeric text from the Windows clipboard into other alphanumeric fields in Audacity:
iv) Directories prefs
v) Keyboard prefs
vi) Edit > Metadata
vii) Import and Export dialogs
For all these only the Windows shortcut **Ctrl+V** will work 

As with the Copy and Cut buttons issue (and the commands, as @crsib has pointed out) the Paste button also appears to be a regression created somewhere between 2.0.0 and 2.4.2.  I will try to find some time later today to test in which version the regression occurred and then I will log the bug.

@Tantacrul @petersampsonaudacity 
Meanwhile since this residual issue also affects Cut, Copy and Paste too. maybe we could just allow this pull request to be pulled into master for 3.3.0 - and deal with the residual for all buttons as a separate logged issue?

_That would enable me to then get on with updating the Reference Manual._

**Comment by petersampsonaudacity** [comment]
Argh  -  now I'm totally mindblown ...

If I clear my Audacity settings folder and then launch @abhi-kr-2100 's branch and enable the Cut/Copy/Paste toolbar
I now see the Cut, Copy and Delete buttons alll grayed out

**Comment by Tantacrul** [comment]
I think you might be right that if this PR is not introducing issues, then we should fix them separately. I'll leave it up to @crsib to determine if this is the case. Thanks @petersampsonaudacity !

**Review by ksoze95 — APPROVED** [review]

**Pull request merged**
