### PR TITLE
Fix two effects that declared parameters but did not use them...

### PR DESCRIPTION
**Pull request by Paul-Licameli**
... Travis build warnings discovered this problem for me.

### CODE REVIEW

**Comment by lllucius** [comment]
There was actually a reason those were not verified...they aren't part of the saved effects settings.

**Comment by Paul-Licameli** [comment]
You refer to Amplify or Equalization or both?

PRL

**Comment by lllucius** [comment]
Both.  I actually did include the "amp" value when I first converted the effects, but it was determined that it didn't make any sense to save it.  The EQ fellas are basically in the same boat.

**Comment by Paul-Licameli** [comment]
Why does it not make sense for Amplify?

If I use Amplify, then use it again in-session, the last-used amplification
factor is forgotten.

**Comment by lllucius** [comment]
Unfortunately, I don't recall all of the details, but it was all discussed back in April/May of last year.

However, there may have been further changes since then that have broken this or that we didn't get it right back then.

**Comment by lllucius** [comment]
I "believe" it was because mAmp isn't really used when the effect is applied.  Only the ratio is used.

**Comment by JamesCrook** [comment]
Amplification is supposed to be recalculated based on the actual loudness of the audio selected.   This pull request has been around since March.  I figure if Paul would have committed it, and still can even with me closing the pull request, as he has commit rights, if he thought it was OK.

**Pull request closed without merging**
