### PR TITLE
update thumbnail and video link

### PR DESCRIPTION
**Pull request by LWinterberg**

### CODE REVIEW

**Review by vsverchinsky — APPROVED** [review]

**Comment by dozzzzer** [comment]
Tested

**Comment by dozzzzer** [comment]
Windows: 
image

**Comment by vsverchinsky** [comment]
@LWinterberg Seems like new file has Exif format and the previous one had EFIF

**Comment by LWinterberg** [comment]
I don't know why it breaks in CI, it works fine locally 
image

**Comment by LWinterberg** [comment]
Tried metadataless, that didn't work. Trying 4:2:0/DCT integer without arithmetic coding @ 50%

**Comment by LWinterberg** [comment]
Trying now with the image dimensions matching exactly the HTML

**Comment by dozzzzer** [comment]
Tested

**Pull request merged**
