### PR TITLE
Update FR translation (3279 first lines)

### PR DESCRIPTION
**Pull request by trebmuh**
...and a few others bits.

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Thank you, but I still see:

"POT-Creation-Date: 2017-07-22 11:50+0100\n"

That is still not the most up-to-date .pot file.

The latest is

"POT-Creation-Date: 2017-11-06 13:24-0500\n"

**Comment by trebmuh** [comment]
@Paul-Licameli : I'm currently writing an email on audacity-translator about it.

**Comment by trebmuh** [comment]
(message sent to the ML list)

**Comment by trebmuh** [comment]
@Paul-Licameli : message sent to the ML list

**Comment by Paul-Licameli** [comment]
I made other changes to all the .po files, that now make conflicts here that can't be easily solved with git, but they may be solved with msgmerge.

I will close this pull request but put these changes in with msgmerge.

The merged .po file will be based on the latest .pot file, with more empty msgstrs for you to fill in.

However there are still abundant errors from

msgcmp fr.po audacity.po

I see in this diff that in many places you add a #, fuzzy comment.

You do understand that a fuzzy translation will not be used by the program.  If your translation of a string is not in doubt, then you shoudl remove that #, fuzzy line.

Some of these lines are added automatically by the msgmerge program too.

**Comment by Paul-Licameli** [comment]
Olivier,

Please see commit 81f9bf77628c71b6c0afc5cef4a22e5846978565 which merged these updates.

Please base your further work on that version of fr.po.

If you had other updates that you did not yet share, I suggest you rename that version to fr1.po, get the latest fr.po, then on a Unix command line:

msgmerge -U --previous --add-location=file fr1.po fr.po
mv fr1.po fr.po

If you continue this work, I request that you first complete the translation by eliminating #, fuzzy lines where that is correct, and filling in new empty msgstr "" lines.  This is more important than making corrections to messages that already exist.

The goal is to reduce the number of errors reported by

msgcmp fr.po audacity.pot

Thank you for this effort!

Paul

**Comment by trebmuh** [comment]
Hi @Paul-Licameli 

> I see in this diff that in many places you add a #, fuzzy comment.
> You do understand that a fuzzy translation will not be used by the program.
> If your translation of a string is not in doubt, then you shoudl remove that #, fuzzy line.

Yes I added those. My original plan was to make a whole review of the file, leaving some fuzzy when I need to double-check something, and make a last overview at the end of the review. That said, given the short timeline and the impression I have you're pushing me to do so ( :-) ), I'm fine to move from this plan the other way around: "get the rid of the fuzzy strings, then make complete review". So, on my next run through the (new) fr.po, I'll get the rid of the fuzzy lines (and put some translator-comment instead of for my future needs).

Thanks for the updates of the fr.po . By experience with other audio/midi software translations, it makes it much easier for translators if it can be done regularly by a dev' as a part of the usual maintenance.

Cheers

**Comment by Paul-Licameli** [comment]
Apologies if I seem "pushy," but I'm just letting you know what I think is best for you to do with limited time to improve the experience of French speaking users of Audacity.  We are trying to hold 2.2.1 to a tight schedule, but it is also very desirable to get our fr.po more up to date after a period of neglect, and we are thankful to you.

To repeat, besides eliminating the fuzzies, now fr.po is updated to latest audacity.pot, and so there are new blank msgstr lines for you to fill.  That is also priority work.

PRL

**Comment by trebmuh** [comment]
No worries. I do understand that you're giving a direction for the translators team. Be sure there is no offense taken 👍

**Pull request closed without merging**
