### PR TITLE
Fixes the check for the valid UTF8 symbols

### PR DESCRIPTION
**Pull request by crsib**
Resolves: #2132
Resolves: #2134

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
This looks harmless.  I don't immediately understand why this fixes the bug.  Is it because char is signed?  But the signed-unsigned comparison would have coerced the negative to a large unsigned value.

More seriously I should ask why all the logic in XMLWriterx::XMLEsc was not reproduced in XMLUtf8BufferWriter::WriteEscaped.  I should have asked that question with the earlier PR.

**Comment by crsib** [comment]
>But the signed-unsigned comparison would have coerced the negative to a large unsigned value.

This is a signed-signed conversion, unfortunately.

> More seriously I should ask why all the logic in XMLWriterx::XMLEsc was not reproduced in

The problem is that it was mostly reproduced, just with the exception of surrogate pairs handling.

**Comment by Paul-Licameli** [comment]
> > But the signed-unsigned comparison would have coerced the negative to a large unsigned value.
> 
> This is a signed-signed conversion, unfortunately.

DUH!  I see 0x... and assume unsigned, but there wasn't ...u after it.  Of course.

> 
> > More seriously I should ask why all the logic in XMLWriterx::XMLEsc was not reproduced in
> 
> The problem is that it was mostly reproduced, just with the exception of surrogate pairs handling.

**Comment by Paul-Licameli** [comment]
> > But the signed-unsigned comparison would have coerced the negative to a large unsigned value.
> 
> This is a signed-signed conversion, unfortunately.
> 
> > More seriously I should ask why all the logic in XMLWriterx::XMLEsc was not reproduced in
> 
> The problem is that it was mostly reproduced, just with the exception of surrogate pairs handling.

And we know the string has been converted to utf8 here 

```
void XMLUtf8BufferWriter::WriteAttr(const std::string_view& name, const Identifier& value) 
{
   const wxScopedCharBuffer utf8Value = value.GET().utf8_str();

   WriteAttr(name, { utf8Value.data(), utf8Value.length() });
}
```

And that makes the surrogate handling unnecessary?  It is ok to leave all the utf8 encodings un-escap3ed?

**Pull request merged**
