### PR TITLE
NULL check to avoid crash

### PR DESCRIPTION
**Pull request by JoeS209**
Resolves: #7131

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by kryksyh — APPROVED** [review]
@JoeS209 thank you!

**Comment by kryksyh** [comment]
@JoeS209 please rebase on the latest master, to get the ci build working.

**Comment by JoeS209** [comment]
I can do that today.  How do you want me to do this?  From past experience if I just sync the master to my fork, then that will introduce all of those changes to my pull request.

**Comment by kryksyh** [comment]
> I can do that today. How do you want me to do this? From past experience if I just sync the master to my fork, then that will introduce all of those changes to my pull request.

Yes, that should work

**Pull request merged**
