### PR TITLE
5264 easier clip drag insert

### LINKED ISSUE #5264: It's hard to put a clip in between other clips when dragging it across the tracks
### Bug description

It's hard to fit a clip in the position in between other clips by dragging and dropping.

### Steps to reproduce

1. have a blank audio track
2. have another audio track with three identical clips going one after another: 

3. try to move the middle clip up and down and back into its original position

### Expected behavior

A clip can be easily fitted into its original position

### Actual behavior

A clip cannot be fitted into a position easily:

https://github.com/audacity/audacity/assets/70063970/d3f1cbe9-f66f-47bb-959c-81085c1ba193

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #5264 

Please see ticket for detailed description.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by saintmatthieu** [comment]
@vsverchinsky just augmenting the tolerance from 1 to more pixels had the drawback that the clip tended to be inserted to the left of the overlapping clip. I couldn't find an easy way to adapt the code you wrote. I hope this new implementation makes sense.

**Comment by Paul-Licameli** [comment]
All looks good to me

**Review by Paul-Licameli — APPROVED** [review]

**Comment by Paul-Licameli** [comment]
I agree with the new, third commit.

**Comment by dozzzzer** [comment]
Tested

**Comment by saintmatthieu** [comment]
@Tantacrul

**Comment by Tantacrul** [comment]
Damn! I'll test this a little later. That's awesome if it works as expected! 

Is this slated to go in the 3.4 release (it looks like it from the milestone)?

**Comment by Tantacrul** [comment]
Haven't exhaustively tested this but I'm not having the same issues I was having before. Seems good, thanks!

**Comment by dozzzzer** [comment]
> Is this slated to go in the 3.4 release

Absolutely!

**Pull request merged**
