### PR TITLE
VS2013 includes the log2() function, so prevent Nyquist from defining it...

### PR DESCRIPTION
**Pull request by lllucius**
....

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
The .patch file should not be part of the commit?

**Comment by Paul-Licameli** [comment]
Leland, what were the Windows build errors that James says you were fixing?

**Comment by JamesCrook** [comment]
We can delete it (the patch files) in the next push.  No need to rewrite history.  It is small.  And add .patch to .gitignore.

**Comment by lllucius** [comment]
The patch file is supposed to be there...it's how we track changes to the libs.  Well, that's how we've historically done it anyway.

**Pull request merged**
