### PR TITLE
Make this word to be a noun in Spanish, not a verb

### PR DESCRIPTION
**Pull request by pacovila**
Make Silence to be a noun in Spanish as in Generate->Silence, not a verb

### CODE REVIEW

**Comment by windinthew** [comment]
Thanks. It is probably a good change but our policy is to use the audacity-translation mailing list 

https://lists.sourceforge.net/lists/listinfo/audacity-translation 

for translation changes. Please follow that link to subscribe to the list. 

So I'm closing this.

**Comment by pacovila** [comment]
Thank you but there it says very clearly it's for "any decent sized pull requests" or "anything that is more than a couple of lines". My patch changes a single word (or rather a fraction of one). I suggest to change those wordings so that people collaborating tiny changes like mine don't get confused for both following a policy and not following it at the same time.

**Comment by windinthew** [comment]
Hello, our policy is for translations to be handled on the -translation list  http://wiki.audacityteam.org/wiki/GitHub_Pull_Requests#Milestones .

**Comment by windinthew** [comment]
Now that 2.1.3 is released I committed this https://github.com/audacity/audacity/commit/64a6fa6 in order to get it done. Looking forwards perhaps to seeing you on the -translation list at some future time.

**Pull request closed without merging**
