### PR TITLE
Add option to run chain from the command line

### PR DESCRIPTION
**Pull request by corycook**
Added --chain (-c) option to the list of command line options.

audacity.exe -c "MP3 Conversion" file1.wav file2.wav ...
audacity.exe --chain="MP3 Conversion" file1.wav file2.wav ...

will Normalize/Convert all files passed as arguments

Ensures all files passed are valid paths

It shows the list of files and process dialog for each effect/command same as Apply To Files from BatchProcessDialog.

Opted not to show the primary window since they could just open Audacity and run the chain from there. This would be for more passive application.

### CODE REVIEW

**Comment by JamesCrook** [comment]
Sorry we have been 'off the air' for so long.  
Could you come and talk with us on audacity-devel about this, https://lists.sourceforge.net/lists/listinfo/audacity-devel  and we can look at whether this is good for 2.1.3 ?

**Comment by JamesCrook** [comment]
Has conflicts with current code.

No response to my email on audacity-devel about using mod-script-pipe for automation: "I am feeling the special new command line switch is adding complexity to Audacity and Audacity documentation for not enough real advantage."

Closing; not accepted.

**Comment by SteveDaulton** [comment]
To Cory: Although this pull request has been closed, the invitation to talk about this proposed new feature, on the developer's mailing list, remains open.

Re. 'do we want this': From user feedback, there is certainly interest in more flexible command line options, and personally I this proposal is an interesting approach. There's a lot of scope for future development of scripting / automation, and I'd welcome a discussion with Cory about his proposal within that context. (Mailing list is here: https://lists.sourceforge.net/lists/listinfo/audacity-devel)

**Comment by iwillneverjoin** [comment]
Thanks for this Cory.  Only needed 1 minor change to compile 2.1.2 (file src/AudacityApp.cpp line 1422 in the shown patch, return needed a boolean value) and of course line numbers have changed slightly but not too hard to figure that out.  Don't know if I'm the only one that was looking for this but thanks all the same :)

**Pull request closed without merging**
