### PR TITLE
Update Italian translation

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by JamesCrook** [comment]
Hi Michele,

Please join the translators list and talk with Carmelo Battaglia there.  He is coordinating translation for Italian.

**Comment by mlocati** [comment]
@JamesCrook I already contacted him via email (a couple of months ago)

**Comment by JamesCrook** [comment]
@mlocati what did Carmelo say about your changes?  Has he reviewed them?

**Comment by mlocati** [comment]
@JamesCrook we discussed a bit about writing rules. He prefers to use a more personal approach when writing strings, I prefer to use the well established and discussed [rules defined by the Italian section of the Free Translation Project](http://tp.linux.it/buona_traduzione.html).
Anyway, we also wrote:

> hai un grande merito nell’aver eseguito una revisione completa di tutte le stringhe di Audacity e sarei veramente felice che tu voglia continuare in futuro l’aggiornamento delle prossime versioni perché io comincio a essere stanco di tale impegno e volentieri ti cederei il lavoro.

Which, transladed, sounds more or like a go for my strings, and he expresses the wish to deletage to me the maintenance of the Italian translations.

**Comment by JamesCrook** [comment]
Thanks Michele.  I merged it.  For future updates to .pot file I have a preference for receiving them on the translation mailing list.  Announcements about when we are needing updates (and when we are NOT taking them due to release in progress) are made there.

**Comment by mlocati** [comment]
> For future updates to .pot file I have a preference for receiving them on the translation mailing list.

Why? I think that seeing here on GitHub is much nicer, since you (and everybody) can see the differences very easily.

> Announcements about when we are needing updates (and when we are NOT taking them due to release in progress) are made there.

I'd prefer a more continuous system (like I suggested [in the mailing list](https://sourceforge.net/p/audacity/mailman/message/36526610/): developers update the code, a [TravisCI job](https://github.com/audacity/audacity/pull/335) updates the .pot file, an online tool (like Transifex) can be configured to fetch the .pot file on a regular (daily) basis, translators translate strings as soon as they are available in Transifex (or whatever).
That way, we'd have a collaborative, continuous (we don't have to translate tons of strings on a hurry right before a release).
The nice stuff of Transifex is that is allows translators to work with .po files (they can download/upload them).

**Comment by trebmuh** [comment]
I'm against using transifex (private business, non-free). I could cope with weblate tho, and I'm fine with the current system.

**Comment by mlocati** [comment]
> I'm against using transifex (private business, non-free).

@rebmuh I also am not a great supported of closed source projects (that's one of the reasons why I developed [CommunityTranslation](https://github.com/concrete5/addon_community_translation), an online collaborative tool currently used by [translate.concrete5.org](https://translate.concrete5.org) to translate concrete5).
Nevertheless, IMHO online collaborative translation is much more powerful than offline translation...

**Comment by trebmuh** [comment]
Depends, a badly configured online service (such as transifex, weblate, ...wathever) is less useful, more error-prone, and more selfish-oriented than a mailing list which has proven being useful in Audacity's case for a bunch of years now.

Anyway, this discussion shouln't happen here on github but on the translators mailing-list. Please, switch it to there.

**Comment by JamesCrook** [comment]
@mlocati please, as trebmuh says, have such discussion about tools for translation on the translators list.

As a practical matter, I personally find it easier to handle po files that arrive at the email address.  So if you do post here, they are likely to sit for much longer without comment from anyone.  Your choice though.

**Pull request merged**
