### PR TITLE
Top navigation bar cleanup

### PR DESCRIPTION
**Pull request by ksoze95**
Resolves: #2716

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by vsverchinsky — APPROVED** [review]

**Review by Paul-Licameli — CHANGES_REQUESTED** [review]
I'm trying to build each commit.

At the second commit, it built, but running Audacity, I noticed the wrong images were shown in the edit toolbar.  The old Cut image was on the button that still correctly did Trim, and so on.

The CMake Dependencies are not set up so that the *AsCeeCode.h files are regenerated when images are only deleted.

Deleteing the generated *AsCeeCode.h files and rebuilding does fix it.

How can the rebuilding be made automatic without requiring the developer to do that?

I think I have an answer, which I may give by pushing a commit onto this branch.  I suggest you then interactively rebase, permuting that commit to the start of the sequence.

**Comment by Paul-Licameli** [comment]
I confirmed that my added commit works to do what I want, when it is at the appropriate place in the sequence of commits.

Please fetch this commit, and do interactive rebase to put it first in the sequence of commits, then force-push this branch again.

**Comment by Paul-Licameli** [comment]
Otherwise, this PR looks good.

I would only question whether changing the default width of Audacity (when started with a fresh audacity.cfg files), to 1200 is acceptable to designers.

Also I need View > Toolbars > Reset Toolbars if I restart Audacity without a fresh audacity.cfg in order to see the desired changes of layout.  Old users of Audacity migrating to the new version might observe the same.

Hm, what's the fix for that?

**Comment by LWinterberg** [comment]
> I would only question whether changing the default width of Audacity (when started with a fresh audacity.cfg files), to 1200 is acceptable to designers.

It is, because:

* #2717 and the vertical volume meter may require further changes to the default width, so this is an acceptable temporary solution until we know just how wide things need to be
* Even if this temporary change becomes a permanent one, I think the only somewhat common desktop resolutions smaller than 1200 would be 800x600 and 1024x768 - and both of those are quite vintage. 
* And even if someone finds out their screen is too small for the new default, they will be able to just resize it.

> Also I need View > Toolbars > Reset Toolbars if I restart Audacity without a fresh audacity.cfg in order to see the desired changes of layout. Old users of Audacity migrating to the new version might observe the same. Hm, what's the fix for that?

This is indeed tricky. The Audacity installer has a toggle to reset configuration, though that of course is quite nuclear. Maybe there should be another toggle, checked by default, saying "switch to new default layout" which is essentially the View > Toolbars > Reset Toolbars?

**Review by Paul-Licameli — APPROVED** [review]

**Pull request merged**
