### PR TITLE
Update the French translation

### PR DESCRIPTION
**Pull request by trebmuh**
@Paul-Licameli : with this batch of translation, I did focused more on the fuzzy and untranslated strings as requested. Still I did some corrections/fixes/improvements on other strings while scrolling the file.

I'll certainly not have time to work on it tomorrow (but maybe a bit) and will continue on Monday/Tuesday.

Feel free to merge it right now or to wait for me to add more commits to this PR. No preference from me.

HTH

**Edit:** I forgot to let you know that I put some _translator-comments_ as defined in [the gettext manuel](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html#PO-Files). I did so when I've had a doubt about different topics (accelerators management is one of those) to ease a future revision for me when it requires a deeper reflexion. **Please, do not strip these (_you can see those with searching for "trebmuh" in the file_).**

### CODE REVIEW

**Comment by trebmuh** [comment]
Made Travis happy eventually. :)

Looking [at its log here](https://travis-ci.org/audacity/audacity/builds/307346157#L5586) tells us: `fr.po: 2759 translated messages, 94 fuzzy translations, 251 untranslated messages.` which enlighten me since I'm sure it's doable to have great French coverage for the upcoming version (2.2.1, right ?) and start a whole review afterward (because, even when we'll have "0 fuzzy translations, 0 untranslated messages", I can ensure you that there is a much bigger job to do in the French translation, consistency across it is really needed I can swear).

HTH

**Comment by Paul-Licameli** [comment]
With this I now see only 345 errors from

msgcmp fr.po audacity.pot

Formerly, over 1000.  This is good.

You are making rapid progress, and it seems still in flux, so I will wait a little more for more word from you.  Add more commits to this branch.

PRL

**Comment by Paul-Licameli** [comment]
Thanks again for the effort.

I see what you are doing:  replacing #, fuzzy with your own note-to-self
comments, for later review.  If I rebuilt the product today with only those
changes, that would expose those French strings to users choosing French
locale.

What would seem worse to the Francophone user who is not good with English
-- some inconsistency in the French terminology or punctuation, or the
grosser inconsistency of having only some things translated, but many other
things left in English?  The second is what you get leaving the #, fuzzy in
place.

But perhaps you really do think that much of the existing French
translation was very bad and misleading, even worse then sending people to
their French-English dictionaries?

PRL

**Comment by trebmuh** [comment]
> With this I now see only 345 errors from

Yes, this looks to be like the "94 + 251" [reported by the Travis build](https://travis-ci.org/audacity/audacity/builds/307346157#L5586).

> You are making rapid progress, and it seems still in flux, so I will wait a little more for more word from you. Add more commits to this branch.

Thanks for that, I might have a bit of time later today to work on continuing the translation. I'll push another commit to this PR then.

>  I see what you are doing: replacing #, fuzzy with your own note-to-self comments, for later review.

Exact.

> If I rebuilt the product today with only those changes, that would expose those French strings to users choosing French locale.

Really ? Just to be sure that I get it, you mean that if you rebuilt Audacity with this commit, users will then see the `# trebmuh to check` strings in the GUI interface, or did I misunderstand what you said?

> But perhaps you really do think that much of the existing French translation was very bad and misleading, even worse then sending people to their French-English dictionaries?

Reading that, I realize that I might have be a bit too strong on my last message here. The actual translation is not that bad (it's good, I've seen much much bad than that, like when I started reviewing the FR translation for mhwaveedit), but I can find a bunch of incorrect translations, some being misleading.

I'll keep it going and keep pushing commit to this PR.
Cheers

**Comment by trebmuh** [comment]
> With this I now see only 345 errors from

Yes, this looks to be like the "94 + 251" [reported by the Travis build](https://travis-ci.org/audacity/audacity/builds/307346157#L5586).

> You are making rapid progress, and it seems still in flux, so I will wait a little more for more word from you. Add more commits to this branch.

Thanks for that, I might have a bit of time later today to work on continuing the translation. I'll push another commit to this PR then.

>  I see what you are doing: replacing #, fuzzy with your own note-to-self comments, for later review.

Exact.

> If I rebuilt the product today with only those changes, that would expose those French strings to users choosing French locale.

Really ? Just to be sure that I get it, you mean that if you rebuilt Audacity with this commit, users will then see the `# trebmuh to check` strings in the GUI interface, or did I misunderstand what you said? If yes, it shouldn't work like that if reading at the [gettext manual here](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html#PO-Files) where we can see:
 One PO file entry has the following schematic structure:

```
white-space
#  translator-comments
#. extracted-comments
#: reference…
#, flag…
#| msgid previous-untranslated-string
msgid untranslated-string
msgstr translated-string
```
Anyway, if the `# trebmuh to check` are to be shown on the GUI, it's a pita and I suggest to remove those before building the final next Audacity version. I'll still keep those in my branch fork on github and will then be able to re-merge these in after 2.2.1 publication if needed. What do you think?

> But perhaps you really do think that much of the existing French translation was very bad and misleading, even worse then sending people to their French-English dictionaries?

Reading that, I realize that I might have be a bit too strong on my last message here. The actual translation is not that bad (it's good, I've seen much much bad than that, like when I started reviewing the FR translation for mhwaveedit), but I can find a bunch of incorrect translations, some being misleading.

I'll keep it going and keep pushing commit to this PR.
Cheers

**Comment by Paul-Licameli** [comment]
I do not mean that users will see

#trebmuh to check

Oh no!  What I mean is, there are certain strings in the msgstr directives, and there are #comment lines associated with the strings.  When there is an associated #, fuzzy comment, then the string will not be seen by users.  If you remove that comment or replace the comment with some other, then the string will be seen by users.

But surely the comments themselves are not seen!

PRL

**Comment by Paul-Licameli** [comment]
So if that is understood, what I meant about priorities is this:

Looking quickly at commit 81f9bf77628c71b6c0afc5cef4a22e5846978565 I see examples like this:

-msgstr "Récupération automatique de crash"
+msgstr "Récupération automatique de plantage"

While I understand it's good to correct such ugly "franglais" into better French, or fix spelling and grammar and punctuation mistakes, still, if bad strings are not very frequent, then I would rather first complete the translation, supplying the missing strings.

There were hundreds of those.  And while any string is still marked fuzzy, consider it missing.

Some fuzzy strings, you may have marked as such.  Others might have been marked such by the msgmerge program, which makes guesses in case one untranslated msgid is similar to another translated one -- but it may guess wrongly and suggest something with a very unrelated meaning.

Those may need more attention -- don't remove "fuzzy" indiscriminately.  I think they should also be marked with automatic #| comments, if I ran msgmerge correctly.

PRL

**Comment by trebmuh** [comment]
Those 3 last commits:
- gets the rid of all "fuzzy" string (yeah!)
- translates a few "untranslated" strings (still a bunch to go)
- corrects a few typos I spotted on
- checks (and changes when needed) consistencies around the following topics:
1) unification : the "preset" words are now all translated to "préréglage" rather than "présélection" or "pré-réglage" or others (it's the commonly used translation for "preset")
2) CC ("courant continu" in French) rather than "DC" ("direct current" in English)
3) accentuated capital letters in the French translated strings such as "Éditer" instead of the wrong "Editer", or "A" -> "À" when relevant
4) correct a mistake : "decay" was wrongly translated to "delay" in French, while it should have been "relâche" (this was very misleading)

@Paul-Licameli , re: "#trebmuh to check", OK, I'm happy that those comments doesn't shows up in the GUI ! :o) _(In order to ensure you that we are on the same page: yes, I understand that when a "#, fuzzy" line is present, then the translation is not shown in the GUI, and when I remove it, the translation is shown)_

About my translation method, I'm working with a simple text editor (pluma from the MATE environment) which is showing me the whole text. This is making me reading at a lot of strings, so when I can see some mistake/typo/punctuation, it's easy and quick to just correct those. Taking the example in your previous message (crash->plantage) when I encountered the first one, I used then a search & replace (not fully automatic, but it asks me each time for the replace confirmation), then it doesn't take a lot of time either. That's pretty much why, even if specialized software (like poeditor or other) are useful for certain cases/persons, I found myself being much more happy with working with a simple text editor.

> Those may need more attention -- don't remove "fuzzy" indiscriminately.

Do not worry, I'm not doing that. When I remove a "fuzzy", this is because I checked the translation first.

Travis is saying that there are only 202 untranslated left. I might be able to finish most of those by the 29th.

**Comment by trebmuh** [comment]
In these 3 last ones:
- a bunch of untranslated strings
- disambiguation: "decay" (EN) -> "déclin" (FR)
- disambiguation: "save" (EN) -> "sauvegarder" (FR) and "record" (EN) -> "enregistrer" (FR)
- consistency around "preset" (EN) -> "préréglage" (FR)
- consistency around the "are you sure?" (EN) strings
- consistency around "discard" (EN) -> "abandonner" (FR)
- consistency around "batch chain" (EN) -> "traitement par lot" (FR)
- consistency around "presmooth" (EN) -> "prélissage" (FR)
- fixes "sample rate" which was incorrectly translated with "fréquence d'échantillonnage" while the correct translation is "taux d'échantillonnage"
- fixes "bit rate" which was incorrectly translated with "débit" while the correct translation is "débit binaire"
- fixes a misleading translation where a "bit  rate" (EN) was translated to "taux d'échantillonnage" instead of "débit binaire"
- a few typos/punctuations/...

+ updates the header's timestamp

During that, I've found 2 typos (I think) in the source and made a Pull Request: https://github.com/audacity/audacity/pull/219 hoping that'd be useful for Audacity.

Travis is saying that there are 98 remaining untranslated strings.

**Comment by trebmuh** [comment]
- French translation updated to 100% (yeah !)
- improvements of a bunch of `#trebmuh to check` annotations
- consistency around "preset" -> "préréglage"
- consistency around "library" -> "bibliothèque"
- fixes a few typos/mistakes/punctuations
- added Christian Brochec in the header

Travis seems happy and reports that all the 3104 strings are translated.

@Paul-Licameli : it seems to me to be in a pretty good shape for the 2.2.1 release. Feel free to merge it to master. If I find some stuff to be changed, I'll update this PR (if not yet merged) with more commits or I'll open another PR.

**Comment by trebmuh** [comment]
Those 2 ones:
+ adds Christian Brochec in the header
+ better translation for 3 strings
+ a bunch of missing accelerators
+ a bunch of note-to-self precisions
+ few typos
+ consistency around "range" (EN) -> gamme/éventail (FR)

**Comment by trebmuh** [comment]
Those 3 ones includes:
- get the rid off the (useless now) "#| msgid" (which were ancient translation)
- better translation for 3 strings
- a bunch of note-to-self precisions
- a bunch of missing accelerators
- a couple of better accelerators
- few typos
- consistency around "range" (EN) -> gamme/éventail (FR)
- adds Christian Brochec in the header
- update the timestamp in the header

**Comment by trebmuh** [comment]
Those 4 ones includes:
- get the rid off the (useless now) "#| msgid" (which were ancient translation)
- better translation for 3 strings
- a bunch of note-to-self precisions
- a bunch of missing accelerators
- a couple of better accelerators
- few typos
- consistency around "range" (EN) -> gamme/éventail (FR)
- adds Christian Brochec in the header
- update the timestamp in the header

**Comment by trebmuh** [comment]
@Paul-Licameli : I took the liberty to mention the LibraZiK project [on line 517](https://github.com/audacity/audacity/pull/218/files#diff-93e30190dec4ab6cb403e6cfd69043e7R515) which is why I started this translation effort first. I hope it's correct to do so. If it wasn't, please let me know.

**Comment by Paul-Licameli** [comment]
Catching up now.  Good work!

I still get one error from
msgcmp fr.po audacity.pot

But I see that is because you accidentally changed one msgid:

msgid "Confirm Cncel"

I will fix that.

**Comment by Paul-Licameli** [comment]
We are very pleased to get fr.po up to 100% !  Thank you!

I notice that you updated lines that start with
#~ msgstr

I regret to say, that was unnecessary work, because #~ lines are for obsolete messages for msgids that the program no longer uses.  These lines are generated by msgmerge when I update fr.po to audacity.pot .  It's your choice to keep them in the file for reference, or just delete them.

I will "squash" and commit your changes to fr.po and audacity.iss, with the one correction to a msgstr that I last mentioned.

I still see 320 "trubmuh to check" comments.  Do you intend to address more of these very soon?

PRL

**Comment by Paul-Licameli** [comment]
This work is now committed at b69a272ad97fbb5a0eee61bd784e7003fb1e6987

**Comment by trebmuh** [comment]
> I still get one error from `msgcmp fr.po audacity.pot` But I see that is because you accidentally changed one msgid: `msgid "Confirm Cncel"`. I will fix that.

Sorry for that, and thanks for having fixing it. It's a bit strange that Travis didn't see it.

> I notice that you updated lines that start with `#~ msgstr` I regret to say, that was unnecessary work, because #~ lines are for obsolete messages for msgids that the program no longer uses. These lines are generated by msgmerge when I update fr.po to audacity.pot . It's your choice to keep them in the file for reference, or just delete them.

Yes I know I did that :) That said, I have a doubt. I kind of vaguely remember reading that if one of those `#~ msgstr` are re-enable in the source, then gettext will automatically get them back. Can you please confirm/infirm?

> I still see 320 "trubmuh to check" comments. Do you intend to address more of these very soon?

Absolutely. Most of those 320 comments string (roughly ~ 250 of those) are about improving the accelerators in the GUI. To make a proper work with accelerator, one needs to have the GUI running (in order to check the consistency of the accelerators). This needs to have a rebuild of the software according to the source where those accelerator are defined. Given (1) the short time frame I had to review this translation, (2) the time needed to do a proper job with accelerator, and (3) following your advice (translating first the "fuzzy" and the untranslated strings), I choose to leave this part uncompleted for the moment (although I've already been improving this part a bit while doing this translation review) and to wait for the 2.2.1 release to have a proper build with the translation included to work with. In other words, I plan to remove the `# trebmuh to check` for the 2.2.2 release.

Lastly, to give you a more thorough understanding of my work here, I intend to monitor the GUI French translation of the GUI from now.

Cheers, and thanks for the merge @Paul-Licameli .

**Pull request closed without merging**
