### PR TITLE
Vst refresh rate

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #3902

Dragging plain UI sliders or fancy UI controls of VST2 effects, during playback, will not cause the
green play head's movement to slow noticeably.

Note this PR is based on #3900 which may be reviewed separately and merged first

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by pietro68** [comment]
I am sorry but after some extensive testing comparing this branch with the release one, I found that 2 bugs were (accidentally?) fixed, but 4 more have appeared. Please check the included PDF for details.

[vst2-tests.pdf](https://github.com/audacity/audacity/files/9973730/vst2-tests.pdf)

**Comment by Paul-Licameli** [comment]
Too many regressions, too much deepening confusion when I try to amend it, too little time to figure out what complete rewrite of this PR is really needed.

**Comment by pietro68** [comment]
> Too many regressions, too much deepening confusion when I try to amend it, too little time to figure out what complete rewrite of this PR is really needed.

I agree, what if we de-prioritize this issue and go back to fixing what is in the release branch? which at this point I would say, is only issue 3842.

**Comment by Paul-Licameli** [comment]
I figured out the difficulties and am reopening this PR!

@pietro68 please test your matrix of cases again.  I have verified myself the column for DeeGain.

**Pull request closed without merging**
