### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by prokoudine**
Had to use Audacity again, got a bit frustrated over some user-visible untranslated entries, did a quick update.

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Thanks Alexandre, but this failed to pass Travis.  There is at least one error to fix:

ru.po:8971: number of format specifications in 'msgid' and 'msgstr' does not match
/usr/bin/msgfmt: found 3 fatal errors

**Comment by prokoudine** [comment]
Thanks! Fixed

**Comment by prokoudine** [comment]
Well, should I close this PR and open a new one?

**Comment by Paul-Licameli** [comment]
Don't do that, I will catch up with this today.

**Pull request merged**
