### PR TITLE
Update icon and installer images

### PR DESCRIPTION
**Pull request by Pokechu22**
Fixes [bug 1789](https://bugzilla.audacityteam.org/show_bug.cgi?id=1789).

There were actually two things that needed to be updated, which I've done in separate commits.

* The `audacity.ico` file: this is the icon used on the first page of the installer (the one for choosing a language); however it is also used in a number of other places, including as the actual icon for the app and the installer.  So all of those have been updated with this change.

    PRL mentioned:

    > I look in GIMP and see it's actually many image layers, each showing the old
icon with various magnifications, and some sub-pixel half-toning going on in each.

    To clarify about that, ICO contains a bunch of different sizes and bit depths.  The sizes that are provided in the audacity icon are 256x256, 128x128, 96x96, 64x64, 48x48, 32x32, 24x24, 16x16, 14x14, 10x10, and 8x8.  The original icon included bit depths of 4, 8, and 32; I've gotten rid of all but 32 since I find it extremely unlikely that anyone's using a 4 or 8 bit-per-pixel display (and couldn't find a proper way to generate those depths either).

    I generated the icon using the following script (which uses [imagemagick](https://imagemagick.org/) and the logo from [here](http://wiki.audacityteam.org/wiki/File:Audacity_Logo_large_transparent.png)):

    ```bash
    base=Audacity_Logo_large_transparent.png
    out=audacity.ico
    files=
    for size in 256 128 96 64 48 32 24 16 14 10 8; do
        file="tmp_icon_${size}.bmp"
        convert "$base" -resize ${size}x${size} -extent ${size}x${size} "$file"
        files+=" $file"
    done
    convert $files "$out"
    rm $files
    ```

    This new icon should maybe also be used on the various websites, as they're also using the old icon.

* The installer images: these are used on the other pages of the installer.  I made audacity_InnoWizardImage.bmp using [the wiki logo](https://www.audacityteam.org/wp-content/uploads/2016/01/NEW_AudacityTransMediaWiki_sans_serif.png), and the other one using a resized version of the icon.

I have not attempted to handle the mac icon, as I don't know how to edit those (I don't even know which files are needed for the mac installer).

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Poke,

Look in mac/Resources and find eight image files.  One is .png (the background that opens for the Mac .dmg).

The other seven are .icns files.  A little Googling tells me ImageMagick might not support that one.  But maybe that is out of date information.

PRL

**Comment by Paul-Licameli** [comment]
It seems it's not hard to find programs to interconvert that format, even if ImageMagick won't.  For instance:  https://iconverticons.com/online/#

**Comment by Pokechu22** [comment]
It does seem like ImageMagick doesn't work for icns, and gimp also doesn't seem to have saving support for it (but there is [a plugin](https://github.com/brion/gimp-icns) to read them).

According to [this article](http://applehelpwriter.com/2012/12/16/make-your-own-icns-icons-for-free/) there's a program built in to MacOS, which converts a bunch of specially-named PNGs of various sizes -- PNGs which I can generate with ImageMagick.  I do have access to a mac so I should be able to run that on a different machine.

I've updated the DMG background, though, using [this image](http://wiki.audacityteam.org/wiki/File:Audacity_Logo_signika_512_transparent.png).

**Comment by Paul-Licameli** [comment]
I have rebased and pushed these changes, thanks.

Poke, look in mac/Resources.  There is one .png file and seven files with extension .icns.  Can you figure out edits for those too?

**Comment by Pokechu22** [comment]
Currently working on those right now

**Comment by Pokechu22** [comment]
I'll create a new pull request with them, to make this a bit less confusing

**Comment by Paul-Licameli** [comment]
Sorry, our updates crossed, and I closed this PR.  Please open another for the Mac images.

PRL

**Comment by Paul-Licameli** [comment]
Or, I can just reopen.  Done!

**Comment by Paul-Licameli** [comment]
I merged the change for the background .png.  It looked good -- the important thing being that the positions of the arrow and the blank spaces are unchanged.

I hope some solution for the .icns files can also be found, perhaps converting to .ico, editing, and converting back?

**Comment by Paul-Licameli** [comment]
I see with Preview on macOS that win/audacity.ico had 27 images, but now has only 9.  You explained that as using only a 32 bit depth, not supplying three depths.

All right.

**Pull request merged**
