### PR TITLE
Added Pro Tools theme

### PR DESCRIPTION
**Pull request by jonata**
Just an optional theme for those familiar with the Avid DAW.

### CODE REVIEW

**Comment by JamesCrook** [comment]
Hi Jonata.  Please discuss on our devel email list.
This pull request is probably not suitable, as the graphics are likely to be copyright protools.

**Comment by SteveDaulton** [comment]
Looks like you've got an unresolved merge conflict in src/Theme.cpp

**Comment by jonata** [comment]
That is just some tweak we made on a customised build we use here. The graphics does not contain any copyrighted material as it uses Audacity logo, just from another iconset/style. I just wanted to offer it for the team, but certainly this is not something essential to Audacity. So, no problem rejecting it.

**Comment by JamesCrook** [comment]
Jonta, before I close this, can I encourage you to make your Pro Tools theme into an ImageCache.png file and provide it for download somewhere for people who are interested?  If you already do so, tell us where.

If you are using Pro Tools styles and icons, I would expect them to be covered by Pro Tools copyright.  If you aren't, and from what you say it sounds like you aren't, then calling it 'Pro Tools' theme is not very accurate, so you would need a different name.

**Comment by jonata** [comment]
Hi James! I will look at some more information about copyright use of the icon styles, and hopefully make it available for download somewhere with a different name. I fully understand the implications you presented. Anyway, thank you so much for your consideration.

**Comment by JamesCrook** [comment]
Thanks Jonata.

**Pull request closed without merging**
