### PR TITLE
Fix source newlines for translation from \n to ~%

### PR DESCRIPTION
**Pull request by RockyTDR**
Thanks to @Phroneris on Transifex for noticing this
@JamesCrook

### CODE REVIEW

**Comment by JamesCrook** [comment]
Thanks.  We are in string freeze and most translations are already in, so these will wait until later.  We will aim to get this right for 3.0.2.

**Comment by RockyTDR** [comment]
@JamesCrook Any news to approve this pull request?

**Review by JamesCrook — APPROVED** [review]
LGTM.

**Comment by JamesCrook** [comment]
Tanks for the 'bump' (i,e thanks for reminding me of this pull request).

**Pull request merged**
