### PR TITLE
Hot fix for broken realtime effects

### LINKED ISSUE #4859: Non-op realtime effects (incl. the built-ins)
### Bug description

None of the real-time effects families are working, including the built-in ones.

### Steps to reproduce

1. Have some audio clip
2. Select some effects in the stack
3. Start playback

### Expected behavior

The effects changing the sound correspondingly

### Actual behavior

No changes to the sound, as if they were bypassed.

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

A regression introduced by https://github.com/audacity/audacity/commit/35a0869c240631d235f05c0063f340ba3d1feee8

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #4859 

Realtime effects work by AudioIO getting the realtime-effect list attachment onto its playback sequences.

Problem : those are now injected, attachment-less `CachingPlayableSequence`s, which decorate the `WaveTrack`.

Quick fix : we give `WideSampleSequence` a method to return it's decorated version, which can then be used by AudioIO.

Longer term fix (maybe) : this is another incarnation of the problem we had with `GetMute/GetSolo`, also implemented as `WaveTrack` attachments. The solution was to find the right place for an abstract API, which internally is implemented by `WaveTrack` through query of its attachment. Now it's an abstraction for `RealtimeEffectList` that is needed, at least the part of it needed by AudioIO to apply real-time effects.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by crsib — APPROVED** [review]
I can approve it as a hotfix, but I am really confused with the approach, where decorator masks vital parts of the decorated objects. I can see it as a source of a lot of bugs in the future.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @sahilsekr42 's branch build:  audacity-win-3.4.0-alpha-20230629+0feda0a-x64

I confirm that the realtime effects now work again with this branch build.

But I uncovered a further associated regression when adding a further realtime effect while the audio is playing - I will add this as a new issue.

**Comment by saintmatthieu** [comment]
Follow-up problems described in https://github.com/audacity/audacity/issues/4864 and https://github.com/audacity/audacity/issues/4865, as well as the broken-recording problem https://github.com/audacity/audacity/issues/4860 have a similar root cause. Since this is a small PR, I choose to fix them all here.

**Review by crsib — COMMENTED** [review]
How long would it take to do a proper fix, that doesn't expose `GetDecorated` in all the places around the code?

**Comment by saintmatthieu** [comment]
I haven't come up with a good solution. If I could find a way of getting compilation errors wherever `WideSampleSequence` pointers are compared that would count as a better fix.

Alternatively letting `WaveTrack` own the sample views for caching, instead of using a `CachingPlayableSequence` for that, that wouldn't be too bad. The stretching decorator, though, is more complex, and it's nice to keep that logic separate.

Or don't inject `CachingPlayableSequence` _in place of_ `WaveTrack` but _besides_.

**Comment by saintmatthieu** [comment]
Added @Paul-Licameli to this review to contribute to this discussion.

**Comment by Paul-Licameli** [comment]
I'm watching this PR and I have no strong objections.

I don't like disturbing the WideSampleSequence interface, but something like this is really needed.

I may have ideas about making it more elegant, but I'll propose my own PR after all the bugs are found and fixed.

**Comment by saintmatthieu** [comment]
@dozzzzer ready for merge ?

**Comment by saintmatthieu** [comment]
@petersampsonaudacity thank you!

**Pull request merged**
