### PR TITLE
Bug2464

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Implement the dragging of labels between tracks with TimeShift.

Also move the new TrackShifter subclasses into three new source files, separating them from the rest of TrackView subclass code.  They may have dependency on the views, but not the reverse.

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Now there are two enhancements:
Dragging of labels from track to track (up to the first merge commit), and
Dragging of labels from track to track can carry clips with it, and dragging of clips can carry labels

**Comment by JamesCrook** [comment]
I'm not keen on the greater use of events, rather than calls, but that's a philosophical difference, and doer-decides trumps that in this case.  I understand how it helps 'untangling'.  Similarly for what looks like more near-duplicated code in d508b8.  We're seeing a lot of similar code for renumbering label index things.

Overall goal though makes this well worth having.  So added to master.

**Comment by Paul-Licameli** [comment]
Some implementation of the "observer" (or call it "publisher/subscriber" pattern) is a necessity so that LabelTrack is not statically dependent on the code that receives the notifications, here and in other already existing places.

Whether wxEventHandler implements it or not is an implementation detail.  I would like to reimplement many such cases of the observer pattern without it.

**Comment by JamesCrook** [comment]
Would the planned reimplementation be easier to step through?

**Comment by Paul-Licameli** [comment]
Surely there would be far fewer levels of stack between the sending of the message and the entering of the callback function.

Because LabelTrack is broadcasting a message to multiple listeners, the single stepping might have you entering and exiting LabelTrackView::OnLabelPermuted() before you reach LabelTrackShifter::OnLabelPermuted().  But this would be a simple traversal of a list or array of observers, and not the complicated and more generalized business inside wxEvtHandler().

The implementation of those callbacks would be a little simpler and less error prone because event.Skip(); would not be needed to prevent an observer from consuming the message and blocking the broadast from later observers.

**Pull request merged**
