### PR TITLE
Recommend incremental, self-contained commits for large changes...

### PR DESCRIPTION
**Pull request by Paul-Licameli**
... And make the statements concise

### CODE REVIEW

**Review by JamesCrook — CHANGES_REQUESTED** [review]
👎 The original wording is clearer and more friendly.

**Comment by Paul-Licameli** [comment]
The original wording is verbose and not specific about what constitutes "unnecessary changes."  I don't want that construed to mean you can't improve comments or readability or modernize the C++ idioms.  So I restate things rather in terms of effects on the program's behavior.

**Comment by shoogle** [comment]
I like some of the changes but not all. My suggestions are here: https://docs.google.com/document/d/1H3hjFZ58e-wZyt00JoJgI9GXUfOEQ8_pek0jtAK2s1A/edit

**Comment by Paul-Licameli** [comment]
"Each commit does “one thing” and the commit message(s) meet these guidelines" with a link.

I don't like saying "doing one thing" because there are many ways you can count "things," and it's not too bad to combine several small things into one reasonably sized commit.

Rather it's important not to combine so many things in one commit that they overwhelm a reviewer.  Yes, subjectivity there too.

But whatever "things" are contained in one commit, they are complete things, and complete in the sense I stated:  Each commit is known to build and run without known bad behavior.

Besides aiding review, the splitting of a big change into increments that build and run make possible the bisection of bugs to some part of a large project, if bugs are discovered later.

**Review by crsib — APPROVED** [review]

**Review by shoogle — APPROVED** [review]

**Pull request merged**
