### PR TITLE
Deduplicate effect stack

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #5127

Depends on
- #5128

Store the real-time effect stack in `ChannelGroup` attachments, just as
we do for name, rate, solo, etc.

`WideSampleSequence` no longer needs to be another `ClientData::Site`.

Some changes result in library dependencies, and `WaveTrack` now has one
fewer member function to explain.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Rebased onto master; no longer dependent on #5128.

This PR is meant to fix issue #5127 .  PR #5128 is no longer claimed to fix it.

**Comment by Paul-Licameli** [comment]
Sorry, this DOES depend on #5128 after all!

**Comment by Paul-Licameli** [comment]
Rebased unchanged onto updated #5128

**Review by crsib — APPROVED** [review]
I feel that `FindChannelGroup` is a bit confusing, but I can't think of a better name anyway.

**Comment by Paul-Licameli** [comment]
> I feel that `FindChannelGroup` is a bit confusing, but I can't think of a better name anyway.

Elsewhere I have use the convention that “Find” functions can return null pointers (as stl containers may give you end iterators) but “Get” functions can’t fail and return references.

Any better idea?

**Comment by dozzzzer** [comment]
Tested:
- #5127 fix
- Realtime effects stickiness, persistency
- Rendering with realtime effects
- Playback with RT effects
- Undo/Redo for RT effects

**Pull request merged**
