### PR TITLE
Effect latency preliminaries

### PR DESCRIPTION
**Pull request by Paul-Licameli**
First steps toward latency correction in realtime effects, change no behavior yet

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by crsib** [comment]
While looking into this PR I found a P1 in VST3 in master as it seems :-(
image

**Comment by Paul-Licameli** [comment]
> While looking into this PR I found a P1 in VST3 in master as it seems :-(
> image

You may have discovered and example of a bug I suspected might happen, and I asked @Ryan-Miller-Audacity to find an example with free plug-ins.  And I think, @vsverchinsky , this example is why the implementation of VST3 statelesness can't just skip the problem of "slave" processors.

**Comment by Paul-Licameli** [comment]
@crsib besides this incidental discovery of a bug in VST3, do I have an approval of these preliminaries for the latency problem?

**Comment by crsib** [comment]
Not yet, sorry. I stuck on the first commit around 1 am, found a bug and decided that it was quite enough for one day xD

**Review by crsib — APPROVED** [review]

**Pull request merged**
