### PR TITLE
Extract lib label track

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #5446

A toolkit neutral library for label tracks, including their import and export, but none of the graphics.

Also:  move mutable display related fields out of LabelStruct, like what was done in #4364 

Also:  fix two places that improperly mutated layout information during drawing.  Better to keep layout update separate from painting.

QA:  test label creation, editing, import and export;  test again, creation of labels for Find Clipping and Vamp analyzers

Test changes of label font propagate correctly

Test that updates of label box widths for change of text are correct, with various fonts

Confirm this old bug fix persist:  When a label is not a point, then its start and end verticals are at least one pixel distant, even zoomed out

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by crsib** [comment]
Does it block #1627? It waits for review for a really unreasonable amount of time now.

**Comment by Paul-Licameli** [comment]
> Does it block #1627? It waits for review for a really unreasonable amount of time now.

I just tried to rebase the single commit in that PR onto this one, and there was only one easy conflict in the `#include` lines at top.

That one is itself not blocking anything.

**Review by vsverchinsky — APPROVED** [review]

**Comment by Paul-Licameli** [comment]
@vsverchinsky thanks for the review, but more commits will be pushed onto this.  It's incomplete.

**Comment by Paul-Licameli** [comment]
This is a draft until I review #1627 and see if I can resolve conflicts with that

**Pull request closed without merging**
