### PR TITLE
Compile Audacity for Windows with CYGWIN and MINGW

### PR DESCRIPTION
**Pull request by carlo-bramini**
Hello,
I did some fixes for adding support for Windows to the autoconf scripts.
After applying the fixes in this PR, it will be possible to compile all sources of Audacity with CYGWIN.
Unfortunately, it prints these messages when doing the final linking:

```
../lib-src/portmixer/src/.libs/libportmixer.a(libportmixer_la-px_win_endpoint.o)
: In function `open_ep_mixers':
/home/Carlo/a/lib-src/portmixer/src/../../../../org/audacity/lib-src/portmixer/src/px_win_endpoint.c:103: undefined reference to `_imp__CoCreateInstance@20'
/home/Carlo/a/lib-src/portmixer/src/../../../../org/audacity/lib-src/portmixer/src/px_win_endpoint.c:163: undefined reference to `_imp__CoTaskMemFree@4'
/home/Carlo/a/lib-src/portmixer/src/../../../../org/audacity/lib-src/portmixer/src/px_win_endpoint.c:139: undefined reference to `_imp__CoTaskMemAlloc@4'
/home/Carlo/a/lib-src/portmixer/src/../../../../org/audacity/lib-src/portmixer/src/px_win_endpoint.c:163: undefined reference to `_imp__CoTaskMemFree@4'
/home/Carlo/a/lib-src/portmixer/src/../../../../org/audacity/lib-src/portmixer/src/px_win_endpoint.c:197: undefined reference to `_imp__CoTaskMemAlloc@4'
/home/Carlo/a/lib-src/portmixer/src/../../../../org/audacity/lib-src/portmixer/src/px_win_endpoint.c:221: undefined reference to `_imp__CoTaskMemFree@4'
/home/Carlo/a/lib-src/portmixer/src/../../../../org/audacity/lib-src/portmixer/src/px_win_endpoint.c:221: undefined reference to `_imp__CoTaskMemFree@4'
../lib-src/portmixer/src/.libs/libportmixer.a(libportmixer_la-px_win_endpoint.o)
: In function `open_ep_mixers_byid':
/home/Carlo/a/lib-src/portmixer/src/../../../../org/audacity/lib-src/portmixer/src/px_win_endpoint.c:258: undefined reference to `_imp__CoCreateInstance@20'
../lib-src/libnyquist/libnyquist.a(sndread.o):sndread.c:(.text+0x36f): undefined reference to `sf_open'
../lib-src/libnyquist/libnyquist.a(sndread.o):sndread.c:(.text+0x384): undefined reference to `sf_strerror'
../lib-src/libnyquist/libnyquist.a(sndwritepa.o):sndwritepa.c:(.text+0x405): undefined reference to `Pa_WriteStream'
../lib-src/libnyquist/libnyquist.a(sndwritepa.o):sndwritepa.c:(.text+0x887): undefined reference to `sf_open'
../lib-src/libnyquist/libnyquist.a(sndwritepa.o):sndwritepa.c:(.text+0xa46): undefined reference to `sf_open'
../lib-src/libnyquist/libnyquist.a(sndwritepa.o):sndwritepa.c:(.text+0xa7f): undefined reference to `sf_error'
../lib-src/libnyquist/libnyquist.a(sndwritepa.o):sndwritepa.c:(.text+0xa87): undefined reference to `sf_error_number'
../lib-src/libnyquist/libnyquist.a(sndwritepa.o):sndwritepa.c:(.text+0xc18): undefined reference to `sf_open'
../lib-src/libnyquist/libnyquist.a(sndwritepa.o):sndwritepa.c:(.text+0x14e6): undefined reference to `Pa_WriteStream'
../lib-src/libnyquist/libnyquist.a(sndwritepa.o):sndwritepa.c:(.text+0x1bbe): undefined reference to `Pa_WriteStream'
../lib-src/portmidi/libportmidi_s.a(ptwinmm.o):ptwinmm.c:(.text+0x49): undefined reference to `_imp__timeBeginPeriod@4'
../lib-src/portmidi/libportmidi_s.a(ptwinmm.o):ptwinmm.c:(.text+0x5b): undefined reference to `_imp__timeGetTime@0'
../lib-src/portmidi/libportmidi_s.a(ptwinmm.o):ptwinmm.c:(.text+0xa4): undefined reference to `_imp__timeSetEvent@20'
../lib-src/portmidi/libportmidi_s.a(ptwinmm.o):ptwinmm.c:(.text+0xfa): undefined reference to `_imp__timeKillEvent@4'
../lib-src/portmidi/libportmidi_s.a(ptwinmm.o):ptwinmm.c:(.text+0x12a): undefined reference to `_imp__timeEndPeriod@4'
../lib-src/portmidi/libportmidi_s.a(ptwinmm.o):ptwinmm.c:(.text+0x14b): undefined reference to `_imp__timeGetTime@0'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x7): undefined reference to `_imp__midiInGetNumDevs@0'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x5e): undefined reference to `_imp__midiInGetDevCapsA@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xdb): undefined reference to `_imp__midiInGetDevCapsA@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x125): undefined reference to `_imp__midiOutGetNumDevs@0'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x17c): undefined reference to `_imp__midiOutGetDevCapsA@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x1f7): undefined reference to `_imp__midiOutGetDevCapsA@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x32a): undefined reference to `_imp__midiInGetErrorTextA@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x3c7): undefined reference to `_imp__midiOutGetErrorTextA@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x71c): undefined reference to `_imp__midiInPrepareHeader@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x75b): undefined reference to `_imp__midiInAddBuffer@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x8b8): undefined reference to `_imp__midiInOpen@20'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x917): undefined reference to `_imp__midiInStart@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x942): undefined reference to `_imp__midiInReset@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x957): undefined reference to `_imp__midiInClose@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x99d): undefined reference to `_imp__midiInGetErrorTextA@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xa20): undefined reference to `_imp__midiInStop@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xa40): undefined reference to `_imp__midiInReset@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xa52): undefined reference to `_imp__midiInClose@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xa66): undefined reference to `_imp__midiInReset@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xa86): undefined reference to `_imp__midiInClose@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xa9a): undefined reference to `_imp__midiInClose@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xaf2): undefined reference to `_imp__midiInGetErrorTextA@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xcac): undefined reference to `_imp__midiInPrepareHeader@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xcf8): undefined reference to `_imp__midiInAddBuffer@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xd59): undefined reference to `_imp__midiInUnprepareHeader@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xe20): undefined reference to `_imp__midiStreamPosition@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0xfd7): undefined reference to `_imp__midiOutOpen@20'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x1015): undefined reference to `_imp__midiStreamOpen@24'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x10c4): undefined reference to `_imp__midiStreamProperty@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x1105): undefined reference to `_imp__midiStreamProperty@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x114c): undefined reference to `_imp__midiStreamRestart@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x1180): undefined reference to `_imp__midiOutClose@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x11c6): undefined reference to `_imp__midiOutGetErrorTextA@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x12ec): undefined reference to `_imp__midiOutClose@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x1305): undefined reference to `_imp__midiStreamClose@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x1340): undefined reference to `_imp__midiOutGetErrorTextA@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x13b0): undefined reference to `_imp__midiStreamStop@4'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x143b): undefined reference to `_imp__midiOutPrepareHeader@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x149e): undefined reference to `_imp__midiOutLongMsg@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x14cc): undefined reference to `_imp__midiStreamOut@12'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x1574): undefined reference to `_imp__midiOutShortMsg@8'
../lib-src/portmidi/libportmidi_s.a(pmwinmm.o):pmwinmm.c:(.text+0x1961): undefined reference to `_imp__midiOutUnprepareHeader@12'
collect2: error: ld returned 1 exit status
```

This happens because portmidi, portmixer and libnyquist need to be linked with some extra libraries and it does not seem that they could be added in the current state.
I think that the most effective way is to migrate also those libraries to libtool.
In this way, the required libraries for Windows, but it may be applied also to other platforms, will be included and the link will succeded.
However, this seems to be a bit more invasive change, so I provided these first simple changes for starting.
I hope that you could give me your opinion for these changes.
These fixes cover also some parts of the MINGW port, but more are required, here I isolated the ones that made a working Audacity with CYGWIN.

Sincerely.

### CODE REVIEW

**Comment by Pokechu22** [comment]
Thanks for this PR.  It would probably be a good idea to talk about it more on [the audacity-devel mailing list](https://sourceforge.net/projects/audacity/lists/audacity-devel).

I've never attempted to build audacity in cygwin and I haven't attempted to build on linux in quite some time, so I can't say too much about your actual changes.  However, I do know that there has been [some recent work by krokoziabla](https://github.com/audacity/audacity/pulls?q=is%3Apr+author%3Akrokoziabla) to build with cmake.  I don't know much about it, just that it's been worked on; I'm sure some of the other people on audacity-devel know more.

**Comment by carlo-bramini** [comment]
Sorry, I noticed immediately after I did the PR that portmixer already uses libtool.
So I added the missing `-lole32` to `LIBADD` and now portmixer does not give linking errors anymore.
portmidi and libnyquist are the only one left with this issue.

Sincerely.

**Comment by carlo-bramini** [comment]
I have seen that the travis  ci build failed with this message:

```
../../../lib-src/portmidi/pm_linux/pmlinuxalsa.c: In function ‘alsa_write_byte’:
../../../lib-src/portmidi/pm_linux/pmlinuxalsa.c:204:32: error: too many arguments to function ‘Pt_Time’
                                Pt_Time(NULL));
                                ^
In file included from ../../../lib-src/portmidi/pm_linux/pmlinuxalsa.c:16:0:
../../../lib-src/portmidi/porttime/porttime.h:79:22: note: declared here
 PMEXPORT PtTimestamp Pt_Time(void);
                      ^
make[2]: *** [pmlinuxalsa.o] Error 1

```
which happens after a change that I did in the sources.
Actually, after searching inside the sources, Pt_Time() function is called with and without parameter in some files. What is the correct usage to assume?

**Comment by JamesCrook** [comment]
Please introduce yourself on the audacity devel mailing list and tell us also why YOU are  wanting to build with Cygwin and MinGW on Windows (and not using MSVC).  Why would WE want to support an additional way to build?

**Comment by JamesCrook** [comment]
Thanks.  We decided not to pull this.  We don't officially support cross compilation and don't have man/woman-power to maintain it.

**Comment by carlo-bramini** [comment]
> Thanks. We decided not to pull this. We don't officially support cross compilation and don't have man/woman-power to maintain it.

Thank you for your reply.
I understand the reasons for not pulling this.
However, I was wondering if somebody could evaluate at least the two litte fixes that I made to  `lib-src/libnyquist/nyx.c`  and `src/AudacityApp.cpp`, because IMO those lines were bugged.
I can do a separate PR if you think that they could be accepted.

Sincerely.

**Comment by JamesCrook** [comment]
Yes, if those are bugs please provide as a separate pull request.
Probably we will pull them just after we release 2.3.3 which is planned for one week's time.

You may be interested that we have a project to get CMake working on Linuux, Windows and Mac, and we hope to get this done for 2.4.0 (the release after 2.3.3).

**Pull request closed without merging**
