### PR TITLE
5397 fix sbsms integration

### PR DESCRIPTION
**Pull request by saintmatthieu**
Resolves: #5397

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by crsib** [comment]
Please rebase this branch on `release-3.4.0`

**Review by crsib — APPROVED** [review]
I do approve the fix, but it should not be merged before rebasing on the release branch

**Comment by crsib** [comment]
Still not there. You should have one commit, you have 2 now, first comes from the master and bumps the version to 3.5.0

**Comment by saintmatthieu** [comment]
> Still not there. You should have one commit, you have 2 now, first comes from the master and bumps the version to 3.5.0

Oj ...

**Comment by crsib** [comment]
Parfait!

**Comment by dozzzzer** [comment]
Tested

**Pull request merged**
