### PR TITLE
fix Linux packaging

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #6258

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by crsib** [comment]
I don't quite understand why this fix works TBH

**Comment by Paul-Licameli** [comment]
> I don't quite understand why this fix works TBH

I don’t know whether it works.

the Linux packaging that failed is not tested in PRs before merge.

**Comment by crsib** [comment]
The packaging job should run in your actions (if you have them enabled)

**Comment by crsib** [comment]
And it has failed - https://github.com/Paul-Licameli/audacity/actions/workflows/package_linux.yml

I can take a look Friday I think

**Comment by Paul-Licameli** [comment]
Revert my contribution if that is easiest

**Comment by Paul-Licameli** [comment]
It is just certain Gcc versions that interpret # include directives wrong?

**Comment by LWinterberg** [comment]
FWIW: There is no sync/ProjectUploadOperation.h in **modules**/sharing/mod-cloud-audiocom/. There is one though in **libraries**/lib-cloud-audiocom/ though.

**Comment by crsib** [comment]
I will not approve this change.

**Comment by crsib** [comment]
The problem with the Linux build is very simple, I overlooked a detail during the code review, and the audio com module is enabled unconditionally, which is wrong.

**Comment by Paul-Licameli** [comment]
> The problem with the Linux build is very simple, I overlooked a detail during the code review, and the audio com module is enabled unconditionally, which is wrong.
> 
> I will push the fix (and one more fix for GCC13) soon

OK

Messages crossed:  see my latest small commit.

Is that all that is really necessary?

**Comment by Paul-Licameli** [comment]
> > The problem with the Linux build is very simple, I overlooked a detail during the code review, and the audio com module is enabled unconditionally, which is wrong.
> > I will push the fix (and one more fix for GCC13) soon
> 
> OK
> 
> Messages crossed: see my latest small commit.
> 
> Is that all that is really necessary?

Answering myself:  I did not reproduce #6261, but I think I did make a separate fix that is desirable.

**Comment by crsib** [comment]
There is one more needed for GCC 13, I will merge it into the release first, and merge the release into the master right after

**Comment by Paul-Licameli** [comment]
Please do consider https://github.com/audacity/audacity/pull/6256/commits/8613d62de25e3345b5c6df55800a9ef0bd94f1d3

**Review by crsib — APPROVED** [review]

**Comment by Paul-Licameli** [comment]
Straight to merge then?

I apologize for the invconvenience I made.

**Comment by crsib** [comment]
> Straight to merge then?

Yep

> I apologize for the invconvenience I made.

No problems :-)

**Pull request merged**
