### PR TITLE
Fixes crashreporter installation on Linux

### PR DESCRIPTION
**Pull request by crsib**
Resolves: #4629 

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by vsverchinsky — APPROVED** [review]

**Comment by haleba-hotmail** [comment]
@crsib

Where can the fixed AppImage be downloaded?

Thanks

**Comment by applecuckoo** [comment]
Buildfile is at https://github.com/audacity/audacity/suites/12648574392/artifacts/677785394.

**Comment by applecuckoo** [comment]
No, it's an automatically built AppImage from GitHub Actions. You should be able to go [here](https://github.com/audacity/audacity/actions/workflows/build.yml), click on anything from `release-3.3.2`, then just scroll all the way down until you find the third file in the artifact list. Hope this helps!

**Comment by haleba-hotmail** [comment]
@applecuckoo 

Thanks.

Looks like Audacity 3.1.3 is the last version that can run in Ubuntu 18.04: still getting the glibc errors. Glibc versions 2.29+ are not available from the Bionic repository.

I was able to compile glibc 2.29 from source and installed it to /opt so it wouldn't step on anything that used an older version, but don't know how to "point" Audacity at it, since it is hared-coded to look in /lib/x86_64-linux-gnu:

    ./audacity-linux-3.3.2-x64.appimage     
    /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0
    /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0
    /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2
    /usr/lib/x86_64-linux-gnu/libcairo.so.2
    /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
    /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
    /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0
    /usr/lib/x86_64-linux-gnu/libjack.so.0
    findlib: libportaudio.so: cannot open shared object file: No such file or directory
    /home/barry-u/AppImages/audacity-linux-3.3.2-x64.appimage: Using fallback for library     'libportaudio.so'
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/bin/audacity)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/lib-project-file-io.so)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/libgtk-x11-2.0.so.0)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/lib-audio-io.so)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/lib-track.so)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/lib-numeric-formats.so)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/lib-math.so)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/libmpg123.so.0)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/libsndfile.so.1)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/libvorbis.so.0.4.9)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/libFLAC.so.8)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/fallback/libportaudio.so/libportaudio.so)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/libpng16.so.16)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/libopus.so.0)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/libpixman-1.so.0)
    /tmp/.mount_audaciJ1jYnn/bin/audacity: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not     found (required by /tmp/.mount_audaciJ1jYnn/lib/libselinux.so.1)

Look like I needed glibc 2.30 anyway.

Audacity 3.1.3 is working OK, so guess I'll just have to stick with that until I get around to upgrading to 22.04 LTS.

**Pull request merged**
