### PR TITLE
Issue #4487 : Saving project vs exporting audio

### PR DESCRIPTION
**Pull request by aniruddhJo**
Resolves: #4487

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

Image For Changes:-

image

### CODE REVIEW

**Review by LWinterberg — APPROVED** [review]
no objection from me

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @aniruddhJo 's branch build:

This change looks fine to me .

@LWinterberg can we possibly get it pulled into master or even 3.3.0?

image

**Comment by crsib** [comment]
We are already receiving translations, so I would say no.

**Comment by LWinterberg** [comment]
This one is targeted at master, not release. It definitely doesn't go into 3.3.

**Comment by petersampsonaudacity** [comment]
BUMP

**Comment by petersampsonaudacity** [comment]
Further BUMP

@LWinterberg @crsib 

Any chance we can get this pulled into master for 3.4.0 please?

**It is a mere couple of very straightforward string changes ...**

**Pull request merged**
