### PR TITLE
Bug 1402

### PR DESCRIPTION
**Pull request by tip2tail**
Rewrite logic for the display of hours and minutes in status bar and dialog and ensure we use one routine for this.

### CODE REVIEW

**Comment by JamesCrook** [comment]
_("%d %s and %d %s.") must have a translation hint.  A translator will not have a clue what is being translated otherwise.

**Comment by tip2tail** [comment]
Hi James,

Just to clarify you mean have a comment above this line indicating an
example of the English text here?

Thanks,
Mark

**Comment by windinthew** [comment]
Hi Mark,

I believe you should format the hint such as in this example so it will show up in poedit and other tools:

/* i18n-hint: A time in hours and minutes. Only translate the "and". */

**Comment by JamesCrook** [comment]
Merged into audacity:master,

**Pull request closed without merging**
