### PR TITLE
Add an option to skip plugin scanning

### PR DESCRIPTION
**Pull request by vsverchinsky**
Resolves: #4923

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by crsib** [comment]
Can you please add the checkbox to the scan dialog as well?

**Comment by LWinterberg** [comment]
ah, I hadn't thought of putting it there as well, but I support that idea.

**Comment by crsib** [comment]
> ah, I hadn't thought of putting it there as well, but I support that idea.

It was so natural for me that I forgot about mentioning it xD

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @crsib 's latest branch build for this:  audacity-win-3.5.0-alpha-20240213+cf42988-x64

This seems to be working properly.

I note the new checkbix in Effects prefs to turn off plugin scanning.

1. On my initial run of this branch my plugins got scaneed
2. I then set the new no-scanning checkbox to "on"
3. deleted the plugins cfg files from the audacirt settings folder
4. relaunched 
5. Observe: my plugins were not scanned and not available
6. reset the no-scanning to be "off"
7. relaunched
8. Observe: my plugins were scanned and made available

**Comment by LWinterberg** [comment]
The exact nature of the in-scan-dialog checkbox has led to some discussion in the design team which is unresolved as of now, please move this PR forward as-is.

**Review by crsib — APPROVED** [review]

**Comment by crsib** [comment]
Please open up a task related to it @LWinterberg

**Pull request merged**
