### PR TITLE
Fix for bug 683

### PR DESCRIPTION
**Pull request by SteveDaulton**
Also adds "m" prefix to some member variables for consistency.

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Steve, James has cleaned up the recent tangle in repository history, but it is still in the ancestry of your commit, which is why I see 36 commits above, many of them extraneous.  Can you rebase your changes on the new cleaned up master branch?

**Comment by SteveDaulton** [comment]
Are there instructions for how to do that?

**Comment by Paul-Licameli** [comment]
I am not exactly sure how to advise Steve to do rebase in detail, because I
have not succeeded with it yet.  We are all learning this...

I think what you want to do is make sure you have done

git remote add audacity git@github.com:audacity/audacity.git
git fetch audacity/master

That mirrors the cleaned up branch for you locally.  And then, to take just
your last three commits that I see in your master,

git checkout master
git rebase --onto remotes/audacity/master HEAD~3

(I am not sure whether you really need the "remotes/" part)

If that fails, you may need git rebase --abort to get back to a good state,
but if it works, you may need -f to push to your master and lose the old
tangled up master:

git push -f origin master

Reference:
http://git-scm.com/docs/git-rebase

**Comment by lllucius** [comment]
Be careful though.  Somewhere along the line I wound up rebasing my entire repo and lost the 3 branches I had there.  Wasn't a biggie...I just recreated them (well, all but 1 so far).

**Comment by Paul-Licameli** [comment]
I understand git reflog may help you rediscover "lost" branches, or
"dangling commits," which are not reachable from any branch head.

**Comment by Paul-Licameli** [comment]
An alternative to rebase is the "cherry-pick" command which lets you
re-apply one diff at a time elsewhere in the graph.

**Comment by lllucius** [comment]
Well, both of those options would have been handy.  :-)  But, I just went with recreating the branches as it was pretty easy to do.

Thanks,

Leland

**Comment by SteveDaulton** [comment]
On 8 April 2015 at 04:20, Leland Lucius <notifications@github.com> wrote:

> Be careful though. Somewhere along the line I wound up rebasing my entire
> repo and lost the 3 branches I had there. Wasn't a biggie...I just
> recreated them (well, all but 1 so far).
>
Thanks for the warning but it's hard to "be careful" when I don't know what
I'm doing :-)


What happened here?
Was it  that:
The audacity/audacity repository became messed up, causing all other forks
to be messed up, and now the audacity/audacity master has been "cleaned",
commits from forks will mess it up again?

Would it be better if I deleted my fork and used SVN for now?

Steve

**Comment by lllucius** [comment]
If it's easy to redo your changes, then do what I did.  It was an accident for me, but it worked.  :-)  You could delete your fork:

https://help.github.com/articles/deleting-a-repository/

Then just fork again and reapply your change.

**Comment by SteveDaulton** [comment]
I've deleted my repository and will start again.

**Comment by Paul-Licameli** [comment]
Sorry for the grief.

The problem was that audacity/master got messy, and the mess was reverted
and replaced with equivalent code changes but a neater history.  We need to
base further changes on the new history to avoid merging the messy parts
back in again.

git rebase is supposed to make that sort of thing easy -- picking up a
branch you have not yet pushed, and moving it elsewhere in the graph.  I
made my first successful use of that command today.

**Comment by lllucius** [comment]
Oh no...not a big deal.  The more we play/learn at the beginning, the better off we'll be later.

**Comment by Paul-Licameli** [comment]
Here's another discovery:  if I rebase a banch that I already pushed to my
remote, public sandbox (not to audacity), then I need the -f (force) option
to push it again.  Else it complains that the branch on the remote is not
upstream of the branch I am pushing.

**Comment by JamesCrook** [comment]
Paul, yes.  After a rebase you have 'rewritten history' and a push of the local branch that is tracking a remote branch will need a -f. 

We should avoid doing push -f to audacity/audacity as that could/will overwrite changes already made by someone else.  In your own repo it is just fine.

Also if you have done a push -f, and then make further changes on your branch and push again, you don't need a -f the second time (unless you've also rebased again).  The history matches, so there is no rewriting of history to do.

**Pull request closed without merging**
