### PR TITLE
Audacity does not depend on lib-cloud-audiocom

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by crsib** [comment]
ATM Audacity must depend on lib-cloud-audiocom. It should probably be reworked in a different way, but not right now. 

You can see the usage of HAS_AUDIOCOM_UPLOAD in ToolManager.cpp

**Comment by Paul-Licameli** [comment]
`DefaultConfigTable` wants to become a scattered registry but that work isn't done

**Comment by crsib** [comment]
`HAS_AUDIOCOM_UPLOAD` changes the visible behavior.

**Comment by Paul-Licameli** [comment]
> `HAS_AUDIOCOM_UPLOAD` changes the visible behavior.

That does not prove that this change is incorrect.  But I'll drop it.

**Comment by crsib** [comment]
This change results in a bug: https://github.com/audacity/audacity/issues/5966

**Comment by Paul-Licameli** [comment]
> This change results in a bug: #5966

Ah, now I see it.

Still this could be fixed with some other lines of Cmake language.

**Pull request closed without merging**
