### PR TITLE
Unlink mismatched channels in wave tracks

### PR DESCRIPTION
**Pull request by vsverchinsky**
Problem description: user cannot open project that has stereo tracks with mismatched sample format/rate.
Solution: unlink channels, preserving rate/format for individual channel and remove the effect stack. Changes should not be applied unless project is explicitly saved by user, user should be warned about changes.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

QA list is similar to one in #5202, but here mismatch can be either by clip boudaries, sample rate or sample format, or any combination of them (but it will be enough to check each of them separately):
 - [x] Verify opening of a properly saved project that contains mismatches:
   - [x] Shows warning dialog with the message explaining the reason to split tracks
   - [x] Stereo wave tracks that has mismatches are split into two mono tracks
   - [x] These tracks have empty effects stack
   - [x] Splited tracks preserve their initial rate and sample format
   - [x] Other tracks are not affected (mono wave tracks, label tracks etc.)

### CODE REVIEW

**Review by Paul-Licameli — APPROVED** [review]

**Comment by Paul-Licameli** [comment]
Approved.  I assume this PR should be on the main board with 3.4 milestone?  I made it so.

**Comment by chinakov** [comment]
@vsverchinsky has mentioned that he'd like to advise someone in regards to the splitting of tracks to L-R channels, waiting for info regarding this, and then will close this ticket.

@vsverchinsky suggests that the split stereo tracks should be sent to Left and Right channels respectively on each resulting mono channel.

**Comment by LWinterberg** [comment]
Yes, the resulting mono tracks should be hard panned L/R

**Comment by chinakov** [comment]
Yes, the panning works now. Thanks!

**Pull request merged**
