### PR TITLE
Changed string part from warning to information

### PR DESCRIPTION
**Pull request by Dhriti03**
Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [ ] Each commit's message describes its purpose and effects
- [ ] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by LWinterberg** [comment]
Is this supposed to resolve #2588? If so, it changes the text near the checkbox but not the window title.

**Comment by Dhriti03** [comment]
> Is this supposed to resolve #2588? If so, it changes the text near the checkbox but not the window title.

So isn't it like the line number 55 was dedicated for the text near the  checkbox and line 62 for the window title

**Comment by LWinterberg** [comment]
Ah, sorry, I misread. What you're doing here is you're changing *all* warnings to say Information. However, the bug is only one specific case.

**Comment by Dhriti03** [comment]
So which means I need to have a soft code for warning part to be converted to information with a condition statement  and having a string variable representing that string of warning is it ....wrt the class ...........please correct me with this ..

**Pull request closed without merging**
