### PR TITLE
Update cs.po - second attemt

### PR DESCRIPTION
**Pull request by pafri**
After fixing some issues in some strings (see the request "Update cs.po #3928") I make the new request.

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [ ] Each commit's message describes its purpose and effects
- [ ] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by LWinterberg — APPROVED** [review]
thank you!

**Comment by LWinterberg** [comment]
ah, one more request: Can you rebase this PR to the release-3.2.3 branch and rebase (and then force-push)? That way, it can get merged into the very next release

**Comment by Gootector** [comment]
Thank you and f* U - not merged with 3.2.3.

**Comment by crsib** [comment]
It had no strings related to 3.2.3. 

Please mind your language.

**Comment by Gootector** [comment]
My language is OK - "f*" is just "f*". I see many updated strings in this PR, but I think that @pafri didn't sign CLA and this is the problem with merging.

**Comment by LWinterberg** [comment]
The problem was that this PR wasn't based on 3.2.3, @Gootector

**Comment by Gootector** [comment]
@LWinterberg & @crsib - OK, fine. I'll check this Czech translation in my free time and copy/paste to PO file in the master repo. OK?

**Comment by pafri** [comment]
It seems, that Audacity 3.2.4 doesn´t contain any translation update. Where is the problem?

**Comment by LWinterberg** [comment]
I believe the changes here have made it into Audacity in a different PR. In each case the files here are now conflicting.

**Pull request closed without merging**
