### PR TITLE
Fix bug dragging a clip into a track with a different rate

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #4808

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch build:  audacity-win-3.4.0-alpha-20230621+140ef2c-x64

I confirm that this now works fine once again with this branch build on Windows 10

**Review by saintmatthieu — APPROVED** [review]
This obviously fixes this bug, but I still have a bad feeling about `mLegacyRate` also used as argument to `SetClipRates` without this greater-than-zero check. Please review that place and consider adding this check there too.

**Comment by Paul-Licameli** [comment]
> `mLegacyRate`

That would be a one line fix and I will do it

**Comment by Paul-Licameli** [comment]
Rebased onto recent master, and added the suggested additional check for zero.

**Pull request merged**
