### PR TITLE
export dialog: center and max width

### PR DESCRIPTION
**Pull request by LWinterberg**
Resolves: #5515
Resolves: #5884

hey look it's the same PR again but for a different dialog and limiting the exciting direction of X this time instead of Y. 

It's intentional that the thing is not centered for the updates; the window should just extend downwards instead of shifting position to stay centered.

### CODE REVIEW

**Comment by LWinterberg** [comment]
Actually, looking at it in practice I think I just want to set a simple max size for this thing and not allow it to stretch all across the screen.

**Comment by vsverchinsky** [comment]
> Actually, looking at it in practice I think I just want to set a simple max size for this thing and not allow it to stretch all across the screen.

@LWinterberg 
Export editor UI is also present in Timer Record dialog.
In that particular case limiting the maximum width of the dialog may not look good with some translations, I think. If so, maybe the constraints could be set on `wxComboBox` that is created in `ExportOptionsCLEditor`?

**Review by vsverchinsky — APPROVED** [review]

**Comment by GermanKiwi** [comment]
Hi @LWinterberg, does this patch mean the Export dialog will now always be centered in the middle of the Audacity window - just as the Preferences dialog already is?

The reason this is important for me, is because I always keep Audacity maximised on my screen, and I have a large 32-inch 4K monitor, and it's harder to interact with the Export dialog when it always opens up in the top-left corner of the screen, rather than in the center, directly in front of my eyes. :)

**Comment by LWinterberg** [comment]
> Hi @LWinterberg, does this patch mean the Export dialog will now always be centered in the middle of the Audacity window - just as the Preferences dialog already is?

That indeed would be the case yes.

Let me know if you see other dialogs which don't open up in the center - the fix for these is quite easy.

**Pull request merged**
