### PR TITLE
Adds FR comment to audacity.desktop.in

### PR DESCRIPTION
**Pull request by trebmuh**
... and remove unnecessary duplication of the name (no needs to override the original name if it doesn't change when translated).

### CODE REVIEW

**Comment by trebmuh** [comment]
ping ?

**Comment by trebmuh** [comment]
Ping, any issue with this pull request maybe ?

**Comment by trebmuh** [comment]
ping ?

**Comment by windinthew** [comment]
This seems a good change and in accordance with the "Desktop Entry Specification" at  https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html .

Anyone think not?

**Comment by windinthew** [comment]
Committed at https://github.com/audacity/audacity/commit/145a54d .

**Comment by trebmuh** [comment]
Sweet, thanks.

**Pull request closed without merging**
