### PR TITLE
The end of audacity.h

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Remove the old Audacity.h header file...
    
... instead, do all that it did either with macros in header files of more
limited use, or in CMake where there are declarations that really must be
pervasive.
    
This will be a useful preliminary for later refactoring work to make separate
libraries.
    
See also commit 19312e4 where similar was done for Experimental.h.

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
> Would it make sense to rename this file? With the inclusion of macros like MAX_AUDIO, it isn't really about Memory any more?

I agree maybe not the best new home for the macros, but it was an expedient to help the main thing of this branch, elimination of another header.

MemoryX.h began a miscellany of old stuff to accommodate certain compilers and imperfect C++ standard library implementations,  that should go away with better standard implementations.

**Comment by Be-ing** [comment]
I recommend to incorporate the output of `git describe` in the GUI and logs so it is easy for developers to know exactly what code users are running. We have been working towards this on Mixxx.

cc @Holzhaus and @daschuer

**Comment by Paul-Licameli** [comment]
> I recommend to incorporate the output of `git describe` in the GUI and logs so it is easy for developers to know exactly what code users are running. We have been working towards this on Mixxx.
> 
> cc @Holzhaus and @daschuer

I won’t comment on the merits of the suggestion, but I think it is not directly relevant to review of this pull request.

**Comment by lllucius** [comment]
> 
> 
> I recommend to incorporate the output of `git describe` in the GUI and logs so it is easy for developers to know exactly what code users are running. We have been working towards this on Mixxx.
> 
> cc @Holzhaus and @daschuer

This is already being done.  Check the Commit ID in Help -> About Audacity -> Build Information.

**Review by lllucius — APPROVED** [review]

**Pull request merged**
