### PR TITLE
Add a set of patches to better support OpenBSD and FreeBSD

### PR DESCRIPTION
**Pull request by brad0**
```
- When dlopening libraries on OpenBSD we need to drop the major version
- OpenBSD does not have sys/timeb.h. Note this has been removed from POSIX.1-2008
- Correct the mistake with the FreeBSD symbol, it should be __FreeBSD__
```

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by brad0** [comment]
I can't sign the CLA. The URL does not work.

**Comment by LWinterberg** [comment]
> I can't sign the CLA. The URL does not work.

thanks for that, it should be fixed now. And thanks for the patch!

**Comment by brad0** [comment]
OK, signed the CLA.

**Review by crsib — APPROVED** [review]

**Comment by brad0** [comment]
Can this be back ported to the 3.4 branch?

**Pull request merged**
