### PR TITLE
Toolkit neutral menus part 2

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: *(direct link to the issue)*

Further changes after #4017 define a sufficient toolkit neutral interface for most uses of
toolbar and context menus.

That facade is not yet written with abstract base classes and injection of the toolkit-specific
implementation at startup.

The intent is to eliminate all but one use of wx/menu.h.  This is almost done here.

But see #4052.  This pull request does not yet remove wx/menu.h from AudioSetupToolbar,
which has many other (but unnecessary) uses of menus that were added after these
commits were drafted two years ago.  That pull request (based directly on current
master, not on #4017) does other rewriting first.

There are also still uses of wxEVT_MENU_OPEN, wxEVT_MENU_CLOSE, and wxEVT_MENU
to remove (these are defined not in wx/menu.h but in wx/event.h)

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by crsib — CHANGES_REQUESTED** [review]
After spending quite a lot of time going multiple times through this PR I am still very confused with naming used and with semantics behind those names. I think this is something that should be improved.

In the commit that introduces Handle it feels like some work is missing. `wxMenu` is used directly instead of Handle methods.

In general, I think that this is the case where we should separate the **definition** of menu and the toolkit specific code in two different layers instead of proposed `Handle` approach.

Consider pseudocode like

```
BasicMenu::Menu menu;

menu.Append(XO("No Effect"). []{})'
menu.AppendSeparator();
...

// wxMenu is only created here...
BasicMenu::Popup(menu);
```

I think it will simplify the lifetime management quite a bit.

**Comment by Paul-Licameli** [comment]
Wait!  You are reviewing the part 2 PR before part 1!

**Comment by Paul-Licameli** [comment]
I order the PRs in the column of the project board to show which I want reviewed sooner.

**Comment by crsib** [comment]
I am reviewing both because Part 1 makes very little sense to me by itself. I wanted to see if further work will clarify my previous confusions - it did not.

**Pull request closed without merging**
