### PR TITLE
PortMIDI build changes + use Pa_GetStreamTime instead of PaUtil_GetTime

### PR DESCRIPTION
**Pull request by Pokechu22**
These changes adjust building, fix a few compile errors when features are disabled, and most importantly, switches to `Pa_GetStreamTime` instead of `PaUtil_GetTime`.

<dl>
<dt>1d32b0306 &mdash; Fix PortMidi automake files and update PortMidi's m4</dt>
<dd>Corrections of some typos and other mistakes needed to use includes correctly that I made earlier.</dd>
<dt>ed5bc5b04 &mdash; Include headers via automake instead of via hardcoded paths</dt>
<dd>Replaces e.g. <code>#include "../lib-src/portmidi/pm_common/portmidi.h"</code> with just <code>#include "portmidi.h"</code>, which is possible due to the above change.</dd>
<dt>f5f29d886 &mdash; Manually regenerate windows and mac configs</dt>
<dd>I manually updated the mac and windows configs to match the new template (which was generated in the first commit) - they were both missing <code>USE_PORTMIDI</code>.</dd>
<dt>0495ed56d &mdash; Check for both <code>USE_MIDI</code> and <code>USE_PORTMIDI</code> for <code>EXPERIMENTAL_MIDI_OUT</code></dt>
<dd>Allows compiling <code>--without-portmidi</code> without manually editing <code>Experimental.h</code>.</dd>
<dt>0c51ba734 &mdash;  Fix more missing checks for USE_MIDI</dt>
<dd>Adds more missing checks relating to USE_MIDI (those that were missed in #257 since they didn't break compilation).</dd>
<dt>ab9429c8a &mdash; Remove unused mAudioCallbackClockTime</dt>
<dd>Removes a now-unused field (and one use of <code>PaUtil_GetTime</code>).</dd>
<dt>21e55934d &mdash; Completely replace <code>PaUtil_GetTime</code> with <code>Pa_GetStreamTime</code></dt>
<dd>This change is probably the most important in terms of building.  It means that <code>PaUtil_GetTime</code> is no longer directly linked by audacity, which means that the <code>extern "C"</code> change in portaudio is no longer necessary (and thus system portaudio should be usable again!).</dd>
<dd>The change basically just uses <code>Pa_GetStreamTime</code> with <code>mPortStreamV19</code> &ndash; but since that requires a non-null stream, some logic needs to be reordered to ensure that the stream isn't <code>NULL</code>.</dd>
<dt>15f82ff &mdash; Check <code>USE_PORTMIDI</code> instead of <code>EXPERIMENTAL_MIDI_OUT</code> for MIDI device info</dt>
<dd>Since <code>USE_PORTMIDI</code> now exists, it makes more sense to use that to govern the MIDI device info option &ndash; especially since the option reports the status of that experimental flag.</dd>
</dl>

### CODE REVIEW

**Comment by Pokechu22** [comment]
Looks like I originally missed one case (MIDI import via drag-and-drop or File&rarr;Open).  Will squash.

A side effect of disabling MIDI import the way I did there is that the low quality FFMPEG MIDI (/mod) import applies.  Since this would only be when `USE_MIDI` is disabled (and thus there's no other way for it to import), that is fine, but it's worth noting.

**Comment by Pokechu22** [comment]
Seems stable enough from my testing, could maybe use some more but I think it's safe to no longer mark it as WIP.

Also went in and made a few small changes - using `wxASSERT_MSG` instead of just `wxASSERT` (for context), and using `USE_PORTMIDI` for MIDI device info.

**Comment by Pokechu22** [comment]
Rebased off of latest master.  The changes that were already made in #257 aren't included.

I haven't yet completely tested this for all build combos, currently doing that (but it takes a while since one of them involves building on my pi).

**Comment by Pokechu22** [comment]
Ah, glad I'm doing this testing, seems like I did actually make a mistake here, with the midi device info commit.  I only updated the defines for the definitions of the methods, not the ones in the headers.  Should be fixed now, still running the rest of the tests.

**Comment by Pokechu22** [comment]
Found another case where it was broken, `PlayableTrack::DoSetHeight(h);` in `NoteTrack::DoSetHeight` is incorrect when `EXPERIMENTAL_MIDI_OUT` is disabled as `NoteTrack` extends `AudioTrack` in that case, instead of `PlayableTrack`.

**Comment by Pokechu22** [comment]
Took a while, but all of the build configurations I listed above have succeeded.

**Comment by JamesCrook** [comment]
Thanks.  We've moved to CMake, so would now need different build changes for this.

**Comment by SteveDaulton** [comment]
> Is there a reason nobody reviewed this in 2.5 years

Probably because over the last 2.5 years there has been so many things that 'must' be done, and so few people to do them, that many things that 'should' be done don't get done. Hopefully that will improve in the future.

**Pull request closed without merging**
