### PR TITLE
Code cleanup: removed the old real FFT code not used for a long time

### PR DESCRIPTION
**Pull request by RaphaelMarinier**
Hi Audacity developers,

I have an idea for an Audacity plugin (I will share details in the ML) and to familiarize myself with the codebase I thought I could start by doing a small cleanup.

In this pull request, I remove the old real FFT code that hasn't been used since 2009 (and checked that the current real FFT code is faster than the old one - see first commit), and add a few healthy consts in FFT.{h,cpp} and RealFFTf.{h,cpp}.

### CODE REVIEW

**Comment by JamesCrook** [comment]
Did you confirm that the power spectrum was faster too?

**Comment by RaphaelMarinier** [comment]
Yes. The reported timings are actually comparing the current vs old versions of PowerSpectrum(). I also just directly compared the current vs old versions of the FFT themselves, without the PowerSpectrum proxy, and I get the same results. In PowerSpectrum(), almost all of the time is spent computing the FFT.

Are cleanups like this welcome in the future?

**Comment by JamesCrook** [comment]
This cleanup is welcome.  I intend to pull it soon into my own branch, add some more comments and then commit to main Audacity.

Other removals of 'dead code' might not be so welcome.  Commented out code could be kept in Audacity for a good reason.  The MIDI code is a good example.  Const is good.  We like const.

Our tardy responses to pull requests on GitHub are mostly because we don't (yet) visit here regularly.  Most activity happens on our email list https://lists.sourceforge.net/lists/listinfo/audacity-devel .  It is much much easier for us to accept a change that is from someone we know and have talked with on that list.  They will know when we are in lockdown, where and how we track bugs, a bit more about our plans and so on.   

We would for example like to make it so that Audacity can compile with wxWidgets compiled with STL enabled.  Lots of const wxString changes for that to work.  But to do that the developer making the changes needs to engage with us so that we get it in in the right stages.  So they need to contact us on the email list first and chat a bit about the plan.

**Comment by RaphaelMarinier** [comment]
Ok. Of course, I understand that not all dead code should be removed, but here I went ahead since we have the same functionality implemented twice, with one version behind superior (faster).

I am the one who proposed on the ML to implement an audio alignment mechanism. I wrote this change in order to familiarize myself with Audacity's code base. I will start discussing on the ML when I see other potential small changes that I could make.

**Comment by JamesCrook** [comment]
Ah, OK, Sorry Raphael, I had not made that connection.  That makes a world of difference.   

Merged.

Future pull requests, please just share your branch name with us on devel with a comment there.

**Pull request merged**
