### PR TITLE
Fix stereo track loading

### PR DESCRIPTION
**Pull request by kryksyh**
Resolves: [#7196](https://github.com/audacity/audacity/issues/7196)

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by kryksyh** [comment]
@saintmatthieu there few other places where we didn't consider the stretch factor.
Please check if it also needs fixes (in another pr).

**Comment by saintmatthieu** [comment]
I'm looking at [this way of reproducing](https://github.com/audacity/audacity/issues/7196#issuecomment-2316956776). After the track is split, the clips of each channels should have the exact same stretch ratio, start and end times. Then it is saved. Then it is reopened. What explains the difference we now see in `AreAligned` ?

**Comment by kryksyh** [comment]
> I'm looking at [this way of reproducing](https://github.com/audacity/audacity/issues/7196#issuecomment-2316956776). After the track is split, the clips of each channels should have the exact same stretch ratio, start and end times. Then it is saved. Then it is reopened. What explains the difference we now see in `AreAligned` ?

what is happening is that we are calling SetRate only of the left channel, this leads to slight differences between left and right.

https://github.com/audacity/audacity/blob/e3b721d6730f0671a019391a4b94e764c221b660/libraries/lib-wave-track/WaveTrack.cpp#L656

**Comment by saintmatthieu** [comment]
... and this redoes the clip boundary calculations, I see...
I'm not so fond of the proposed fix because it loosens the equality check because of a numeric precision error we introduce before exporting to XML.
Given your analysis, isn't calling SetRate on the left channel as well not an option? (With a comment linking to this issue.) Or alternatively (but maybe more risky because hard to guarantee it won't have a stupid impact on some other stupid code) doing smth like
```cpp
void WaveTrack::SetRate(double newRate)
{
   if (mRate == newRate) return;
   ...
}
```
?

**Comment by kryksyh** [comment]
@saintmatthieu 
> I'm not so fond of the proposed fix 

Well, I don't believe that comparing floats to be equal here should be allowed. Semantically, what we are doing here is comparing if clips are aligned with sample precision, so the code should reflect that. Otherwise, if you want to compare times bitwise, let's do that, but rename the method to HaveIdenticalIntervals or something.

> calling SetRate on the left channel as well not an option
It makes sense. I checked it, and it works as expected. I can do that, but the first point still stands

**Comment by saintmatthieu** [comment]
> what we are doing here is comparing if clips are aligned with sample precision

`GetPlayStartTime()` and the end-time version of it do round the result to samples all right, but `GetSequenceStartTime()` not. I suppose it's because of the latter that the alignment check fails?
I think we're safer with a bitwise comparison. If the clips get merged into a stereo track, some assumptions of equality of sequence start and end times may be made later.

**Review by saintmatthieu — APPROVED** [review]

**Pull request merged**
