### PR TITLE
Settings structure for AudioUnit effect

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #2933

Settings structure defined for AudioUnit effect; some event handling un-entangled from the settings
manipulations, anticipating the definition of a Validator.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by pietro68** [comment]
I confirm that the bug I posted earlier, does not happen anymore after the rebase.

However, I found another problem. Have a mono track, instantiate a AUGraphicEQ, press the play button (the main one, not the one on the effect dialog) this will happen:
Screenshot 2022-05-19 at 16 07 03

**Comment by Paul-Licameli** [comment]
I fixed the crash.  Please review again.  There are changes in "Fetch parameters of each AudioUnits plug-in only once..." and later commits.

**Comment by pietro68** [comment]
Built and repeated the tests, all seems good now. I will have a look at the changes.

**Comment by Paul-Licameli** [comment]
> I could not really understand what the fixes consisted of, because they were squashed with previous commits? anyway, it works now.

"@[Paul-Licameli](https://github.com/Paul-Licameli) Paul-Licameli [force-pushed](https://github.com/audacity/audacity/compare/c5a33cc48c8a8164542ee5cd07e8b33e7a5fcff9..43e2a74f6ccbcfc9c72c915920765e342cdfe5a6) the AU-effect-settings  branch from [c5a33cc ](https://github.com/audacity/audacity/commit/c5a33cc48c8a8164542ee5cd07e8b33e7a5fcff9)to [43e2a74 ](https://github.com/audacity/audacity/commit/43e2a74f6ccbcfc9c72c915920765e342cdfe5a6)[Compare](https://github.com/audacity/audacity/compare/c5a33cc48c8a8164542ee5cd07e8b33e7a5fcff9..43e2a74f6ccbcfc9c72c915920765e342cdfe5a6) [17 hours ago](https://github.com/audacity/audacity/pull/2934#event-6646676641)"

That means you can fetch my fork and supply `c5a33cc ... 43e2a74` to `git log` or `gitk`

At least, that's what I do from the command line, when a branch I reviewed is force-pushed again with changes.

**Comment by Paul-Licameli** [comment]
Please observe that in the commit "Fetch parameters of each AudioUnits plug-in only once..." I changed it so that now, there is only one constructor of AudioUnitWrapper, and therefore, I have to change `AudioUnitEffect::RealtimeAddProcessor` to pass the new argument.  The new argument is the array of parameters from the AudioUnit.

The problem was that in `AudioUnitEffect::RealtimeAddProcessor`, (at the later commit "Eliminate CopyParameters ...") `slave->StoreSettings(GetSettings(settings))` was failing, meaning `mSlaves` did not grow by one.  I changed things so that the call does not fail, because `ForEachParameter` will not fail, because it has the array of parameters.

Please tell me you understand that.

**Pull request merged**
