### PR TITLE
Add footer to EGATs dialogs

### PR DESCRIPTION
**Pull request by vsverchinsky**
Resolves: #4205
Resolves: #3615 

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch for this:  audacity-win-3.5.0-alpha-20240213+848d528-x64

I observe the for all EGATs The **Apply/Generate** button has been move to the bottom of the EGAT dialog window and a **Cancel** button has been added (back) also in the footer.

image

_This is a much more "conventional" position for action buttons in a dialog._

**Comment by SteveDaulton** [comment]
Considering that the natural flow is to set the parameters first before previewing, it seems strange to have the Preview button at the top.

Nice to see the return of the Cancel button.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's subsequent branch for this:   audacity-win-3.5.0-alpha-20240214+3a68083-x64

The EGATs' footers in Vitaly's latest branch now have buttons for **Preview**, **Cancel** and **Apply**
image

Looks good to me.

**Review by crsib — APPROVED** [review]

**Comment by petersampsonaudacity** [comment]
I am in the process of updating the Manual for this change (about 40% done so far - it's a long job).

And I have to say that these EGATs look SO much better with the action buttons back in the footer.

Thanks for fixing this.

**Pull request merged**
