### PR TITLE
Add ability to reverse tracks in crossfadetracks

### PR DESCRIPTION
**Pull request by campg2j003**
This enhancement to the crossfadetracks.ny plugin adds the ability to choose whether to fade out the top or bottom track.  I was doing some processing where I crossfaded from one track to another with different processing and then back.  This allowed me to not have to either do it manually with crossfadeout/in or move the tracks.  It was originally created from the version shipped in 2.1.0 but I just updated it to match that in 2.1.1.  I am new to Git, and had to redo the commit (line terminators!), so maybe that's why there's two commits shown.  Sorry, I probably should have put it on a feature branch.

### CODE REVIEW

**Comment by SteveDaulton** [comment]
Thanks for the contribution, but what I had in mind, now that Nyquist plug-ins are a bit more flexible, was to make the fade direction automatic based on the selection. Something like this:

    ;nyquist plug-in
    ;version 4
    ;type process
    ;name "Crossfade Tracks..."
    ;action "Crossfading..."
    ;preview selection
    ;author "Steve Daulton"
    ;copyright "Released under terms of the GNU General Public License version 2"

    ;; crossfadetracks.ny by Steve Daulton Nov 2014.
    ;; Updated Sept 2015.
    ;; Released under terms of the GNU General Public License version 2:
    ;; http://www.gnu.org/licenses/old-licenses/gpl-2.0.html .

    ;control type "Fade type" choice "Constant Gain,Constant Power 1,Constant Power 2,Custom Curve" 0
    ;control curve "Custom curve" real "" 0 0 1

    (defun crossfade (type)
      (mult *track*
        (cond
          ((equal (guessdirection) 'OUT)  ; fade out.
            (case type
              (0 (pwlv 1 1 0))
              (1 (osc (hz-to-step (/ (get-duration 4))) 1 *sine-table* 90))
              (2 (s-sqrt (pwlv 1 1 0)))
              (T (custom curve 0))))
          (T  ; else fade in.
            (setf *control-srate* *sound-srate*)
            (case type
              (0 (pwlv 0 1 1))
              (1 (osc (hz-to-step (/ (get-duration 4))) 1))
              (2 (s-sqrt (pwlv 0 1 1)))
              (T (custom curve 1)))))))

    (defun custom (curve inout)
      ;; 'epsilon' defines the curvature of a logarithmc curve.
      ;; To avoid log 0 or /0 it must be > 0 and < 1.
      (let* ((curve (+ 0.99 (* -0.98 (min 1 (max 0 curve)))))
             ; magic number 2.7 gives approx 'constant power' curve at 50% setting.
             (epsilon (power curve 2.7)))
        (if (= inout 0)
            (setf logcurve (pwev epsilon 1 1))
            (setf logcurve (pwev 1 1 epsilon)))
        (sum 1
             (mult (/ -1 (- 1 epsilon))
                   (diff logcurve epsilon)))))
     
     (defun guessdirection ()
      (let* ((start (get '*selection* 'start))
             (end (get '*selection* 'end))
             (clips (get '*track* 'clips))
             (in end)
             (out in))
        (dotimes (i (length clips))
          (setf in (min in (abs (- start (first (nth i clips))))))
          (setf out (min out (abs (- end (second (nth i clips)))))))
        (if (< in out) 'in 'out)))

    (crossfade type)

**Comment by campg2j003** [comment]
Hi Steve,

My Nyquist is a bit rusty-- it's been a couple of years since I actually 
wrote a plug-in, particularly before breakfast, so I don't understand 
right off how you are deciding the direction.  (After breakfast.) Are 
you figuring out whether the selection is closer to the beginning or end 
of the track?  I'm a little leary of "automatic" things, but I think 
that should work.

Thanks.

Gary

**Comment by SteveDaulton** [comment]
I have posted my proposed updated version to the Audacity forum.
It will be easier, and I'd be happy to discus it there: http://forum.audacityteam.org/viewtopic.php?p=286488#p286488

Steve

**Comment by SteveDaulton** [comment]
The Cross Fade Tracks effect now has this feature, so closing this pull request. Thanks campg2j003 for your input that helped make this happen.

**Pull request closed without merging**
