### PR TITLE
Break dependencies on ffmpeg and mp3

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: *(direct link to the issue)*

Some dependency breaking before other import and export refactoring into modules

QA:  Test that all works as before in the Libraries page of the Preferences dialog.

Verify that the error message shows as before, when you try to import a file type that requires FFmpeg, but that is not installed on the system.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by crsib — APPROVED** [review]
I'm not sure if we need MP3 panel, but let's keep the behavior for now

**Review by vsverchinsky — APPROVED** [review]

**Comment by Paul-Licameli** [comment]
Rebased onto more recent master.  No conflicts, no changes.

**Comment by Ryan-Miller-Audacity** [comment]
Confirmed on both windows and Mac.

**Comment by Paul-Licameli** [comment]
Some dependency breaking before other import and export refactoring into modules

**Pull request merged**
