### PR TITLE
Parameter loading for batch EQ

### PR DESCRIPTION
**Pull request by WaveMotion**
This PR contains two commits; the first fixes chains that did EQ using a named EQ curve (i.e. not 'unnamed'). The second prevents users from using or making chains that use the 'unnamed' EQ curve. 

The second commit restores what looked to me to be the originally intended behavior, but I put it separate in case I was wrong.

### CODE REVIEW

**Comment by SteveDaulton** [comment]
This seems to work as far as it goes, but a couple of points:

1) When Equalization is called from a Chain, Init() is not called, which means that there is no checking of the sample rate, and mHiFreq may not have been initialised. If mHiFreq has not neen initialised, then in EffectEqualization::setCurve
`env->Insert(std::min(1.0, std::max(0.0, when)), value);`
may pass invalid values to Envelope::Insert

Off the top of my head, if mHiFreq is initialised to say -1 in the constructor, then at the top of EffectEqualization::setCurve we could use something like:
```
if (mHiFreq == -1 && !Init())
   return;
```
There may be a better solution ;-)

2) It's not a "rule" as far as I'm aware, but the usual style is to split long strings across multiple lines rather than relying on the ide/editor to wrap (see HelpText.cpp for examples).

**Comment by WaveMotion** [comment]
1) From inspecting call hierarchies, running an effect from a chain does seem to run its Init(). BatchCommands::ApplyEffectCommand() and Effect::Apply() both contain a call to AudacityProject::OnEffect(), which eventually leads to the Init() call. Running Debug with a breakpoint at EffectEqualization::Init() confirms this; the breakpoint is hit when normally applying EQ, when running a chain on the current project, and when running a chain on a file.

2) Thanks for the heads up, didn't notice that from my IDE : ) Fix incoming.

**Comment by SteveDaulton** [comment]
Please try running your patched version through a debugger.
Your addition of `setCurve(CurveName);` in  EffectEqualization::SetAutomationParameters is the cause of the problem because it leads to EffectEqualization::setCurve before Init() has been called.

**Comment by SteveDaulton** [comment]
Ah, you've also made the same mistake that I made a couple of weeks ago splitting long strings ;-)
To split the string over multiple lines, if you use "/" then the next line shouldn't have leading whitespace.
Alternatively, each line may be quoted separately. The former seems to be the usual style in Audacity, but either of these works for me:
```
      // The user tried to run a chain using the unnamed curve
      wxMessageBox( _("The chain which you tried to run had an Equalization \
command using an unnamed curve. Using Equalization in \
chain processing requires the chain file to specify a \
named EQ Curve.\n\nTo use a custom-drawn equalization \
curve in a chain, please save your curve to a new name \
by pressing 'Save/Manage Curves...' and then renaming \
the 'unnamed' curve. It will then be available under \
that name in the 'Select Curve:' list when editing your \
chain's Equalization parameters."),
                   _("Chain aborted: invalid EQ curve name: 'unnamed'"),
                   wxOK | wxICON_ERROR);
```
```
      // The user tried to run a chain using the unnamed curve
      wxMessageBox( _("The chain which you tried to run had an Equalization "
                      "command using an unnamed curve. Using Equalization in "
                      "chain processing requires the chain file to specify a "
                      "named EQ Curve.\n\nTo use a custom-drawn equalization "
                      "curve in a chain, please save your curve to a new name "
                      "by pressing 'Save/Manage Curves...' and then renaming "
                      "the 'unnamed' curve. It will then be available under "
                      "that name in the 'Select Curve:' list when editing your "
                      "chain's Equalization parameters."),
                   _("Chain aborted: invalid EQ curve name: 'unnamed'"),
                   wxOK | wxICON_ERROR);
```

**Comment by JamesCrook** [comment]
Nice idea.  Not completed.  Not suitable for merging.  Closed.

**Pull request closed without merging**
