### PR TITLE
Changing affordance hint text

### PR DESCRIPTION
**Pull request by vsverchinsky**
Resolves: https://github.com/audacity/audacity/issues/1332

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

**Comment by petersampsonaudacity** [comment]
Testing on W10 

the new Staus Bar text is far too long for the Audacity Window at default size
image

**Comment by Tantacrul** [comment]
I think we have a design issue with the description at the bottom of the app. It should be able to allow longer strings than that. Possibly we could solve it by being able to move to two lines when needed. We can fix that later. For now, I'd suggest:

1. "Drag clips to reposition them. Hold Shift and drag to move all clips on the same track."
2. We should have a tooltip for this too (just as you do when hovering over the play button)
3. Create an issue for the bottom bar truncating descriptions

I actually thought this would provide a tooltip if you hovered over the clip itself. One question: I assume screen readers still work fine with it?

@petersampsonaudacity - what do you think?

**Comment by petersampsonaudacity** [comment]
> I think we have a design issue with the description at the bottom of the app. It should be able to allow longer strings than that. Possibly we could solve it by being able to move to two lines when needed. We can fix that later. 

Or it could auto-scroll.

>For now, I'd suggest:
> 
>     1. "Drag clips to reposition them. Hold Shift and drag to move all clips on the same track."

I like this revised message.


>     2. We should have a tooltip for this too (just as you do when hovering over the play button)
I agree - we know from experience  that many (most) folk never notice.read the Status Bar


>     3. Create an issue for the bottom bar truncating descriptions
+1
> 
> One question: I assume screen readers still work fine with the description, even if it's truncated?

**Comment by DavidBailes** [comment]
> One question: I assume screen readers still work fine with the description, even if it's truncated?

screen readers just read the truncated text. (though obviously in this particular case it's not of much interest.)

**Review by Paul-Licameli — APPROVED** [review]

**Comment by petersampsonaudacity** [comment]
Testing on W10 with audacity-win-3.0.4-alpha-20210803+f90698c-64bit

Looks much better now with default window size.

**Pull request merged**
