### PR TITLE
Typos fixes in the French translation

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by trebmuh** [comment]
@Paul-Licameli : as discussed on the -translation ML, could you please merge this one before I start the FR translation against the new pot file? Thanks.

**Comment by trebmuh** [comment]
@Paul-Licameli @JamesCrook : ping?

**Comment by JamesCrook** [comment]
Hi Olivier.
It should have been Paul responding as he is managing translations.  He may have a reason why he didn't merge this, but as he hasn't given you a reason, I went ahead and merged it.  Sorry you had to wait for this.

**Comment by Paul-Licameli** [comment]
My apologies for neglecting this.  The notifications were going to a spam folder and I overlooked them.

PRL

**Comment by trebmuh** [comment]
Thanks @JamesCrook and @Paul-Licameli

**Pull request closed without merging**
