### PR TITLE
Update cs.po

### PR DESCRIPTION
**Pull request by pafri**
Czech translation update. Fixed e-mail in header.

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [ ] Each commit's message describes its purpose and effects
- [ ] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by pafri** [comment]
Hi,

could someone make the review, for the file to be able to go further.

Thanks.

**Comment by LWinterberg** [comment]
@pafri Looks like your changes break Audacity, it doesn't compile. It seems like it breaks sometime during or shortly after looking at the nyquist effects.

**Comment by pafri** [comment]
Also, what does it mean. Should something (specific strings) remain in English, but which. Or some quotation in source file is missing?

**Comment by pafri** [comment]
I would find that command to check the .po file first. It could show the exact problematic row.

**Comment by pafri** [comment]
Hi, after the fix in some strings, I´ve made the new request: see "Update cs.po - second attemt #4090". So this failed attempt shoul be closed and the #4090 could be approved:

"All checks have passed
11 successful checks"

**Pull request closed without merging**
