### PR TITLE
Add a Reset Configuration Dialog that warns the user as well as give options for resetting different preferences individually.

### PR DESCRIPTION
**Pull request by malevolentstrix**
image

Resolves: #1578 

This will add a dialog box that warns the user and gives the option to individually reset preferences that are usually reset by users.

- [X] I signed [CLA](https://www.audacityteam.org/cla/)
- [X] The title of the pull request describes an issue it addresses
- [X] If changes are extensive, then there is a sequence of easily reviewable commits
- [X] Each commit's message describes its purpose and effects
- [X] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [X] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by SteveDaulton** [comment]
Testing on Xubuntu 20.04 with 1920x1080 display, there's a display problem:
prefs

The window CAN be resized to fit the entire text, but it defaults to the "too small" size each time it opens.

**Comment by SteveDaulton** [comment]
While not *directly* related to this pull request, I  think it would be better for the default set of keyboard shortcuts to be the "Full" set. (Perhaps rename the "standard" set as "common shortcuts only" or similar.

**Comment by SteveDaulton** [comment]
More often than not, I would want to be selective about which prefs to reset.

Perhaps "Reset Configuration" should remember it's last used settings, (or perhaps that might be a bit weird as that would be one setting that must not be reset). 
If it does NOT remember what the user did last, then maybe a better default would be nothing selected. (It already has the instruction: "Select the configurations you want to reset"). That would allow users to directly select one or more options without having to deselect "All configurations" first.

**Comment by SteveDaulton** [comment]
Other than the minor issues that I've noted, this patch works well for me on Xubuntu 20.04. I like it a lot :+1:

**Comment by MalevolentStrix** [comment]
> Other than the minor issues that I've noted, this patch works well for me on Xubuntu 20.04. I like it a lot +1

I will remove the default checking of the boxes, make the keyboard options in a separate static text group, and will do something to get the window size correct as you mentioned. 

Thanks a lot for the review @SteveDaulton  :slightly_smiling_face:

**Comment by MalevolentStrix** [comment]
>The window CAN be resized to fit the entire text, but it defaults to the "too small" size each time it opens.

@SteveDaulton Can you check if the window is still smaller than the content as before? I couldn't find a proper way to set it universally, I tested it on Windows and Ubuntu 20.04 and it worked fine.

**Comment by LWinterberg** [comment]
Hello! We just [switched master to 4.0.0](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which makes this PR incompatible and/or obsolete as we're switching UI framework and reorganizing large parts of the codebase. You're very welcome to make these kinds of contributions in the future though, after things stabilize a little bit.

Also, sorry for dropping the ball on this one - we should've merged it when it still was fresh.

**Pull request closed without merging**
