### PR TITLE
Update German Translation from Transifex

### PR DESCRIPTION
**Pull request by Gootector**
Update German Translation from Transifex

Greetings,
Gootector

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by LWinterberg — APPROVED** [review]

**Comment by Gootector** [comment]
Thanks, but with typo in the title and "Last-Translator: Grzegorz Pruchniakowski <gootector@o2.pl>, 2020-2022\n" - 2022 only😆

**Comment by petersampsonaudacity** [comment]
@Gootector  - my German speaking wife queries (for consistency) wht you have used "du" rather than "Sie" at line 6122.

She says she has no objection to being duzed by an app - but she does like consistency.   ;-))

**Comment by Gootector** [comment]
@petersampsonaudacity This line is translated by guy who approved and merged this PR.

**Comment by Gootector** [comment]
@petersampsonaudacity And I made this PR at the last moment before the release of version 3.2.3.

**Comment by Gootector** [comment]
@petersampsonaudacity So... I like consistency also. Polish is "consistency" in 100%. German... is no "consistency", at this moment, but should be better in the near future. Nice to meet you too 😉

**Comment by Gootector** [comment]
https://github.com/audacity/audacity/pull/4123

**Pull request merged**
