### PR TITLE
remove Karaoke

### PR DESCRIPTION
**Pull request by LWinterberg**

### CODE REVIEW

**Comment by petersampsonaudacity** [comment]
I have added P1s to the Manual for this

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @LWinterberg 's branch build:  audacity-win-3.5.0-alpha-20231128+5b3f4c4-x64

Karaoke is no longer in the View menu in this branch build.
image

**Comment by Paul-Licameli** [comment]
After so many years, the happy bouncing ball finally got bounced.  :cry:

**Comment by petersampsonaudacity** [comment]
> ... the happy bouncing ball finally got bounced.

Got splatted !

**Comment by Paul-Licameli** [comment]
😠 

That's IT!!  I'm DONE!!!  I'm defecting to TENACITY!!!! NOW!!!1!!!1

/kidding

**Comment by buanzo** [comment]
roflmao

**Comment by Paul-Licameli** [comment]
> roflmao

Hello, buanzo, you magnificent SOB, you!!

**Comment by rbdannenberg** [comment]
Here's where it all began ... [Automatic Lyric Alignment](https://www.cs.cmu.edu/~music/video/lyric-align.mp4)

**Comment by buanzo** [comment]
> Here's where it all began ... [Automatic Lyric Alignment](https://www.cs.cmu.edu/~music/video/lyric-align.mp4)

Thank you!

**Comment by Paul-Licameli** [comment]
> > roflmao
> 
> Hello, buanzo, you magnificent SOB, you!!

Did I ever mention…

The first assembly language I ever learned,
Long ago in high school, was PDP-11, and one of the mnemonics, for “subtract one and branch,” was… SOB ?

**Comment by buanzo** [comment]
I was familiar with that one, but I hope you were using the non geek
meaning :) Cheers!

**Comment by Paul-Licameli** [comment]
> Here's where it all began ... [Automatic Lyric Alignment](https://www.cs.cmu.edu/~music/video/lyric-align.mp4)

cool!

Two thousand freakin seven???  What were you doing in that year, @LWinterberg ?

**Comment by Paul-Licameli** [comment]
> Here's where it all began ... [Automatic Lyric Alignment](https://www.cs.cmu.edu/~music/video/lyric-align.mp4)

2007?  So let’s long ago.

**Review by Paul-Licameli — APPROVED** [review]

**Comment by rbdannenberg** [comment]
I think 2007 was when I recorded the video before I lost the ability to run that archived version of Audacity. The work was completed by Dominic when he was a student in Dec. 2000.

**Comment by Paul-Licameli** [comment]
> I think 2007 was when I recorded the video before I lost the ability to run that archived version of Audacity. The work was completed by Dominic when he was a student in Dec. 2000.

“Let it snow”

I was told they got a lot of that white stuff around the Baltic lately.

**Comment by petersampsonaudacity** [comment]
> Here's where it all began ... [Automatic Lyric Alignment](https://www.cs.cmu.edu/~music/video/lyric-align.mp4)

@rbdannenberg  I'd have liked to see more of that label track - we only git a brief glimpse at the end

**Comment by petersampsonaudacity** [comment]
> “Let it snow”
> 
> I was told they got a lot of that white stuff around the Baltic lately.

But not much in Killington, Vermont,  for the skiing championships - the pistes look to be all artificial "snow" with the countryside all around barren of snow.

**Comment by petersampsonaudacity** [comment]
> The first assembly language I ever learned,
> Long ago in high school, was PDP-11, and one of the mnemonics, for “subtract one and branch,” was… SOB ?

DEC (whom I worked for for a number of years) had a habit of "cunning" acronyms.

My favourite example was FUBAR for Failed UniBus Address Register - a military acronym from longer ago with a ruder meaning ...

Plus the DEC User Group - DECUS, I'm pretty sure that someone at DEC knew the Latin for "ornament"

**Comment by Paul-Licameli** [comment]
The SOB instruction was used to make countdown loops.  Subtract one from a register, then branch conditionally, often backwards, of the new value was nonzero.  Or non-negative? I forget.

**Comment by petersampsonaudacity** [comment]
My other favorite in DEC's manual's was 

"**This page is left intentionally blank**"

creased me up every time

**Comment by LWinterberg** [comment]
\*party music stops*

**Comment by buanzo** [comment]
sad

btw what was the rationale for removing karaoke?

**Pull request merged**
