### PR TITLE
add support for "seconds + milliseconds" time format

### PR DESCRIPTION
**Pull request by JC3**
Resolves: https://github.com/audacity/audacity/issues/4258

Adds support for "seconds + milliseconds" time format to time widget.

image

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by petersampsonaudacity** [comment]
Just tested this on W10 with @JC3  Jason's branch:  audacity-win-3.2.4-alpha-20230203+0baa1bf-x64

This works fine for me in 
a) **Selection** toolbar
b) **Time** toolbar


image

**Comment by LWinterberg** [comment]
LTGM from a design point - we'll split this big list into sub-menus soon anyway

**Review by crsib — APPROVED** [review]

**Comment by LWinterberg** [comment]
wait why was this targeted for release-3.2.4? I screwed up merging this

**Comment by JC3** [comment]
> wait why was this targeted for release-3.2.4? I screwed up merging this

Because I have no idea how the branches work here so I based my code off of the latest release to minimize changes, figuring somebody who knew what they were doing would merge it into the correct branch 😂.

**Comment by LWinterberg** [comment]
evidently not me then! : D

**Pull request merged**
