### PR TITLE
Migrate clips

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Next act, the reparenting of clips in Time shift is done by the WaveTrackShifter class.

### CODE REVIEW

**Comment by JamesCrook** [comment]
Were we previously failing to resample clips on moving them between tracks?

**Comment by SteveDaulton** [comment]
On Wed, 16 Sep 2020 at 17:44, James Crook <notifications@github.com> wrote:

> Were we previously failing to resample clips on moving them between tracks?
>

In Audacity 2.4.2 (and earlier), if we move a clip to a track with a
different sample rate, the audio is resampled.
However, a stereo track may have different sample rates in each channel
(which can produce surprising behaviour for the unwary).

Steve

**Comment by Paul-Licameli** [comment]
> Were we previously failing to resample clips on moving them between tracks?

We were not failing to do that.  I only moved the code that does it.

**Comment by Paul-Licameli** [comment]
This pull request looks incomplete to me now.  I will add a commit.

**Review by JamesCrook — COMMENTED** [review]
This looks fine as far as it goes.
I am waiting for the actual fix for the bug.

**Comment by Paul-Licameli** [comment]
Rebased onto more recent master, no other changes.

The other thing I thought necessary will be in the next pull request.

**Pull request closed without merging**
