### PR TITLE
Track shifters

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Act II of the TimeShift restructuring eliminates two TypeSwitches and one Visit, and makes the clip-shifting menu items also work for Note tracks.

### CODE REVIEW

**Review by JamesCrook — COMMENTED** [review]
I see this is in draft, but wanted to ask:

Is the fixed/movable distinction too much of a special case and too geared to clips?  That clips won't move out the way and are non overlapping is a specific choice for wave clips.  
> The actual algorithm when moving something is to (a) to determine where it lands if it attempts to move to a new position (b) to determine what else changes when it moves to a new position.  Shouldn't TrackShifter itself be more agnostic of the algorithms, otherwise it's already specialised for clips? 

Please replace wxASSERT( false ) in TimeShiftHandle.cpp with wxFAIL_MSG ("Slide amount is in opposite direction or larger than requested").  The comment 'didn't honor post condition!' is too vague,  even in combination with the actual condition (above), but this would fix that by clarifying the intent of the post condition.  [One's first thought on seeing a multiply is that an area is involved; the next that integer overflow might be a concern].

**Comment by Paul-Licameli** [comment]
> I see this is in draft, but wanted to ask:
> 
> Is the fixed/movable distinction too much of a special case and too geared to clips? That clips won't move out the way and are non overlapping is a specific choice for wave clips.

But the non-overlapping constraint will be special to WaveTrackShifter and need not impemented in LabelTrackShifter and will not be in any way enforced by the base class.

The purpose is that the shifter can select only certain of the intervals as moving, then the TimeShift code can iterate only over moving or over fixed intervals as needed -- such as to make fewer snap positions.

> 
> > The actual algorithm when moving something is to (a) to determine where it lands if it attempts to move to a new position (b) to determine what else changes when it moves to a new position.  Shouldn't TrackShifter itself be more agnostic of the algorithms, otherwise it's already specialised for clips?

What do you mean?

TrackShifter, the abstract base class, and the TimeShiftHandle that uses it, are "agnostic," not committed to any particular policy for checking whether moving would succeed.  TimeShiftHandle just checks whether an error is reported.  Derived classes do that as appropriate to the type of track.  LabelTrackShifter need impose no constraint on movement.

> 
> Please replace wxASSERT( false ) in TimeShiftHandle.cpp with wxFAIL_MSG ("Slide amount is in opposite direction or larger than requested"). The comment 'didn't honor post condition!' is too vague,

I do not consider it vague when I used the @post Doxygen command in the documentation of TrackShifter to formalize a postcondition.

It means a derived class failed to keep its contract.

>even in combination with the actual condition (above), but this would fix that by clarifying the intent of the post condition. >[One's first thought on seeing a multiply is that an area is involved; the next that integer overflow might be a concern].

**Comment by JamesCrook** [comment]
Where is the @post condition?  I didn't see it.

> TrackShifter, the abstract base class, and the TimeShiftHandle that uses it, are "agnostic," not committed to any particular policy

The detail I'd missed is that mFixed is potentially used by LabelTrackShifter, not in deciding whether a move is allowed at all - for that no mFixed is needed, and constructing mFixed is pointless.  Rather mFixed may play a role in snapping of moving Labels.

Because I'd missed that use, mFixed looked like a WaveTrackShifter implementation detail that had crept into TrackShifter.  Hence my comment.

**Comment by Paul-Licameli** [comment]
There are some changes now.

None of the actual moving of clips is managed by TrackShifters yet.

Enough of the rest is managed by them, so that the snapping code in TimeShiftHandle makes no direct use of WaveTrack and
WaveClip classes, and the function in ClipMenus.cpp is generalized enough to shift NoteTracks too.

**Comment by JamesCrook** [comment]
I see this isn't draft anymore.  Is it ready for review, or might it change further as next stage is done?
Can you say more about the switch on hitTest introduced in f00128d please?

**Comment by Paul-Licameli** [comment]
See the TypeSwitch in TimeShiftHandle.cpp that is eliminated.

We decide whether nothing can be done for that click (and that was never the case but for WaveTrack).

If you can do something, then either we shift parts of the track and also try to shift parts of other tracks when the click is in the selection.  Or, we shift the clicked track only.

Old behavior is that the label track always shifts as a whole and takes nothing else with it when you click in it.  NoteTrack shifts as a whole but may take other tracks with it.  Wave track moves only certain clips but may take other clicks with it.

**Comment by Paul-Licameli** [comment]
Rebased onto more recent master, no changes

**Pull request closed without merging**
