### PR TITLE
Fix rpath for private libraries on Linux

### PR DESCRIPTION
**Pull request by bdrung**
Installing audacity on Linux will produce private libraries that have `RUNPATH` set to the build directory instead of the installation directory. https://github.com/audacity/audacity/pull/3302 implemented a workaround. Instead of letting cmake write a wrong `RUNPATH` into the installed libraries and fixing `RUNPATH` with a lengthy script afterwards, better configure cmake to create a correct `RUNPATH` in the first place.

The root cause is that the library directory is copied to the installation directory without touching the libraries. The cmake wiki says in RPATH handling caveats [1]: "Since install-side RPATH tweaking is an operation that is done by target-specific installation handling, any target that should have its install RPATH changed (e.g. to `CMAKE_INSTALL_RPATH`) needs to end up in the installation via an `install(TARGETS ...)` signature and not via directory-based copying."

So replace `install(DIRECTORY ...)` by individual `install(TARGETS ...)` for the libraries and modules. Then cmake will replace the `RUNPATH` to `$ORIGIN/../lib/audacity`, which is still incorrect. Therefore set `INSTALL_RPATH` explicitly.

Fixes: https://github.com/audacity/audacity/issues/3289
[1] https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling#caveats

- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by crsib** [comment]
Are you sure that this fixes is needed? Can you please provide more details?

**Comment by bdrung** [comment]
Yes, since https://github.com/audacity/audacity/pull/3302 was just a workaround instead of a real fix. This merge request reverts https://github.com/audacity/audacity/pull/3302 and fixes the cmake configuration.

**Comment by crsib** [comment]
Why that was a workaround and not a fix?

**Comment by crsib** [comment]
From you PR I observe that you install unconditionally, so I expect problems with it on platforms other than Linux. Have you checked on them?

**Comment by bdrung** [comment]
I consider it a workaround to let cmake install libraries with wrong `RUNPATH` and run a 59 line long script (named `fix_rpath.cmake`) afterwards to fix it.

**Comment by bdrung** [comment]
Thanks for the pointer. I changed the install command to only be included on Linux (using the same if-condition that were applied previously).

**Comment by crsib** [comment]
So it appears that your fix breaks the Linux build when it is not using system only libraries. And now I remember why I had to hack-around the issue in the first place.

**Comment by bdrung** [comment]
The solution from this merge request should also work for AppImage. I haven't found time yet to debug the failure there.

**Comment by crsib** [comment]
It will not work for the case when Conan is enabled. It works for "system only" builds. This means that we either need to

* vendor all the dependencies back,
* or drop older Linux distributions,
* or manually build and install all the packages. 
 
We do not have plans for either of the options right now nor in foreseeable future.

**Comment by bdrung** [comment]
Why won't it work when Conan is enabled?

**Pull request closed without merging**
