### PR TITLE
Lift effect preview from libraries

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: *(direct link to the issue)*

A preliminary before lifting wave track caching scope out of lib-sample-track.

Move the previewing for Effects out of lib-effects, back up into Audacity.

This also makes lib-effects independent of lib-audio-io, which is nice.

(There may be a future "lib-effects-ui" for this layer, though it might not be toolkit neutral.)

- [x] QA:  Test playback, recording, effects preview from the destructive dialog.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by crsib** [comment]
Please fix the build :-)

**Comment by Paul-Licameli** [comment]
> Please fix the build :-)

Sorry, forgot to turn off precompiled headers locally.

It only needs one forward class declaration.

**Review by crsib — APPROVED** [review]

**Comment by saintmatthieu** [comment]
So this PR removes the preview functionality from `lib-effects` because the preview functionality needs the creation of `TransportTracks`, which in turn need `TrackList`. So now `lib-effects` doesn't need `TrackList` for that purpose.
That's a couple of pieces of the puzzle, still missing the bigger picture. We can talk about it later. Don't wait for my approval.

**Comment by dozzzzer** [comment]
Tested: playback, recording, effects preview from the destructive dialog

**Comment by Paul-Licameli** [comment]
But it is also nice that lib-effects loses one dependency, on lib-audio-io.  I didn't like that dependency.  I really should have thought of all this extra work when lib-effects was extracted.  But that was itself already a large and difficult thing to do, requiring a lot of other tough untangling of some confused control flow involving UI with internals.

**Pull request merged**
