### PR TITLE
Add some honesty to the README

### PR DESCRIPTION
**Pull request by mvgorcum**
Thank you for at least being honest about your motivation.

### CODE REVIEW

**Comment by JamesCrook** [comment]
Thanks, but this can't be accepted as you haven't signed the CLA.

**Comment by Tannermanner2008** [comment]
LMAO

**Comment by AkaiiKitsune** [comment]
I can't believe this is happening...

**Comment by jakubfabijan** [comment]
>**audacity** blocked **mvgorcum**

Well... it speaks for itself...

**Pull request closed without merging**
