### PR TITLE
Reorganize tree

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Intended for 3.0.0 development.

NOW PASSING git hub actions, after the merge of pull request 7 into our wxWidgets fork.  But there were reports of Windows Debug builds failing, which should have an easy fix in AudacityHeaders.h.

This commit makes a CMakeList.txt file in each sub-directory of src (with a few minor exceptions) which allows easy specification of that directory's allowed compilation dependencies, so that later we can work on further restriction of dependencies and other improvements of the graph.

See comments in the branch tip commit for more detailed explanation.

=======

Update: macro do_directory takes another keyword OBJCPP_SOURCES and some CMakeLists.txt are simplified using it

Update for branch tip d8e9feaafa2bef5a15e0c18c0327cbecc567350e: fixed build with precompiled headers

Update for branch tip fde4c24466293543985fd01280cbed100c2a560c: fixed Windows debug build with precompiled headers

Update for branch tip 04326739b2c9c75a0812d6fa568580c45d78cc98: fixed absent effect, generator, analyzer menu items

Update for branch tip 26934474e0a7cc11fcfbdebd1164423ab9d90d2c: Keywords INCLUDE_PRIVATE, INCLUDE_PUBLIC, PRIVATE, and PUBLIC for do_directory macro, and more thorough comments about their usage

Update form branch tip 5bc09090990f1c1561935018b8427e00710b3f83: rebased onto 9acabbbed3a1063a18aa7df2314116edf37d3813 after merging https://github.com/audacity/wxWidgets/pull/7, so I expect it to pass Windows builds too

Update for branch top 7c9b60e2ca409f0f8ee6a7333cc700130c0e4dce: no longer making separate precompiled headers for each subdirectory, which should make the clean build faster.  But the common precompiled headers can contain only a few of Audacity's headers.  The benefit is mostly from precompilation of the wx/ headers.

Update for 75ce2935c3f3b539adddcf678bb3f046f60cd903: just rebasing.

### CODE REVIEW

**Comment by lllucius** [comment]
I recloned your tree and tried this branch again.  The Debug build on Windows still fails and the Release build times "seem" to have gotten a bit longer than previous tests.

Current Audacity master builds in "0m57.680s" and your branch builds in "2m14.121s".

I think a lot of that time is spent generating the precompiled header for each of the subdirectories.  Maybe a separate target that does nothing but generate the PCH and then all of the subdirectory targets would use that single PCH.  Basically, tossing the CMake PCH support and doing it manually.

The generated PCH would have only "external" headers, like WX and system includes and maybe one or two Audacity specific headers.  With your prior include detangling efforts, I'd think that would be good enough.

**Comment by Paul-Licameli** [comment]
On Sunday, June 28, 2020, Leland Lucius <notifications@github.com> wrote:

> I recloned your tree and tried this branch again. The Debug build on
> Windows still fails
>
>
> Same errors as before in any and vector?

> and the Release build times "seem" to have gotten a bit longer than
> previous tests.
>
> Current Audacity master builds in "0m57.680s" and your branch builds in
> "2m14.121s".
>
> I think a lot of that time is spent generating the precompiled header for
> each of the subdirectories. Maybe a separate target that does nothing but
> generate the PCH and then all of the subdirectory targets would use that
> single PCH. Basically, tossing the CMake PCH support and doing it manually.
>

I will need to rethink what I did for PCH.  Maybe keep just one, but it
must include fewer of Audacity’s own headers.  The list of them may not be
well chosen anyway after so much else has changed in those headers.

There need not be just one precompiled header for an object.  Maybe I can
add more precompiled headers in subdirectories and figure out how to share
them among some subdirectories so that there is not repeated compilation.

PRL

**Comment by Paul-Licameli** [comment]
On Sun, Jun 28, 2020 at 4:43 PM Paul Licameli <paul.licameli@gmail.com>
wrote:

>
>
> On Sunday, June 28, 2020, Leland Lucius <notifications@github.com> wrote:
>
>> I recloned your tree and tried this branch again. The Debug build on
>> Windows still fails
>>
>>
>> Same errors as before in any and vector?
>

Leland, is there a change I can make to .github/workflows/cmake_build.yml
so that I build debug in GitHub?

PRL

**Comment by lllucius** [comment]
Add “-D CMAKE_BUILD_TYPE=Debug”.  If you want to get a good link, you'll need to do it for the wxWidgets step too.

**Comment by Paul-Licameli** [comment]
Well I tried that but I haven't yet reproduced a build failure.

What are the compilation errors that you still see for Windows Debug?

PRL

**Comment by lllucius** [comment]
Really sorry Paul.  I completely spaced out that it was MSVC.  the -DCMAKE_BUILD_TYPE doesn't work with MSVC or Xcode.  In the Actions case, look for the lines like this:

cmake --build "wxroot" --config Release --verbose

Change the "Release" to "Debug".

**Pull request closed without merging**
