### PR TITLE
Effect settings dialog is always modal for destructive workflows

### PR DESCRIPTION
**Pull request by crsib**
Resolves: #2987

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by vsverchinsky — APPROVED** [review]

**Review by Paul-Licameli — CHANGES_REQUESTED** [review]
I request that the merge be delayed.

Nothing wrong with the changes.

**Comment by Paul-Licameli** [comment]
The reason to delay merge is that, while other effect families are making the transition to statelessness, the old interface for realtime effects should also remain available to QA while testing.

In case refactoring introduces errors, testing with the old user interface may help us understand if the regression in behavior is properly part of the refactoring of one effect family, or is instead some bug remaining in the general framework.

**Comment by Paul-Licameli** [comment]
> I'm not sure if I understand your point. The interface is not changed (preview button is still in place) and I only found out that the dialog is not modal two weeks ago, I have always used `Preview` button

The Preview button may be available, but if it treats the effect like any other non-realtime effect, then it will pre-compute some sound to play, and not respond to control changes while playing.

That should be the behavior of the dialog in this branch (is it?) but is not the behavior I would like to keep available to QA.

**Comment by Ryan-Miller-Audacity** [comment]
> @Ryan-Miller-Audacity @dozzzzer any comments on that? Do you use play button in such case?

I would say in general the play button is where I go when dealing with anything realtime.

 However, with the described usefulness of being able to determine if there is a regression in behavior or a bug in the general framework, would it not be possible to go ahead and do the merge, but keep a separate branch for any discovered bugs to be verified in to determine if it is a regression or not? Or would that require a lot of upkeep? IMO, it's best to have QA taking place how the end user will actually end up seeing/using it as much as possible, but using Paul's plan as a additional tool could be helpful for better determining bugs in relation to regression etc.

Essentially, i'm asking for a "best of both worlds" scenario here.

**Comment by crsib** [comment]
Should this be merged now @Paul-Licameli?

**Comment by Paul-Licameli** [comment]
> Should this be merged now @Paul-Licameli?

I still want to wait.

**Comment by crsib** [comment]
@Paul-Licameli any reason to wait longer? It should be merged before alpha anyway

**Review by Paul-Licameli — APPROVED** [review]

**Comment by Paul-Licameli** [comment]
VST3 statelessness is done and VST is not must-have for alpha, so poyekhali!

**Pull request merged**
