### PR TITLE
More in lib track selection

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: #5448

The logic for getting and setting the focused track is lowered to libraries.

TrackPanelAx is now used only by TrackPanel and together they inject the extra toolkit-dependent interaction with screen readers.

The other places that used to use TrackPanel.h, use only TrackFocus.h now.

QA: 
- [x] yellow focus border of tracks draws, and moves with cursor arrow keys
- [ ] screen reader navigation to tracks and speaking of track names

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Really ready for review now and rebased onto latest master

**Comment by Paul-Licameli** [comment]
Force-pushed only a commit comment change

**Review by crsib — APPROVED** [review]

**Comment by chinakov** [comment]
> screen reader navigation to tracks and speaking of track names

Yeah, there seems to be a problem with this. Unlike in the release version of Audacity 3.4.2, this build does not let the narrator 'narrate' the individual tracks added to Audacity. Rather, it only narrates the track pane.

**Comment by Paul-Licameli** [comment]
Rebased to recent master, resolved conflicts, inserted two small fixup commits so the screen reader works

**Comment by Paul-Licameli** [comment]
Rebased to recent master

**Review by crsib — DISMISSED** [review]

**Comment by Paul-Licameli** [comment]
I promised you two fixup commits to review, but somehow misplaced them and didn't really include the fixes for the problems Anton identified.

**Comment by Paul-Licameli** [comment]
Now they are there.  Please review again.  It should take just a minute.

**Review by crsib — APPROVED** [review]

**Pull request merged**
