### PR TITLE
Fix registry usage

### PR DESCRIPTION
**Pull request by Paul-Licameli**
Resolves: Two questionable but minor problems found post-review

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by crsib** [comment]
I don't understand what this PR addresses.

**Comment by Paul-Licameli** [comment]
> I don't understand what this PR addresses.

Are the commit comments enough explanation?

**Comment by crsib** [comment]
The first one performs a copy of the registry for no reason, because we don't care about the ordering. 

The second one is very minor, but I don't see how it changes anything really. I think initially I haven't used the format string because I don't understand how registry sorting works. I don't really understand it even now.

Implementation worked for me, so I kept it. If we decide to allow user to sort the list (I don't see it coming at all) - it doesn't matter what is written to the config - format string, some ordered identifier or even GUID. 

So...
> Are the commit comments enough explanation?
No, not really.

**Comment by crsib** [comment]
Oh, and yeah - the first commit crashes tests, so it definitely should not be merged.

**Comment by Paul-Licameli** [comment]
> Oh, and yeah - the first commit crashes tests, so it definitely should not be merged.

I should look closer at it then.  Maybe fix the inconsistency the opposite way.  There is another call to Visit() in the file that could instead be the changed one.

**Comment by crsib** [comment]
They are inconsistent because they are used to achieve different goals. Why this inconsistency is a problem? Rewriting `void SnapFunctionsRegistry::Visit(SnapRegistryVisitor& visitor)` will break UI, I won't approve it either.

**Comment by Paul-Licameli** [comment]
> They are inconsistent because they are used to achieve different goals. Why this inconsistency is a problem? Rewriting `void SnapFunctionsRegistry::Visit(SnapRegistryVisitor& visitor)` will break UI, I won't approve it either.

Then wait to see the rest of a bigger PR that cleans up the Registry system to simplify usage.

**Comment by Paul-Licameli** [comment]
Registry should have let you express your intent better and it should have been easier to figure it out.
- Type safety (no usage of BaseItemPtr)
- Less boilerplate code for `SnapRegistryItemRegistrator`, `SnapFunction`, `SnapFunctionGroup`, etc. -- easy generation from templates instead
- Easier definition of analogues of `Command`, `Menu`, etc. so you could express the un-scattered, ORDERED tree of built-in snap functions directly
- Therefore avoiding use of ordering hints except where really needed for scattered items

**Pull request closed without merging**
