### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by trebmuh**
Update the French translation.

I was on my way to update it to 100% but I noticed a reference to transifex. Since I'm not on transifex and I'm reluctant to be so and, before continuing to update the translation further, I'd like someone with commit access to the audacity git repo to confirm that it's OK for me to send a pull request with the full French GUI translation here on github.

Please advise. Thanks.

### CODE REVIEW

**Comment by JamesCrook** [comment]
Thanks Olivier!  Yes we can and will take it from GitHub.  Or from a .po file posted to the translators list.  Paul is coordinating the 2.2.1 release and managing deadlines for a .po to get into that release.

**Comment by trebmuh** [comment]
Awesome. I'll update the French translation and will update this pull request on the coming days. I'll ping you then.

**Comment by Paul-Licameli** [comment]
Great thanks, Olivier!

But I still see in your file:

POT-Creation-Date: 2017-07-22 11:50+0100\n

This tells me you did not start with the most up-to-date version of audacity.pot.

Please do so to complete the work.

Please subscribe, if you have not yet, to this mailing list:

https://sourceforge.net/p/audacity/mailman/audacity-translation/

PRL

**Comment by trebmuh** [comment]
@Paul-Licameli :
I've subscribed to the mailing list you mentionned above and I've sent a message to check if my subscription was correct.

About the fr.po, I didn't started from a fresh POT file since there is already a fr.po in the repo. So I started from the current fr.po where I can see a bunch of non-translated file. Shouldn't I do so ?

**Comment by Paul-Licameli** [comment]
Olivier,

I did see your email to the translation list.

I suggest you talk to other translators there, who know the editing tools for .po files better than I do.  But I know this much:

There are command-line tools:

msgcmp fr.po audacity.pot

lists error messages when the .po is incomplete.  There is also msgmerge that updates a .po to a .pot, marking some strings obsolete and putting new blank msgids in place.  Details in this long page:  

https://www.gnu.org/software/gettext/manual/gettext.html#msgmerge-Invocation

And there is also the graphical program poedit, which I know less about, but it is meant to aid the translator in finding the unfinished work and in other tasks.

PRL

**Comment by JamesCrook** [comment]
CLOSED.  This pull request was created to have a conversation, and communication and progress is now on the translation list and continuing there.  Audacity will later take either a pull request or an attached .po file for french at the translators list.

**Pull request closed without merging**
