### PR TITLE
Update ffmpeg headers to 4.2.3

### PR DESCRIPTION
**Pull request by Zapeth**
Addresses https://github.com/audacity/audacity/issues/398

Header files were taken from https://ffmpeg.zeranoe.com/builds/ version 4.2.3 (the various architecture and license versions of these header files have equivalent content)

### CODE REVIEW

**Comment by whalehub** [comment]
@Paul-Licameli @JamesCrook requesting review

**Comment by AvrahamTsaban** [comment]
I am not sure how much attention do the audacity developers put into the conversation here. 
According to [this audacity forum post](https://forum.audacityteam.org/viewtopic.php?f=20&t=68196&sid=15fe1125d989d5155cfcd9b6b47c4cf7), feature request should be sent on the forum. 
Join [this forum discussion](https://forum.audacityteam.org/viewtopic.php?f=20&t=116912). Your voice will be helpful!

**Comment by JamesCrook** [comment]
@AvrahamTsaban We do pay some attention to conversations here and requests here.  Updating ffmpeg, portaudio and enabling new options in wxWidgets are all in our plans.  However Unitary Project (3.0.0) and follow up (3.0.1) take precedence.  When we change libs it usually introduces new problems.  We do not want that for those two releases.

**Comment by JamesCrook** [comment]
This pull request is obsoleted by #741 (update to ffmpeg v4.3.1)

**Pull request closed without merging**
