### PR TITLE
Update German Translation (3.6.2)

### PR DESCRIPTION
**Pull request by Gootector**
Update German Translation (3.6.2)

Greetings,
Gootector

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Review by LWinterberg — APPROVED** [review]
Fwiw: I'm unsure if Attack/Release are translated at all in German usually. I see that https://www.thomann.de/de/onlineexpert_page_kompressoren_die_dynamischen_parameter.html for example just uses the english terms, as does https://de.wikipedia.org/wiki/Kompressor_(Signalverarbeitung)

**Comment by Gootector** [comment]
Hi, I'll check it soon. When deadline?

**Comment by Gootector** [comment]
@LWinterberg Hi, I updated the translations. In Polish, I found "more correct" translations for Attack/Release terms, but there are Attack/Decay terms also, so... so I think that these terms are very similar. In German, I reverted to English. "The compressor's terms" are very specific...

**Comment by Gootector** [comment]
@LWinterberg Please merge Polish & German. I finished the translations.

**Pull request merged**
