### PR TITLE
FR translation improvements

### PR DESCRIPTION
**Pull request by trebmuh**
- fixes for a few typos in the FR translation
- a few general improvements
- some punctuations
- min/maj
- updates the header's timestamp

### CODE REVIEW

**Comment by trebmuh** [comment]
@Paul-Licameli : I've used `&nbsp;` to provide the non-breakable spaces to the translation in French. That said, I've rebuild a 2.2.0 version with such a fr.po and the `&nbsp;` are displayed as this:

capture du 2017-12-10 15-23-53

A strange thing is the `&nbsp;` are taken in account in other places such as ([in the code](https://github.com/audacity/audacity/blob/master/locale/fr.po#L594)):
capture du 2017-12-10 15-31-55

Any idea?

**Comment by trebmuh** [comment]
@Paul-Licameli ping

**Comment by Paul-Licameli** [comment]
Olivier, I am very sorry I missed your messages so long.

I took the first seven of these commits, squashed as one.

I cannot take the commits in which you added &nbsp;

Translations should not contain markup, unless the msgid has markup.

Almost all translated strings are used in contexts where they are not interpreted as HTML.

I am sorry for your confusion on this point.

**Comment by Paul-Licameli** [comment]
Olivier, I also took and squashed the other seven commits, but I replaced most of the &nbsp; with spaces.

What I said is not quite correct:  a minority of the msgids with no markup really are still in HTML context.  But you don't know which.  Assume they are not.

Perhaps in future I can add i18n-hint comments for the few that are.

So, relax, you work so far is saved.  But now there is a new audacity.pot to merge your fr.po with.

**Comment by trebmuh** [comment]
Thank you @Paul-Licameli 
No worries about the space. They can stay like that.

**Pull request closed without merging**
