### PR TITLE
Rename INSTALL to INSTALL.txt

### PR DESCRIPTION
**Pull request by 22jcampb**
*(Renamed the INSTALL file to INSTALL.txt so it is recognized by OS's as a text file, and therefore can be easily opened)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [N/A] I made sure the code compiles on my machine
- [N/A] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [N/A] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

**Comment by peepopoggers** [comment]
I think this is good for windows users.

**Review by newbies155 — APPROVED** [review]
w

**Comment by 22jcampb** [comment]
Can we get someone with write access here?

**Comment by peepopoggers** [comment]
Why closed? For windows users they will presume this is a file they should not touch because when opening, there is no notation of what to open it with.

**Comment by SteveDaulton** [comment]
If you're referring to this file: https://github.com/audacity/audacity/blob/master/INSTALL
it's not really relevant to users unless they are techy enough to build from source.

**Pull request closed without merging**
