### PR TITLE
Fix CMake build of modules

### PR DESCRIPTION
**Pull request by lllucius**
They must not be linked against any libraries as build time.  The
symbols will be resovled at runtime.

# Pull Requests

If you are submitting a pull request, please read https://wiki.audacityteam.org/wiki/GitHub_Pull_Requests

### CODE REVIEW

**Comment by eszlari** [comment]
Have you considered cmake's build-ins [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html) / [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) for vendored dependencies?

**Comment by lllucius** [comment]
Yepper, I did.  But, doing it the way we are now allows us to control the build requirements more carefully.  And some of the dependencies do not have a suitable Windows build.

It does seem to cause extra work for us doing the way we have, but the libs don't change that often and never very much.

**Comment by eszlari** [comment]
> And some of the dependencies do not have a suitable Windows build.

If they run on Windows, they should compile there too, no?

**Comment by lllucius** [comment]
But what extra "tools" are required on the users system to build them when using the dependency provided build process?  Right now, only git, cmake, and the chosen generator are required. 

> 
> 
> > And some of the dependencies do not have a suitable Windows build.
> 
> If they run on Windows, they should compile there too, no?
But what extra "tools" are required on the users system to build them when using the dependency provided build process?  Right now, only git, cmake, and the chosen generator are required.

One of the goals for us we to completely jettison the "AutoTools" headaches we've had over the years and if we were to use something like ExternalProject, we'd still be open to those headaches as not all of the external dependencies provide a CMake project.

**Comment by eszlari** [comment]
> One of the goals for us we to completely jettison the "AutoTools" headaches we've had over the years and if we were to use something like ExternalProject, we'd still be open to those headaches as not all of the external dependencies provide a CMake project.

Why not patch in the cmake support in those cases, like e.g. Krita does:

https://invent.kde.org/kde/krita/-/tree/master/3rdparty/ext_libraw

**Comment by lllucius** [comment]
> 
> 
> > One of the goals for us we to completely jettison the "AutoTools" headaches we've had over the years and if we were to use something like ExternalProject, we'd still be open to those headaches as not all of the external dependencies provide a CMake project.
> 
> Why not patch in the cmake support in those cases, like e.g. Krita does:
> 
> https://invent.kde.org/kde/krita/-/tree/master/3rdparty/ext_libraw

Isn't that "sort of" what we are doing now (in a way)?  :-)

**Comment by eszlari** [comment]
> Isn't that "sort of" what we are doing now (in a way)? :-)

Sure, but using cmake's build-ins would make you a good open source citizen, because it would make it more easily reusable by others. :smiley:

**Comment by lllucius** [comment]
> 
> 
> > Isn't that "sort of" what we are doing now (in a way)? :-)
> 
> Sure, but using cmake's build-ins would make you a good open source citizen, because it would make it more easily reusable by others. 😃

Honestly (and this is my opinion, not the team's), if we had time to contribute to other projects, then we're doing something wrong as we have a ton of feature requests that we should be working on.  And, it takes extra time to put together something that another project might even consider accepting...if they accept it at all.  And if we don't have 100% acceptance from all of the other projects, then we wind up with a mishmash.

And I think we've done pretty well on the "good open source citizen" front.

**Pull request merged**
