### PR TITLE
refactor SeekLeftOrRight

### PR DESCRIPTION
**Pull request by evanshort73**

### CODE REVIEW

**Comment by Paul-Licameli** [comment]
Is this to serve some other purpose?  Do you wish to add other commands?

**Comment by evanshort73** [comment]
No, I just offered to clean it up as a familiarization task.

**Comment by evanshort73** [comment]
I submitted an email to audacity-devel about it but I'll put it here as well:

I finished my initial refactor of SeekLeftOrRight. I managed to remove 41 lines of code while making it (in my opinion) more readable.

I removed some dead code for seeking by pixels while the audio is playing, but it would be very easy to restore in the future.

I noticed the slightly odd behavior that when the audio is playing, shift+ctrl+arrow still constrains on the current selection even though shift+arrow is overridden to move the playback cursor. I disabled shift+ctrl+arrow during playback.

Aside from that, all the existing behavior should be preserved. I made a spreadsheet describing the existing behavior: https://gist.github.com/evanshort73/0b130c923edc12196ea1480a6c3d0188

Of course I am open to any feedback about this pull request and I would greatly appreciate anyone who takes the time to review it.

**Comment by JamesCrook** [comment]
Thanks.  I've pulled #263 instead.

**Pull request closed without merging**
