### PR TITLE
French translation update for the upcoming 2.3.0

### PR DESCRIPTION
**Pull request by trebmuh**
Strings update + typos fixes

### CODE REVIEW

**Comment by trebmuh** [comment]
@JamesCrook @Paul-Licameli : there is [on error on the travis build](https://travis-ci.org/audacity/audacity/builds/422322306#L5904) that I don't understand and thus, don't know how to fix. Any advice welcome.

**Comment by Paul-Licameli** [comment]
Sorry Olivier, I think we made some procedural errors in updating our audacity.pot.  All the generated lines
#, elisp-format
should instead have been
#, lisp-format

I think we need to correct our audacity.pot first and then ask you to merge and update again.

**Comment by trebmuh** [comment]
Hi @Paul-Licameli and all.

I've manually replaced the `#, elisp-format` by `#, lisp-format` (they were only 3 occurrences in the file) and the travis build now passes. Thanks for the hint.

Can you please merge this PR before updating the pot file? I fear having to redo all the string translations if not.

**Comment by trebmuh** [comment]
Thanks @JamesCrook :+1: 
@Paul-Licameli let me know on the translation mailing list when/if a new .pot file is available and then the French translation .po file needs an update.

**Pull request merged**
