### PR TITLE
use issue forms

### PR DESCRIPTION
**Pull request by LWinterberg**
This PR converts the existing issue templates (found at https://github.com/audacity/audacity/issues/new/choose) to forms and changes them to (hopefully) fulfill their purposes better. 

It automatically applies a relevant label, and you can also make it automatically assign a person, auto-fill titles and form boxes and stuff like that. Further info on forms can be found at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

You can see them in action here: https://github.com/LWinterberg/audacity/issues/new/choose

* Output of a bug report: https://github.com/LWinterberg/audacity/issues/7 
* Output of an enhancement request: https://github.com/LWinterberg/audacity/issues/8
* Output of a plugin bug: https://github.com/LWinterberg/audacity/issues/9

### CODE REVIEW

**Comment by crsib** [comment]
Probably let's remove "actual behavior"? I feel that it usually duplicates the bug description

**Comment by LWinterberg** [comment]
@dozzzzer added the actual behavior line, so maybe it's helpful for him

**Comment by Ryan-Miller-Audacity** [comment]
> Probably let's remove "actual behavior"? I feel that it usually duplicates the bug description

I have found in the past that the "actual behavior" field simply allows for a more concise description of the bug vs the bug description and lets the reader go to a very direct description of the issue without having to sift through the sometimes verbose bug description. It also just gives a very direct 1:1 comparison to the expected behavior. So it can be helpful sometimes, but I see both sides of the coin. 

Overall, forms seem cool and add a level of usability (and structure) beyond an open text field. I don't think I have any complaints with them. Presumably the Enhancement/Plugin forms would add their relevant labels? It looks like they both just add the bug label currently.

**Comment by LWinterberg** [comment]
> Presumably the Enhancement/Plugin forms would add their relevant labels? It looks like they both just add the bug label currently.

My fork doesn't have the labels which exist here so it didn't apply them, but yes: Enhancement request would be auto-tagged "Enhancement request", plugin issues would be tagged "bug, plugins"

**Comment by Ryan-Miller-Audacity** [comment]
> > Presumably the Enhancement/Plugin forms would add their relevant labels? It looks like they both just add the bug label currently.
> 
> My fork doesn't have the labels which exist here so it didn't apply them, but yes: Enhancement request would be auto-tagged "Enhancement request", plugin issues would be tagged "bug, plugins"

Ah, right on.

**Comment by LWinterberg** [comment]
>  It also just gives a very direct 1:1 comparison to the expected behavior. So it can be helpful sometimes, but I see both sides of the coin.

Maybe the "actual behavior" field should be optional then

**Review by dozzzzer — APPROVED** [review]

**Pull request merged**
