### PR TITLE
Updating FFmpeg API calls.

### PR DESCRIPTION
**Pull request by heckendorfc**
These functions cause the build to fail when using the FFmpeg 2.7 branch.

### CODE REVIEW

**Comment by JamesCrook** [comment]
Hi Heckendorf.
Your changes however cause the Travis build to fail.  https://travis-ci.org/audacity/audacity/builds/71094555 Can you fix that so we can consider the pull request?

**Comment by heckendorfc** [comment]
Hi,
It will build with external FFmpeg 2.7, like when built through FreeBSD ports. If you'll allow the bundled version of FFmpeg to be upgraded to 2.7,  I can update this patch to include that also.

**Comment by silverbacknet** [comment]
Almost a year later, is there any movement on this patch? Does anyone even care that ffmpeg 2.2.2 has so many documented security problems that expose users? At least this should work fine with 2.7.7, although now 3.0.x is current.

**Comment by windinthew** [comment]
There is a later patch here https://github.com/audacity/audacity/pull/130/commits/41de5b385b2ca721a71871fcdb00ec3fa4441b5b

that I have tested on Windows so far. That patch allows Audacity on that platform to still work with the current maximum FFmpeg 2.3.x but does not allow it to work with later FFmpeg than that. 

A lot has to be done for Audacity to support later FFmpeg than 2.3.x and we also have to consider some compatibility with older FFmpeg between 2.3.x and current. Also we have limited resources. Rather than repeatedly modifying our FFmpeg code for their changes, we may move to GStreamer instead which is also a large change but a once-only change.   

Please post links to the known security problems with FFmpeg 1.2 to 2.3.x. Are you able to offer a future patch that updates Audacity to support later FFmpeg on all platforms?

**Comment by TheNH813** [comment]
I'd definitely be all for a change to GStreamer! FFMpeg is nice but at least in my opinion and experience it's hard to build programs against it and maintain compatibility with the changes in newer versions. That would definitely simplify things quite a bit.

**Comment by walisser** [comment]
41de5b3 has been merged so this PR can be closed. Verified import is still compatible with AVFormat/AVCodec 57.x.x which is part of the 3.1.3 (latest) release.

**Comment by JamesCrook** [comment]
" 41de5b3 has been merged so this PR can be closed. "

Closed now.

**Pull request closed without merging**
