### PR TITLE
fix #4872

### LINKED ISSUE #4872: creating a wxCursor in the global initialisation phase can cause an abort.
#e4ad5331e96036b3ce0b2ed8c79726d3108a6416 introduced a cache variable for a "hand open" cursor with a non-standard hot spot: https://github.com/audacity/audacity/blob/e4ad5331e96036b3ce0b2ed8c79726d3108a6416/src/AdornedRulerPanel.cpp#L741

This leads to an abort on Mac OS X 10.9 (AFAIK still supported), apparently because the Cocoa GUI layer has not yet been initialised properly at this point:

```
> audacity
2023-07-01 17:50:20.337 Audacity[38837:d0b] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error (1000) creating CGSWindow on line 263'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff9547d25c __exceptionPreprocess + 172
        1   libobjc.A.dylib                     0x00007fff92903e75 objc_exception_throw + 43
        2   CoreFoundation                      0x00007fff9547d10c +[NSException raise:format:] + 204
        3   AppKit                              0x00007fff947f6e95 _NSCreateWindowWithOpaqueShape2 + 1403
        4   AppKit                              0x00007fff947f5a21 -[NSWindow _commonAwake] + 3720
        5   AppKit                              0x00007fff946d1400 -[NSWindow _commonInitFrame:styleMask:backing:defer:] + 882
        6   AppKit                              0x00007fff946d0882 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1054
        7   AppKit                              0x00007fff946d0458 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
        8   AppKit                              0x00007fff94e2288d -[NSWindow init] + 95
        9   libwx_osx_cocoau_core-3.1.dylib     0x000000010d0f8010 _Z33wxMacCocoaCreateCursorFromCGImageP7CGImageff + 79
        10  libwx_osx_cocoau_core-3.1.dylib     0x000000010d0dd053 _ZN8wxCursor15CreateFromImageERK7wxImage + 287
        11  libwx_osx_cocoau_core-3.1.dylib     0x000000010d0dcf1b _ZN8wxCursorC2ERK7wxImage + 33
        12  Audacity                            0x000000010af33f88 _Z10MakeCursoriPKPKcii + 264
        13  Audacity                            0x000000010ad7dbd6 _GLOBAL__sub_I_AdornedRulerPanel.cpp + 2678
        14  ???                                 0x00007fff6da94c6e 0x0 + 140735033199726
        15  ???                                 0x00007fff6da94dfa 0x0 + 140735033200122
        16  ???                                 0x00007fff6da91aa2 0x0 + 140735033186978
        17  ???                                 0x00007fff6da91936 0x0 + 140735033186614
        18  ???                                 0x00007fff6da851da 0x0 + 140735033135578
        19  ???                                 0x00007fff6da884ca 0x0 + 140735033148618
        20  ???                                 0x00007fff6da8427b 0x0 + 140735033131643
        21  ???                                 0x00007fff6da8405e 0x0 + 140735033131102
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort
```

I suppose this is not currently happening on any of the commonly used platforms; the reason I'm creating this issue is that it seems to me that creating graphical resources at this stage is not the best kind of practice.

### PR DESCRIPTION
**Pull request by LWinterberg**
Resolves: #4872

PR-ifies the patch provided in that issue. 

@RJVB can you sign the CLA?

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by RJVB** [comment]
Thanks for doing this for me, saves me some time :) I would probably have thrown in the other patches I made to get Audacity running on 10.9, though. Will try to put up a PR for those when I get around to it.

> @RJVB can you sign the [CLA](https://www.audacityteam.org/cla/)?

> [*] I signed the CLA
> [*] There are no behaviour changes unnecessary for the stated purpose of the PR
> [*] Each commit compiles and runs on my machine without known undesirable changes of behaviour

**Review by Paul-Licameli — COMMENTED** [review]
Are these changes complete?

RearrangeCursorXpm is mentioned in other places.  There is a hand cursor for the drag bar at the top of clips, for the bar in a label, and to rearrange the split waveform/spectrum view.

Are there similar problems to fix for those?

**Comment by Paul-Licameli** [comment]
> Are these changes complete?
> 
> RearrangeCursorXpm is mentioned in other places. There is a hand cursor for the drag bar at the top of clips, for the bar in a label, and to rearrange the split waveform/spectrum view.
> 
> Are there similar problems to fix for those?

I'm guessing now that there are no problems, because in those places, static variables are inside functions and not at file scope.

**Review by Paul-Licameli — APPROVED** [review]

**Comment by RJVB** [comment]
>I'm guessing now that there are no problems, because in those places, static variables are inside functions and not at file scope.

They're not even static variables, are they? AFAICT these instances get created when a class instance is created. That's safe as long as it only happens when the graphics context is set up correctly.

**Comment by RJVB** [comment]
>@RJVB FYI: We're nearing code freeze for 3.4, if you want to get the other changes in for that version, please open a PR soon.

Next couple of days are going to be tough for that for me, so how soon is soon? And how much interest is there anyway in keeping Audacity buildable and/or runnable on OS X 10.9?

**Comment by LWinterberg** [comment]
> Next couple of days are going to be tough for that for me, so how soon is soon? 

2 weeks approximately

> And how much interest is there anyway in keeping Audacity buildable and/or runnable on OS X 10.9?

there's a surprising number of people still using Audacity on legacy OSX versions, so having it runnable probably has interest of a couple hundred to a few thousand people. Having it buildable probably is less important.

**Comment by RJVB** [comment]
OK, 2 weeks leaves me a little more time to breathe.

>there's a surprising number of people still using Audacity on legacy OSX versions

Probably a predictable effect of Apple making (or having made, in the past) computers that don't break down but that they don't support anymore. My system is officially limited to 10.13, which is probably considered "legacy" too by now...

>so having it runnable probably has interest of a couple hundred to a few thousand people. Having it buildable probably is less important.

I can only do both, sorry ;)

**Comment by RJVB** [comment]
On Monday August 21 2023 03:44:12 LWinterberg wrote:

>2 weeks approximately

Still in time I hope: #5100

**Pull request merged**
