### PR TITLE
Changed line no. 55 & 56 with  wxString format

### PR DESCRIPTION
**Pull request by Dhriti03**
Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [ ] Each commit's message describes its purpose and effects
- [ ] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by Dhriti03** [comment]
Now y is it giving an error ...........Please can u help me out with this @LWinterberg

**Comment by LWinterberg** [comment]
from the linux output:

```
/home/runner/work/audacity/audacity/src/widgets/Warning.cpp:37:23: note:   no known conversion for argument 2 from ‘const TranslatableString’ to ‘char’
   37 |                  char message1= ("Information") ,
      |                  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```
I think the issue is some of the following: 
* You are using char instead of TranslatableString
* &DefaultWarningFooter() is now not returning anything

You may find some help from the doxygen documentation ([warning dialog](https://doxy.audacityteam.org/class_warning_dialog.html), [translatable string](https://doxy.audacityteam.org/class_translatable_string.html)) or by just googling it. I'm afraid I can't help you much since I'm not a programmer. 

You may also want to compile Audacity locally before submitting a PR.

**Comment by Paul-Licameli** [comment]
Remember some languages have declension of nouns.  The string “information” by itself does not tell the translator that it will be the object of the verb in the other string.

i would just use two strings that are the complete sentences with this one word difference.

**Comment by Dhriti03** [comment]
> Remember some languages have declension of nouns. The string “information” by itself does not tell the translator that it will be the object of the verb in the other string.
> 
> i would just use two strings that are the complete sentences with this one word difference.
Can you please give an example for this

**Comment by Dhriti03** [comment]
Also where can we ask doubts related to these contributions please can you let me know

**Comment by LWinterberg** [comment]
> Can you please give an example for this

```
"don't show this information again"
"don't show this warning again"
```

> Also where can we ask doubts related to these contributions please can you let me know

https://audacityteam.org/devserver

anyway: This issue got solved by #2756. No need to continue with this one.

**Pull request closed without merging**
